package edu.usc.cssl.tacit.crawlers.uscongress.services;

import java.util.HashMap;

public class RepresentativeDetails {
	static HashMap<String, String> representativeDet = new HashMap<String, String>();
	public static HashMap<String, String> getRepersentativeDetails() {
		representativeDet.put("Byrne,Bradley", "R-AL");
		representativeDet.put("Roby, Martha", "R-AL");
		representativeDet.put("Rogers, Mike", "R-AL");
		representativeDet.put("Aderholt, Robert", "R-AL");
		representativeDet.put("Brooks, Mo", "R-AL");
		representativeDet.put("Palmer, Gary", "R-AL");
		representativeDet.put("Sewell, Terri A.", "D-AL");
		representativeDet.put("Young, Don", "R-AK");
		representativeDet.put("Radewagen, Amata", "R-AS");
		representativeDet.put("Kirkpatrick, Ann", "D-AZ");
		representativeDet.put("McSally, Martha", "R-AZ");
		representativeDet.put("Grijalva, Raul", "D-AZ");
		representativeDet.put("Gosar, Paul A.", "R-AZ");
		representativeDet.put("Salmon, Matt", "R-AZ");
		representativeDet.put("Schweikert, David", "R-AZ");
		representativeDet.put("Gallego, Ruben", "D-AZ");
		representativeDet.put("Franks, Trent", "R-AZ");
		representativeDet.put("Sinema, Kyrsten", "D-AZ");
		representativeDet.put("Crawford, Rick", "R-AR");
		representativeDet.put("Hill, French", "R-AR");
		representativeDet.put("Womack, Steve", "R-AR");
		representativeDet.put("Westerman, Bruce", "R-AR");
		representativeDet.put("LaMalfa, Doug", "R-CA");
		representativeDet.put("Huffman, Jared", "D-CA");
		representativeDet.put("Garamendi, John", "D-CA");
		representativeDet.put("McClintock, Tom", "R-CA");
		representativeDet.put("Thompson, Mike", "D-CA");
		representativeDet.put("Matsui, Doris O.", "D-CA");
		representativeDet.put("Bera, Ami", "D-CA");
		representativeDet.put("Cook, Paul", "R-CA");
		representativeDet.put("McNerney, Jerry", "D-CA");
		representativeDet.put("Denham, Jeff", "R-CA");
		representativeDet.put("DeSaulnier, Mark", "D-CA");
		representativeDet.put("Pelosi, Nancy", "D-CA");
		representativeDet.put("Lee, Barbara", "D-CA");
		representativeDet.put("Speier, Jackie", "D-CA");
		representativeDet.put("Swalwell, Eric", "D-CA");
		representativeDet.put("Costa, Jim", "D-CA");
		representativeDet.put("Honda, Mike", "D-CA");
		representativeDet.put("Eshoo, Anna G.", "D-CA");
		representativeDet.put("Lofgren, Zoe", "D-CA");
		representativeDet.put("Farr, Sam", "D-CA");
		representativeDet.put("Valadao, David", "R-CA");
		representativeDet.put("Nunes, Devin", "R-CA");
		representativeDet.put("McCarthy, Kevin", "R-CA");
		representativeDet.put("Capps, Lois", "D-CA");
		representativeDet.put("Knight, Steve", "R-CA");
		representativeDet.put("Brownley, Julia", "D-CA");
		representativeDet.put("Chu, Judy", "D-CA");
		representativeDet.put("Schiff, Adam", "D-CA");
		representativeDet.put("Cárdenas, Tony", "D-CA");
		representativeDet.put("Sherman, Brad", "D-CA");
		representativeDet.put("Aguilar, Pete", "D-CA");
		representativeDet.put("Napolitano, Grace", "D-CA");
		representativeDet.put("Lieu, Ted", "D-CA");
		representativeDet.put("Becerra, Xavier", "D-CA");
		representativeDet.put("Torres, Norma", "D-CA");
		representativeDet.put("Ruiz, Raul", "D-CA");
		representativeDet.put("Bass, Karen", "D-CA");
		representativeDet.put("Sánchez, Linda", "D-CA");
		representativeDet.put("Royce, Ed", "R-CA");
		representativeDet.put("Roybal-Allard, Lucille", "D-CA");
		representativeDet.put("Takano, Mark", "D-CA");
		representativeDet.put("Calvert, Ken", "R-CA");
		representativeDet.put("Waters, Maxine", "D-CA");
		representativeDet.put("Hahn, Janice", "D-CA");
		representativeDet.put("Walters, Mimi", "R-CA");
		representativeDet.put("Sanchez, Loretta", "D-CA");
		representativeDet.put("Lowenthal, Alan", "D-CA");
		representativeDet.put("Rohrabacher, Dana", "R-CA");
		representativeDet.put("Issa, Darrell", "R-CA");
		representativeDet.put("Hunter, Duncan D.", "R-CA");
		representativeDet.put("Vargas, Juan", "D-CA");
		representativeDet.put("Peters, Scott", "D-CA");
		representativeDet.put("Davis, Susan", "D-CA");
		representativeDet.put("DeGette, Diana", "D-CO");
		representativeDet.put("Polis, Jared", "D-CO");
		representativeDet.put("Tipton, Scott", "R-CO");
		representativeDet.put("Buck, Ken", "R-CO");
		representativeDet.put("Lamborn, Doug", "R-CO");
		representativeDet.put("Coffman, Mike", "R-CO");
		representativeDet.put("Perlmutter, Ed", "D-CO");
		representativeDet.put("Larson, John B.", "D-CT");
		representativeDet.put("Courtney, Joe", "D-CT");
		representativeDet.put("DeLauro, Rosa L.", "D-CT");
		representativeDet.put("Himes, Jim", "D-CT");
		representativeDet.put("Esty, Elizabeth", "D-CT");
		representativeDet.put("Carney, John", "D-DE");
		representativeDet.put("Norton, Eleanor Holmes", "D-DC");
		representativeDet.put("Miller, Jeff", "R-FL");
		representativeDet.put("Graham, Gwen", "D-FL");
		representativeDet.put("Yoho, Ted", "R-FL");
		representativeDet.put("Crenshaw, Ander", "R-FL");
		representativeDet.put("Brown, Corrine", "D-FL");
		representativeDet.put("DeSantis, Ron", "R-FL");
		representativeDet.put("Mica, John", "R-FL");
		representativeDet.put("Posey, Bill", "R-FL");
		representativeDet.put("Grayson, Alan", "D-FL");
		representativeDet.put("Webster, Daniel", "R-FL");
		representativeDet.put("Nugent, Richard", "R-FL");
		representativeDet.put("Bilirakis, Gus M.", "R-FL");
		representativeDet.put("Jolly, David", "R-FL");
		representativeDet.put("Castor, Kathy", "D-FL");
		representativeDet.put("Ross, Dennis", "R-FL");
		representativeDet.put("Buchanan, Vern", "R-FL");
		representativeDet.put("Rooney, Tom", "R-FL");
		representativeDet.put("Murphy, Patrick", "D-FL");
		representativeDet.put("Clawson,Curt", "R-FL");
		representativeDet.put("Hastings, Alcee L.", "D-FL");
		representativeDet.put("Deutch, Ted", "D-FL");
		representativeDet.put("Frankel, Lois", "D-FL");
		representativeDet.put("Wasserman Schultz, Debbie", "D-FL");
		representativeDet.put("Wilson, Frederica", "D-FL");
		representativeDet.put("Diaz-Balart, Mario", "R-FL");
		representativeDet.put("Curbelo, Carlos", "R-FL");
		representativeDet.put("Ros-Lehtinen, Ileana", "R-FL");
		representativeDet.put("Carter, Buddy", "R-GA");
		representativeDet.put("Bishop Jr., Sanford D.", "D-GA");
		representativeDet.put("Westmoreland, Lynn A.", "R-GA");
		representativeDet.put("Johnson, Henry C. \"Hank\" Jr.", "D-GA");
		representativeDet.put("Lewis, John", "D-GA");
		representativeDet.put("Price, Tom", "R-GA");
		representativeDet.put("Woodall, Robert", "R-GA");
		representativeDet.put("Scott, Austin", "R-GA");
		representativeDet.put("Collins, Doug", "R-GA");
		representativeDet.put("Hice, Jody", "R-GA");
		representativeDet.put("Loudermilk, Barry", "R-GA");
		representativeDet.put("Allen, Rick", "R-GA");
		representativeDet.put("Scott, David", "D-GA");
		representativeDet.put("Graves, Tom", "R-GA");
		representativeDet.put("Bordallo, Madeleine", "D-GU");
		representativeDet.put("Takai, Mark", "D-HI");
		representativeDet.put("Gabbard, Tulsi", "D-HI");
		representativeDet.put("Labrador, Raul R.", "R-ID");
		representativeDet.put("Simpson, Mike", "R-ID");
		representativeDet.put("Rush, Bobby L.", "D-IL");
		representativeDet.put("Kelly, Robin", "D-IL");
		representativeDet.put("Lipinski, Daniel", "D-IL");
		representativeDet.put("Gutierrez, Luis", "D-IL");
		representativeDet.put("Quigley, Mike", "D-IL");
		representativeDet.put("Roskam, Peter J.", "R-IL");
		representativeDet.put("Davis, Danny K.", "D-IL");
		representativeDet.put("Duckworth, Tammy", "D-IL");
		representativeDet.put("Schakowsky, Jan", "D-IL");
		representativeDet.put("Dold, Bob", "R-IL");
		representativeDet.put("Foster, Bill", "D-IL");
		representativeDet.put("Bost, Mike", "R-IL");
		representativeDet.put("Davis, Rodney", "R-IL");
		representativeDet.put("Hultgren, Randy", "R-IL");
		representativeDet.put("Shimkus, John", "R-IL");
		representativeDet.put("Kinzinger, Adam", "R-IL");
		representativeDet.put("Bustos, Cheri", "D-IL");
		representativeDet.put("Schock, Aaron -- Vacancy", "Vacancy-IL");
		representativeDet.put("Visclosky, Peter", "D-IN");
		representativeDet.put("Walorski, Jackie", "R-IN");
		representativeDet.put("Stutzman, Marlin", "R-IN");
		representativeDet.put("Rokita, Todd", "R-IN");
		representativeDet.put("Brooks, Susan W.", "R-IN");
		representativeDet.put("Messer, Luke", "R-IN");
		representativeDet.put("Carson, André", "D-IN");
		representativeDet.put("Bucshon, Larry", "R-IN");
		representativeDet.put("Young, Todd", "R-IN");
		representativeDet.put("Blum, Rod", "R-IA");
		representativeDet.put("Loebsack, David", "D-IA");
		representativeDet.put("Young, David", "R-IA");
		representativeDet.put("King, Steve", "R-IA");
		representativeDet.put("Huelskamp, Tim", "R-KS");
		representativeDet.put("Jenkins, Lynn", "R-KS");
		representativeDet.put("Yoder, Kevin", "R-KS");
		representativeDet.put("Pompeo, Mike", "R-KS");
		representativeDet.put("Whitfield, Ed", "R-KY");
		representativeDet.put("Guthrie, S. Brett", "R-KY");
		representativeDet.put("Yarmuth, John A.", "D-KY");
		representativeDet.put("Massie, Thomas", "R-KY");
		representativeDet.put("Rogers, Harold", "R-KY");
		representativeDet.put("Barr, Andy", "R-KY");
		representativeDet.put("Scalise, Steve", "R-LA");
		representativeDet.put("Richmond, Cedric", "D-LA");
		representativeDet.put("Boustany Jr., Charles W.", "R-LA");
		representativeDet.put("Fleming, John", "R-LA");
		representativeDet.put("Abraham, Ralph", "R-LA");
		representativeDet.put("Graves, Garret", "R-LA");
		representativeDet.put("Pingree, Chellie", "D-ME");
		representativeDet.put("Poliquin, Bruce", "R-ME");
		representativeDet.put("Harris, Andy", "R-MD");
		representativeDet.put("Ruppersberger, C. A. Dutch", "D-MD");
		representativeDet.put("Sarbanes, John P.", "D-MD");
		representativeDet.put("Edwards, Donna F.", "D-MD");
		representativeDet.put("Hoyer, Steny H.", "D-MD");
		representativeDet.put("Delaney, John", "D-MD");
		representativeDet.put("Cummings, Elijah", "D-MD");
		representativeDet.put("Van Hollen, Chris", "D-MD");
		representativeDet.put("Neal, Richard E.", "D-MA");
		representativeDet.put("McGovern, James", "D-MA");
		representativeDet.put("Tsongas, Niki", "D-MA");
		representativeDet.put("Kennedy III, Joseph P.", "D-MA");
		representativeDet.put("Clark, Katherine", "D-MA");
		representativeDet.put("Moulton, Seth", "D-MA");
		representativeDet.put("Capuano, Michael E.", "D-MA");
		representativeDet.put("Lynch, Stephen F.", "D-MA");
		representativeDet.put("Keating, William", "D-MA");
		representativeDet.put("Benishek, Dan", "R-MI");
		representativeDet.put("Huizenga, Bill", "R-MI");
		representativeDet.put("Amash, Justin", "R-MI");
		representativeDet.put("Moolenaar, John", "R-MI");
		representativeDet.put("Kildee, Daniel", "D-MI");
		representativeDet.put("Upton, Fred", "R-MI");
		representativeDet.put("Walberg, Tim", "R-MI");
		representativeDet.put("Bishop, Mike", "R-MI");
		representativeDet.put("Levin, Sander", "D-MI");
		representativeDet.put("Miller, Candice", "R-MI");
		representativeDet.put("Trott, Dave", "R-MI");
		representativeDet.put("Dingell, Debbie", "D-MI");
		representativeDet.put("Conyers Jr., John", "D-MI");
		representativeDet.put("Lawrence, Brenda", "D-MI");
		representativeDet.put("Walz, Timothy J.", "D-MN");
		representativeDet.put("Kline, John", "R-MN");
		representativeDet.put("Paulsen, Erik", "R-MN");
		representativeDet.put("McCollum, Betty", "D-MN");
		representativeDet.put("Ellison, Keith", "D-MN");
		representativeDet.put("Emmer, Tom", "R-MN");
		representativeDet.put("Peterson, Collin C.", "D-MN");
		representativeDet.put("Nolan, Rick", "D-MN");
		representativeDet.put("Kelly, Trent", "R-MS");
		representativeDet.put("Thompson, Bennie G.", "D-MS");
		representativeDet.put("Harper, Gregg", "R-MS");
		representativeDet.put("Palazzo, Steven", "R-MS");
		representativeDet.put("Clay Jr., William \"Lacy\"", "D-MO");
		representativeDet.put("Wagner, Ann", "R-MO");
		representativeDet.put("Luetkemeyer, Blaine", "R-MO");
		representativeDet.put("Hartzler, Vicky", "R-MO");
		representativeDet.put("Cleaver, Emanuel", "D-MO");
		representativeDet.put("Graves, Sam", "R-MO");
		representativeDet.put("Long, Billy", "R-MO");
		representativeDet.put("Smith, Jason", "R-MO");
		representativeDet.put("Zinke, Ryan", "R-MT");
		representativeDet.put("Fortenberry, Jeff", "R-NE");
		representativeDet.put("Ashford, Brad", "D-NE");
		representativeDet.put("Smith, Adrian", "R-NE");
		representativeDet.put("Titus, Dina", "D-NV");
		representativeDet.put("Amodei, Mark", "R-NV");
		representativeDet.put("Heck, Joe", "R-NV");
		representativeDet.put("Hardy, Cresent", "R-NV");
		representativeDet.put("Guinta, Frank", "R-NH");
		representativeDet.put("Kuster, Ann", "D-NH");
		representativeDet.put("Norcross, Donald", "D-NJ");
		representativeDet.put("LoBiondo, Frank", "R-NJ");
		representativeDet.put("MacArthur, Tom", "R-NJ");
		representativeDet.put("Smith, Chris", "R-NJ");
		representativeDet.put("Garrett, Scott", "R-NJ");
		representativeDet.put("Pallone Jr., Frank", "D-NJ");
		representativeDet.put("Lance, Leonard", "R-NJ");
		representativeDet.put("Sires, Albio", "D-NJ");
		representativeDet.put("Pascrell Jr., Bill", "D-NJ");
		representativeDet.put("Payne Jr., Donald", "D-NJ");
		representativeDet.put("Frelinghuysen, Rodney", "R-NJ");
		representativeDet.put("Watson Coleman, Bonnie", "D-NJ");
		representativeDet.put("Lujan Grisham, Michelle", "D-NM");
		representativeDet.put("Pearce, Steve", "R-NM");
		representativeDet.put("Lujan, Ben R.", "D-NM");
		representativeDet.put("Zeldin, Lee", "R-NY");
		representativeDet.put("King, Pete", "R-NY");
		representativeDet.put("Israel, Steve", "D-NY");
		representativeDet.put("Rice, Kathleen", "D-NY");
		representativeDet.put("Meeks, Gregory W.", "D-NY");
		representativeDet.put("Meng, Grace", "D-NY");
		representativeDet.put("Velázquez, Nydia M.", "D-NY");
		representativeDet.put("Jeffries, Hakeem", "D-NY");
		representativeDet.put("Clarke, Yvette D.", "D-NY");
		representativeDet.put("Nadler, Jerrold", "D-NY");
		representativeDet.put("Donovan, Daniel", "R-NY");
		representativeDet.put("Maloney, Carolyn", "D-NY");
		representativeDet.put("Rangel, Charles B.", "D-NY");
		representativeDet.put("Crowley, Joseph", "D-NY");
		representativeDet.put("Serrano, José E.", "D-NY");
		representativeDet.put("Engel, Eliot", "D-NY");
		representativeDet.put("Lowey, Nita", "D-NY");
		representativeDet.put("Maloney, Sean Patrick", "D-NY");
		representativeDet.put("Gibson, Chris", "R-NY");
		representativeDet.put("Tonko, Paul D.", "D-NY");
		representativeDet.put("Stefanik, Elise", "R-NY");
		representativeDet.put("Hanna, Richard", "R-NY");
		representativeDet.put("Reed, Tom", "R-NY");
		representativeDet.put("Katko, John", "R-NY");
		representativeDet.put("Slaughter, Louise", "D-NY");
		representativeDet.put("Higgins, Brian", "D-NY");
		representativeDet.put("Collins, Chris", "R-NY");
		representativeDet.put("Butterfield, G.K.", "D-NC");
		representativeDet.put("Ellmers, Renee", "R-NC");
		representativeDet.put("Jones, Walter B.", "R-NC");
		representativeDet.put("Price, David", "D-NC");
		representativeDet.put("Foxx, Virginia", "R-NC");
		representativeDet.put("Walker, Mark", "R-NC");
		representativeDet.put("Rouzer, David", "R-NC");
		representativeDet.put("Hudson, Richard", "R-NC");
		representativeDet.put("Pittenger, Robert", "R-NC");
		representativeDet.put("McHenry, Patrick T.", "R-NC");
		representativeDet.put("Meadows, Mark", "R-NC");
		representativeDet.put("Adams, Alma", "D-NC");
		representativeDet.put("Holding, George", "R-NC");
		representativeDet.put("Cramer, Kevin", "R-ND");
		representativeDet.put("Sablan, Gregorio", "D-MP");
		representativeDet.put("Chabot, Steve", "R-OH");
		representativeDet.put("Wenstrup, Brad", "R-OH");
		representativeDet.put("Beatty, Joyce", "D-OH");
		representativeDet.put("Jordan, Jim", "R-OH");
		representativeDet.put("Latta, Robert E.", "R-OH");
		representativeDet.put("Johnson, Bill", "R-OH");
		representativeDet.put("Gibbs, Bob", "R-OH");
		representativeDet.put("Boehner, John A.", "R-OH");
		representativeDet.put("Kaptur, Marcy", "D-OH");
		representativeDet.put("Turner, Michael", "R-OH");
		representativeDet.put("Fudge, Marcia L.", "D-OH");
		representativeDet.put("Tiberi, Pat", "R-OH");
		representativeDet.put("Ryan, Tim", "D-OH");
		representativeDet.put("Joyce, David", "R-OH");
		representativeDet.put("Stivers, Steve", "R-OH");
		representativeDet.put("Renacci, Jim", "R-OH");
		representativeDet.put("Bridenstine, Jim", "R-OK");
		representativeDet.put("Mullin, Markwayne", "R-OK");
		representativeDet.put("Lucas, Frank", "R-OK");
		representativeDet.put("Cole, Tom", "R-OK");
		representativeDet.put("Russell, Steve", "R-OK");
		representativeDet.put("Bonamici, Suzanne", "D-OR");
		representativeDet.put("Walden, Greg", "R-OR");
		representativeDet.put("Blumenauer, Earl", "D-OR");
		representativeDet.put("DeFazio, Peter", "D-OR");
		representativeDet.put("Schrader, Kurt", "D-OR");
		representativeDet.put("Brady, Robert", "D-PA");
		representativeDet.put("Fattah, Chaka", "D-PA");
		representativeDet.put("Kelly, Mike", "R-PA");
		representativeDet.put("Perry, Scott", "R-PA");
		representativeDet.put("Thompson, Glenn W.", "R-PA");
		representativeDet.put("Costello, Ryan", "R-PA");
		representativeDet.put("Meehan, Pat", "R-PA");
		representativeDet.put("Fitzpatrick, Michael G.", "R-PA");
		representativeDet.put("Shuster, Bill", "R-PA");
		representativeDet.put("Marino, Tom", "R-PA");
		representativeDet.put("Barletta, Lou", "R-PA");
		representativeDet.put("Rothfus, Keith", "R-PA");
		representativeDet.put("Boyle, Brendan", "D-PA");
		representativeDet.put("Doyle, Mike", "D-PA");
		representativeDet.put("Dent, Charles W.", "R-PA");
		representativeDet.put("Pitts, Joseph R.", "R-PA");
		representativeDet.put("Cartwright, Matthew", "D-PA");
		representativeDet.put("Murphy, Tim", "R-PA");
		representativeDet.put("Pierluisi, Pedro", "D-PR");
		representativeDet.put("Cicilline, David", "D-RI");
		representativeDet.put("Langevin, Jim", "D-RI");
		representativeDet.put("Sanford, Mark", "R-SC");
		representativeDet.put("Wilson, Joe", "R-SC");
		representativeDet.put("Duncan, Jeff", "R-SC");
		representativeDet.put("Gowdy, Trey", "R-SC");
		representativeDet.put("Mulvaney, Mick", "R-SC");
		representativeDet.put("Clyburn, James E.", "D-SC");
		representativeDet.put("Rice, Tom", "R-SC");
		representativeDet.put("Noem, Kristi", "R-SD");
		representativeDet.put("Roe, Phil", "R-TN");
		representativeDet.put("Duncan Jr., John J.", "R-TN");
		representativeDet.put("Fleischmann, Chuck", "R-TN");
		representativeDet.put("DesJarlais, Scott", "R-TN");
		representativeDet.put("Cooper, Jim", "D-TN");
		representativeDet.put("Black, Diane", "R-TN");
		representativeDet.put("Blackburn, Marsha", "R-TN");
		representativeDet.put("Fincher, Stephen", "R-TN");
		representativeDet.put("Cohen, Steve", "D-TN");
		representativeDet.put("Gohmert, Louie", "R-TX");
		representativeDet.put("Poe, Ted", "R-TX");
		representativeDet.put("Johnson, Sam", "R-TX");
		representativeDet.put("Ratcliffe, John", "R-TX");
		representativeDet.put("Hensarling, Jeb", "R-TX");
		representativeDet.put("Barton, Joe", "R-TX");
		representativeDet.put("Culberson, John", "R-TX");
		representativeDet.put("Brady, Kevin", "R-TX");
		representativeDet.put("Green, Al", "D-TX");
		representativeDet.put("McCaul, Michael T.", "R-TX");
		representativeDet.put("Conaway, K. Michael", "R-TX");
		representativeDet.put("Granger, Kay", "R-TX");
		representativeDet.put("Thornberry, Mac", "R-TX");
		representativeDet.put("Weber, Randy", "R-TX");
		representativeDet.put("Hinojosa, Rubén", "D-TX");
		representativeDet.put("O'Rourke, Beto", "D-TX");
		representativeDet.put("Flores, Bill", "R-TX");
		representativeDet.put("Jackson Lee, Sheila", "D-TX");
		representativeDet.put("Neugebauer, Randy", "R-TX");
		representativeDet.put("Castro, Joaquin", "D-TX");
		representativeDet.put("Smith, Lamar", "R-TX");
		representativeDet.put("Olson, Pete", "R-TX");
		representativeDet.put("Hurd, Will", "R-TX");
		representativeDet.put("Marchant, Kenny", "R-TX");
		representativeDet.put("Williams, Roger", "R-TX");
		representativeDet.put("Burgess, Michael", "R-TX");
		representativeDet.put("Farenthold, Blake", "R-TX");
		representativeDet.put("Cuellar, Henry", "D-TX");
		representativeDet.put("Green, Gene", "D-TX");
		representativeDet.put("Johnson, Eddie Bernice", "D-TX");
		representativeDet.put("Carter, John", "R-TX");
		representativeDet.put("Sessions, Pete", "R-TX");
		representativeDet.put("Veasey, Marc", "D-TX");
		representativeDet.put("Vela, Filemon", "D-TX");
		representativeDet.put("Doggett, Lloyd", "D-TX");
		representativeDet.put("Babin, Brian", "R-TX");
		representativeDet.put("Bishop, Rob", "R-UT");
		representativeDet.put("Stewart, Chris", "R-UT");
		representativeDet.put("Chaffetz, Jason", "R-UT");
		representativeDet.put("Love, Mia", "R-UT");
		representativeDet.put("Welch, Peter", "D-VT");
		representativeDet.put("Plaskett, Stacey", "D-VI");
		representativeDet.put("Wittman, Robert J.", "R-VA");
		representativeDet.put("Rigell, Scott", "R-VA");
		representativeDet.put("Scott, Robert C.", "D-VA");
		representativeDet.put("Forbes, J. Randy", "R-VA");
		representativeDet.put("Hurt, Robert", "R-VA");
		representativeDet.put("Goodlatte, Bob", "R-VA");
		representativeDet.put("Brat, Dave", "R-VA");
		representativeDet.put("Beyer, Don", "D-VA");
		representativeDet.put("Griffith, Morgan", "R-VA");
		representativeDet.put("Comstock, Barbara", "R-VA");
		representativeDet.put("Connolly, Gerald E. \"Gerry\"", "D-VA");
		representativeDet.put("DelBene, Suzan", "D-WA");
		representativeDet.put("Larsen, Rick", "D-WA");
		representativeDet.put("Herrera Beutler, Jaime", "R-WA");
		representativeDet.put("Newhouse, Dan", "R-WA");
		representativeDet.put("McMorris Rodgers, Cathy", "R-WA");
		representativeDet.put("Kilmer, Derek", "D-WA");
		representativeDet.put("McDermott, Jim", "D-WA");
		representativeDet.put("Reichert, David G.", "R-WA");
		representativeDet.put("Smith, Adam", "D-WA");
		representativeDet.put("Heck, Denny", "D-WA");
		representativeDet.put("McKinley, David", "R-WV");
		representativeDet.put("Mooney, Alex", "R-WV");
		representativeDet.put("Jenkins, Evan", "R-WV");
		representativeDet.put("Ryan, Paul", "R-WI");
		representativeDet.put("Pocan, Mark", "D-WI");
		representativeDet.put("Kind, Ron", "D-WI");
		representativeDet.put("Moore, Gwen", "D-WI");
		representativeDet.put("Sensenbrenner, F. James", "R-WI");
		representativeDet.put("Grothman, Glenn", "R-WI");
		representativeDet.put("Duffy, Sean P.", "R-WI");
		representativeDet.put("Ribble, Reid", "R-WI");
		representativeDet.put("Lummis, Cynthia M.", "R-WY");

		//from 109
		representativeDet.put("Abercrombie, Neil", "D-HI-1");
		representativeDet.put("Ackerman, Gary L.", "D-NY-5");
		representativeDet.put("Aderholt, Robert B.", "R-AL-4");
		representativeDet.put("Akin, W. Todd", "R-MO-2");
		representativeDet.put("Alexander, Rodney", "R-LA-5");
		representativeDet.put("Allen, Thomas H.", "D-ME-1");
		representativeDet.put("Andrews, Robert E.", "D-NJ-1");
		representativeDet.put("Baca, Joe", "D-CA-43");
		representativeDet.put("Bachus, Spencer", "R-AL-6");
		representativeDet.put("Baird, Brian", "D-WA-3");
		representativeDet.put("Baker, Richard H.", "R-LA-6");
		representativeDet.put("Baldwin, Tammy", "D-WI-2");
		representativeDet.put("Barrett, J. Gresham", "R-SC-3");
		representativeDet.put("Barrow, John", "D-GA-12");
		representativeDet.put("Bartlett, Roscoe G.", "R-MD-6");
		representativeDet.put("Bass, Charles F.", "R-NH-2");
		representativeDet.put("Bean, Melissa L.", "D-IL-8");
		representativeDet.put("Beauprez, Bob", "R-CO-7");
		representativeDet.put("Berkley, Shelley", "D-NV-1");
		representativeDet.put("Berman, Howard L.", "D-CA-28");
		representativeDet.put("Berry, Marion", "D-AR-1");
		representativeDet.put("Biggert, Judy", "R-IL-13");
		representativeDet.put("Bilirakis, Michael", "R-FL-9");
		representativeDet.put("Bishop, Sanford D., Jr.", "D-GA-2");
		representativeDet.put("Bishop, Timothy H.", "D-NY-1");
		representativeDet.put("Blunt, Roy", "R-MO-7");
		representativeDet.put("Boehlert, Sherwood", "R-NY-24");
		representativeDet.put("Bonilla, Henry", "R-TX-23");
		representativeDet.put("Bonner, Jo", "R-AL-1");
		representativeDet.put("Bono, Mary", "R-CA-45");
		representativeDet.put("Boozman, John", "R-AR-3");
		representativeDet.put("Bordallo, Madeleine Z.", "D-GU");
		representativeDet.put("Boren, Dan", "D-OK-2");
		representativeDet.put("Boswell, Leonard L.", "D-IA-3");
		representativeDet.put("Boucher, Rick", "D-VA-9");
		representativeDet.put("Boustany, Charles W., Jr.", "R-LA-7");
		representativeDet.put("Boyd, Allen", "D-FL-2");
		representativeDet.put("Bradley, Jeb", "R-NH-1");
		representativeDet.put("Brady, Robert A.", "D-PA-1");
		representativeDet.put("Brown, Henry E., Jr.", "R-SC-1");
		representativeDet.put("Brown, Sherrod", "D-OH-13");
		representativeDet.put("Brown-Waite, Ginny", "R-FL-5");
		representativeDet.put("Burgess, Michael C.", "R-TX-26");
		representativeDet.put("Burton, Dan", "R-IN-5");
		representativeDet.put("Butterfield, G. K.", "D-NC-1");
		representativeDet.put("Buyer, Steve", "R-IN-4");
		representativeDet.put("Camp, Dave", "R-MI-4");
		representativeDet.put("Campbell, John", "R-CA-48");
		representativeDet.put("Cannon, Chris", "R-UT-3");
		representativeDet.put("Cantor, Eric", "R-VA-7");
		representativeDet.put("Capito, Shelley Moore", "R-WV-2");
		representativeDet.put("Cardin, Benjamin L.", "D-MD-3");
		representativeDet.put("Cardoza, Dennis A.", "D-CA-18");
		representativeDet.put("Carnahan, Russ", "D-MO-3");
		representativeDet.put("Carson, Julia", "D-IN-7");
		representativeDet.put("Carter, John R.", "R-TX-31");
		representativeDet.put("Case, Ed", "D-HI-2");
		representativeDet.put("Castle, Michael N.", "R-DE");
		representativeDet.put("Chandler, Ben", "D-KY-6");
		representativeDet.put("Chocola, Chris", "R-IN-2");
		representativeDet.put("Christensen, Donna M.", "D-VI");
		representativeDet.put("Clay, Wm. Lacy", "D-MO-1");
		representativeDet.put("Coble, Howard", "R-NC-6");
		representativeDet.put("Conyers, John, Jr.", "D-MI-14");
		representativeDet.put("Costello, Jerry F.", "D-IL-12");
		representativeDet.put("Cox, Christopher", "R-CA-48");
		representativeDet.put("Cramer, Robert E. (Bud), Jr.", "D-AL-5");
		representativeDet.put("Cubin, Barbara", "R-WY");
		representativeDet.put("Culberson, John Abney", "R-TX-7");
		representativeDet.put("Cummings, Elijah E.", "D-MD-7");
		representativeDet.put("Cunningham, Randy (Duke)", "R-CA-50");
		representativeDet.put("Davis, Artur", "D-AL-7");
		representativeDet.put("Davis, Geoff", "R-KY-4");
		representativeDet.put("Davis, Jim", "D-FL-11");
		representativeDet.put("Davis, Jo Ann", "R-VA-1");
		representativeDet.put("Davis, Lincoln", "D-TN-4");
		representativeDet.put("Davis, Susan A.", "D-CA-53");
		representativeDet.put("Davis, Tom", "R-VA-11");
		representativeDet.put("Deal, Nathan", "R-GA-10");
		representativeDet.put("DeFazio, Peter A.", "D-OR-4");
		representativeDet.put("Delahunt, William D.", "D-MA-10");
		representativeDet.put("DeLay, Tom", "R-TX-22");
		representativeDet.put("Diaz-Balart, Lincoln", "R-FL-21");
		representativeDet.put("Dicks, Norman D.", "D-WA-6");
		representativeDet.put("Dingell, John D.", "D-MI-15");
		representativeDet.put("Doolittle, John T.", "R-CA-4");
		representativeDet.put("Doyle, Michael F.", "D-PA-14");
		representativeDet.put("Drake, Thelma D.", "R-VA-2");
		representativeDet.put("Dreier, David", "R-CA-26");
		representativeDet.put("Duncan, John J., Jr.", "R-TN-2");
		representativeDet.put("Edwards, Chet", "D-TX-17");
		representativeDet.put("Ehlers, Vernon J.", "R-MI-3");
		representativeDet.put("Emanuel, Rahm", "D-IL-5");
		representativeDet.put("Emerson, Jo Ann", "R-MO-8");
		representativeDet.put("Engel, Eliot L.", "D-NY-17");
		representativeDet.put("English, Phil", "R-PA-3");
		representativeDet.put("Etheridge, Bob", "D-NC-2");
		representativeDet.put("Evans, Lane", "D-IL-17");
		representativeDet.put("Everett, Terry", "R-AL-2");
		representativeDet.put("Faleomavaega, Eni F. H.", "D-AS");
		representativeDet.put("Feeney, Tom", "R-FL-24");
		representativeDet.put("Ferguson, Mike", "R-NJ-7");
		representativeDet.put("Filner, Bob", "D-CA-51");
		representativeDet.put("Flake, Jeff", "R-AZ-6");
		representativeDet.put("Foley, Mark", "R-FL-16");
		representativeDet.put("Ford, Harold E., Jr.", "D-TN-9");
		representativeDet.put("Fortuno, Luis G.", "R-PR");
		representativeDet.put("Fossella, Vito", "R-NY-13");
		representativeDet.put("Frank, Barney", "D-MA-4");
		representativeDet.put("Frelinghuysen, Rodney P.", "R-NJ-11");
		representativeDet.put("Gallegly, Elton", "R-CA-24");
		representativeDet.put("Gerlach, Jim", "R-PA-6");
		representativeDet.put("Gibbons, Jim", "R-NV-2");
		representativeDet.put("Gilchrest, Wayne T.", "R-MD-1");
		representativeDet.put("Gillmor, Paul E.", "R-OH-5");
		representativeDet.put("Gingrey, Phil", "R-GA-11");
		representativeDet.put("Gonzalez, Charles A.", "D-TX-20");
		representativeDet.put("Goode, Virgil H., Jr.", "R-VA-5");
		representativeDet.put("Gordon, Bart", "D-TN-6");
		representativeDet.put("Green, Mark", "R-WI-8");
		representativeDet.put("Grijalva, Raul M.", "D-AZ-7");
		representativeDet.put("Gutierrez, Luis V.", "D-IL-4");
		representativeDet.put("Gutknecht, Gil", "R-MN-1");
		representativeDet.put("Hall, Ralph M.", "R-TX-4");
		representativeDet.put("Harman, Jane", "D-CA-36");
		representativeDet.put("Harris, Katherine", "R-FL-13");
		representativeDet.put("Hart, Melissa A.", "R-PA-4");
		representativeDet.put("Hastert, J. Dennis", "R-IL-14");
		representativeDet.put("Hastings, Doc", "R-WA-4");
		representativeDet.put("Hayes, Robin", "R-NC-8");
		representativeDet.put("Hayworth, J. D.", "R-AZ-5");
		representativeDet.put("Hefley, Joel", "R-CO-5");
		representativeDet.put("Herger, Wally", "R-CA-2");
		representativeDet.put("Herseth, Stephanie", "D-SD");
		representativeDet.put("Hinchey, Maurice D.", "D-NY-22");
		representativeDet.put("Hinojosa, Ruben", "D-TX-15");
		representativeDet.put("Hobson, David L.", "R-OH-7");
		representativeDet.put("Hoekstra, Peter", "R-MI-2");
		representativeDet.put("Holden, Tim", "D-PA-17");
		representativeDet.put("Holt, Rush D.", "D-NJ-12");
		representativeDet.put("Honda, Michael M.", "D-CA-15");
		representativeDet.put("Hooley, Darlene", "D-OR-5");
		representativeDet.put("Hostettler, John N.", "R-IN-8");
		representativeDet.put("Hulshof, Kenny C.", "R-MO-9");
		representativeDet.put("Hunter, Duncan", "R-CA-52");
		representativeDet.put("Hyde, Henry J.", "R-IL-6");
		representativeDet.put("Inglis, Bob", "R-SC-4");
		representativeDet.put("Inslee, Jay", "D-WA-1");
		representativeDet.put("Issa, Darrell E.", "R-CA-49");
		representativeDet.put("Istook, Ernest J., Jr.", "R-OK-5");
		representativeDet.put("Jackson, Jesse L., Jr.", "D-IL-2");
		representativeDet.put("Jackson-Lee, Sheila", "D-TX-18");
		representativeDet.put("Jefferson, William J.", "D-LA-2");
		representativeDet.put("Jenkins, William L.", "R-TN-1");
		representativeDet.put("Jindal, Bobby", "R-LA-1");
		representativeDet.put("Johnson, Nancy L.", "R-CT-5");
		representativeDet.put("Johnson, Timothy V.", "R-IL-15");
		representativeDet.put("Jones, Stephanie Tubbs", "D-OH-11");
		representativeDet.put("Jones, Walter B., Jr.", "R-NC-3");
		representativeDet.put("Kanjorski, Paul E.", "D-PA-11");
		representativeDet.put("Keller, Ric", "R-FL-8");
		representativeDet.put("Kelly, Sue W.", "R-NY-19");
		representativeDet.put("Kennedy, Mark R.", "R-MN-6");
		representativeDet.put("Kennedy, Patrick J.", "D-RI-1");
		representativeDet.put("Kildee, Dale E.", "D-MI-5");
		representativeDet.put("Kilpatrick, Carolyn C.", "D-MI-13");
		representativeDet.put("King, Peter T.", "R-NY-3");
		representativeDet.put("Kingston, Jack", "R-GA-1");
		representativeDet.put("Kirk, Mark Steven", "R-IL-10");
		representativeDet.put("Knollenberg, Joe", "R-MI-9");
		representativeDet.put("Kolbe, Jim", "R-AZ-8");
		representativeDet.put("Kucinich, Dennis J.", "D-OH-10");
		representativeDet.put("Kuhl, John R. (Randy), Jr.", "R-NY-29");
		representativeDet.put("LaHood, Ray", "R-IL-18");
		representativeDet.put("Langevin, James R.", "D-RI-2");
		representativeDet.put("Lantos, Tom", "D-CA-12");
		representativeDet.put("Latham, Tom", "R-IA-4");
		representativeDet.put("LaTourette, Steve C.", "R-OH-14");
		representativeDet.put("Leach, James A.", "R-IA-2");
		representativeDet.put("Levin, Sander M.", "D-MI-12");
		representativeDet.put("Lewis, Jerry", "R-CA-41");
		representativeDet.put("Lewis, Ron", "R-KY-2");
		representativeDet.put("Linder, John", "R-GA-7");
		representativeDet.put("LoBiondo, Frank A.", "R-NJ-2");
		representativeDet.put("Lowey, Nita M.", "D-NY-18");
		representativeDet.put("Lucas, Frank D.", "R-OK-3");
		representativeDet.put("Lungren, Daniel E.", "R-CA-3");
		representativeDet.put("Mack, Connie", "R-FL-14");
		representativeDet.put("Maloney, Carolyn B.", "D-NY-14");
		representativeDet.put("Manzullo, Donald A.", "R-IL-16");
		representativeDet.put("Markey, Edward J.", "D-MA-7");
		representativeDet.put("Marshall, Jim", "D-GA-3");
		representativeDet.put("Matheson, Jim", "D-UT-2");
		representativeDet.put("Matsui, Robert T.", "D-CA-5");
		representativeDet.put("McCarthy, Carolyn", "D-NY-4");
		representativeDet.put("McCotter, Thaddeus G.", "R-MI-11");
		representativeDet.put("McCrery, Jim", "R-LA-4");
		representativeDet.put("McGovern, James P.", "D-MA-3");
		representativeDet.put("McHugh, John M.", "R-NY-23");
		representativeDet.put("McIntyre, Mike", "D-NC-7");
		representativeDet.put("McKeon, Howard P. (Buck)", "R-CA-25");
		representativeDet.put("McKinney, Cynthia", "D-GA-4");
		representativeDet.put("McMorris, Cathy", "R-WA-5");
		representativeDet.put("McNulty, Michael R.", "D-NY-21");
		representativeDet.put("Meehan, Martin T.", "D-MA-5");
		representativeDet.put("Meek, Kendrick B.", "D-FL-17");
		representativeDet.put("Melancon, Charlie", "D-LA-3");
		representativeDet.put("Menendez, Robert", "D-NJ-13");
		representativeDet.put("Mica, John L.", "R-FL-7");
		representativeDet.put("Michaud, Michael H.", "D-ME-2");
		representativeDet.put("Millender-McDonald, Juanita", "D-CA-37");
		representativeDet.put("Miller, Brad", "D-NC-13");
		representativeDet.put("Miller, Candice S.", "R-MI-10");
		representativeDet.put("Miller, Gary G.", "R-CA-42");
		representativeDet.put("Miller, George", "D-CA-7");
		representativeDet.put("Mollohan, Alan B.", "D-WV-1");
		representativeDet.put("Moore, Dennis", "D-KS-3");
		representativeDet.put("Moran, James P.", "D-VA-8");
		representativeDet.put("Moran, Jerry", "R-KS-1");
		representativeDet.put("Murtha, John P.", "D-PA-12");
		representativeDet.put("Musgrave, Marilyn N.", "R-CO-4");
		representativeDet.put("Myrick, Sue", "R-NC-9");
		representativeDet.put("Napolitano, Grace F.", "D-CA-38");
		representativeDet.put("Ney, Robert W.", "R-OH-18");
		representativeDet.put("Northup, Anne M.", "R-KY-3");
		representativeDet.put("Norwood, Charlie", "R-GA-9");
		representativeDet.put("Nussle, Jim", "R-IA-1");
		representativeDet.put("Oberstar, James L.", "D-MN-8");
		representativeDet.put("Obey, David R.", "D-WI-7");
		representativeDet.put("Olver, John W.", "D-MA-1");
		representativeDet.put("Ortiz, Solomon P.", "D-TX-27");
		representativeDet.put("Osborne, Tom", "R-NE-3");
		representativeDet.put("Otter, C. L. (Butch)", "R-ID-1");
		representativeDet.put("Owens, Major R.", "D-NY-11");
		representativeDet.put("Oxley, Michael G.", "R-OH-4");
		representativeDet.put("Pallone, Frank, Jr.", "D-NJ-6");
		representativeDet.put("Pascrell, Bill, Jr.", "D-NJ-8");
		representativeDet.put("Pastor, Ed", "D-AZ-4");
		representativeDet.put("Paul, Ron", "R-TX-14");
		representativeDet.put("Payne, Donald M.", "D-NJ-10");
		representativeDet.put("Pearce, Stevan", "R-NM-2");
		representativeDet.put("Pence, Mike", "R-IN-6");
		representativeDet.put("Peterson, John E.", "R-PA-5");
		representativeDet.put("Petri, Thomas E.", "R-WI-6");
		representativeDet.put("Pickering, Charles W. (Chip)", "R-MS-3");
		representativeDet.put("Platts, Todd Russell", "R-PA-19");
		representativeDet.put("Pombo, Richard W.", "R-CA-11");
		representativeDet.put("Pomeroy, Earl", "D-ND");
		representativeDet.put("Porter, Jon C.", "R-NV-3");
		representativeDet.put("Portman, Rob", "R-OH-2");
		representativeDet.put("Price, David E.", "D-NC-4");
		representativeDet.put("Pryce, Deborah", "R-OH-15");
		representativeDet.put("Putnam, Adam H.", "R-FL-12");
		representativeDet.put("Radanovich, George", "R-CA-19");
		representativeDet.put("Rahall, Nick J., II", "D-WV-3");
		representativeDet.put("Ramstad, Jim", "R-MN-3");
		representativeDet.put("Regula, Ralph", "R-OH-16");
		representativeDet.put("Rehberg, Dennis R.", "R-MT");
		representativeDet.put("Renzi, Rick", "R-AZ-1");
		representativeDet.put("Reyes, Silvestre", "D-TX-16");
		representativeDet.put("Reynolds, Thomas M.", "R-NY-26");
		representativeDet.put("Rogers, Mike D.", "R-AL-3");
		representativeDet.put("Ross, Mike", "D-AR-4");
		representativeDet.put("Rothman, Steven R.", "D-NJ-9");
		representativeDet.put("Royce, Edward R.", "R-CA-40");
		representativeDet.put("Ryun, Jim", "R-KS-2");
		representativeDet.put("Sabo, Martin Olav", "D-MN-5");
		representativeDet.put("Salazar, John T.", "D-CO-3");
		representativeDet.put("Sanchez, Linda T.", "D-CA-39");
		representativeDet.put("Sanders, Bernard", "I-VT");
		representativeDet.put("Saxton, Jim", "R-NJ-3");
		representativeDet.put("Schakowsky, Janice D.", "D-IL-9");
		representativeDet.put("Schiff, Adam B.", "D-CA-29");
		representativeDet.put("Schmidt, Jean", "R-OH-2");
		representativeDet.put("Schwartz, Allyson Y.", "D-PA-13");
		representativeDet.put("Schwarz, John J. H. (Joe)", "R-MI-7");
		representativeDet.put("Sensenbrenner, F. James, Jr.", "R-WI-5");
		representativeDet.put("Serrano, Jose E.", "D-NY-16");
		representativeDet.put("Shadegg, John B.", "R-AZ-3");
		representativeDet.put("Shaw, E. Clay, Jr.", "R-FL-22");
		representativeDet.put("Shays, Christopher", "R-CT-4");
		representativeDet.put("Sherwood, Don", "R-PA-10");
		representativeDet.put("Simmons, Rob", "R-CT-2");
		representativeDet.put("Simpson, Michael K.", "R-ID-2");
		representativeDet.put("Skelton, Ike", "D-MO-4");
		representativeDet.put("Slaughter, Louise McIntosh", "D-NY-28");
		representativeDet.put("Smith, Christopher H.", "R-NJ-4");
		representativeDet.put("Smith, Lamar S.", "R-TX-21");
		representativeDet.put("Snyder, Vic", "D-AR-2");
		representativeDet.put("Sodrel, Michael E.", "R-IN-9");
		representativeDet.put("Solis, Hilda L.", "D-CA-32");
		representativeDet.put("Souder, Mark E.", "R-IN-3");
		representativeDet.put("Spratt, John M., Jr.", "D-SC-5");
		representativeDet.put("Stark, Fortney Pete", "D-CA-13");
		representativeDet.put("Stearns, Cliff", "R-FL-6");
		representativeDet.put("Strickland, Ted", "D-OH-6");
		representativeDet.put("Stupak, Bart", "D-MI-1");
		representativeDet.put("Sullivan, John", "R-OK-1");
		representativeDet.put("Sweeney, John E.", "R-NY-20");
		representativeDet.put("Tancredo, Thomas G.", "R-CO-6");
		representativeDet.put("Tanner, John S.", "D-TN-8");
		representativeDet.put("Tauscher, Ellen O.", "D-CA-10");
		representativeDet.put("Taylor, Charles H.", "R-NC-11");
		representativeDet.put("Taylor, Gene", "D-MS-4");
		representativeDet.put("Terry, Lee", "R-NE-2");
		representativeDet.put("Thomas, William M.", "R-CA-22");
		representativeDet.put("Tiahrt, Todd", "R-KS-4");
		representativeDet.put("Tiberi, Patrick J.", "R-OH-12");
		representativeDet.put("Tierney, John F.", "D-MA-6");
		representativeDet.put("Towns, Edolphus", "D-NY-10");
		representativeDet.put("Turner, Michael R.", "R-OH-3");
		representativeDet.put("Udall, Mark", "D-CO-2");
		representativeDet.put("Udall, Tom", "D-NM-3");
		representativeDet.put("Velazquez, Nydia M.", "D-NY-12");
		representativeDet.put("Visclosky, Peter J.", "D-IN-1");
		representativeDet.put("Walsh, James T.", "R-NY-25");
		representativeDet.put("Wamp, Zach", "R-TN-3");
		representativeDet.put("Watson, Diane E.", "D-CA-33");
		representativeDet.put("Watt, Melvin L.", "D-NC-12");
		representativeDet.put("Waxman, Henry A.", "D-CA-30");
		representativeDet.put("Weiner, Anthony D.", "D-NY-9");
		representativeDet.put("Weldon, Curt", "R-PA-7");
		representativeDet.put("Weldon, Dave", "R-FL-15");
		representativeDet.put("Weller, Jerry", "R-IL-11");
		representativeDet.put("Wexler, Robert", "D-FL-19");
		representativeDet.put("Wicker, Roger F.", "R-MS-1");
		representativeDet.put("Wilson, Heather", "R-NM-1");
		representativeDet.put("Wolf, Frank R.", "R-VA-10");
		representativeDet.put("Woolsey, Lynn C.", "D-CA-6");
		representativeDet.put("Wu, David", "D-OR-1");
		representativeDet.put("Wynn, Albert Russell", "D-MD-4");
		representativeDet.put("Young, C. W. Bill", "R-FL-10");

		// from 110
		representativeDet.put("Altmire, Jason", "D-PA-4");
		representativeDet.put("Arcuri, Michael A.", "D-NY-24");
		representativeDet.put("Bachmann, Michele", "R-MN-6");
		representativeDet.put("Bilbray, Brian P.", "R-CA-50");
		representativeDet.put("Bono Mack, Mary", "R-CA-45");
		representativeDet.put("Boyda, Nancy E.", "D-KS-2");
		representativeDet.put("Braley, Bruce L.", "D-IA-1");
		representativeDet.put("Broun, Paul C.", "R-GA-10");
		representativeDet.put("Carney, Christopher P.", "D-PA-10");
		representativeDet.put("Carson, Andre", "D-IN-7");
		representativeDet.put("Cazayoux, Donald J., Jr.", "D-LA-6");
		representativeDet.put("Childers, Travis", "D-MS-1");
		representativeDet.put("Davis, David", "R-TN-1");
		representativeDet.put("Donnelly, Joe", "D-IN-2");
		representativeDet.put("Ellsworth, Brad", "D-IN-8");
		representativeDet.put("Fallin, Mary", "R-OK-5");
		representativeDet.put("Giffords, Gabrielle", "D-AZ-8");
		representativeDet.put("Gillibrand, Kirsten E.", "D-NY-20");
		representativeDet.put("Hall, John J.", "D-NY-19");
		representativeDet.put("Hare, Phil", "D-IL-17");
		representativeDet.put("Heller, Dean", "R-NV-2");
		representativeDet.put("Herseth Sandlin, Stephanie", "D-SD");
		representativeDet.put("Hill, Baron P.", "D-IN-9");
		representativeDet.put("Hirono, Mazie K.", "D-HI-2");
		representativeDet.put("Hodes, Paul W.", "D-NH-2");
		representativeDet.put("Johnson, Henry C. (Hank), Jr.", "D-GA-4");
		representativeDet.put("Kagen, Steve", "D-WI-8");
		representativeDet.put("Klein, Ron", "D-FL-22");
		representativeDet.put("Lampson, Nick", "D-TX-22");
		representativeDet.put("LaTourette, Steven C.", "R-OH-14");
		representativeDet.put("Mahoney, Tim", "D-FL-16");
		representativeDet.put("Mitchell, Harry E.", "D-AZ-5");
		representativeDet.put("Murphy, Christopher S.", "D-CT-5");
		representativeDet.put("Murphy, Patrick J.", "D-PA-8");
		representativeDet.put("Myrick, Sue Wilkins", "R-NC-9");
		representativeDet.put("Norwood, Charles W.", "R-GA-10");
		representativeDet.put("Richardson, Laura", "D-CA-37");
		representativeDet.put("Rodriguez, Ciro D.", "D-TX-23");
		representativeDet.put("Sali, Bill", "R-ID-1");
		representativeDet.put("Scott, Robert C. (Bobby)", "D-VA-3");
		representativeDet.put("Sestak, Joe", "D-PA-7");
		representativeDet.put("Shea-Porter, Carol", "D-NH-1");
		representativeDet.put("Shuler, Heath", "D-NC-11");
		representativeDet.put("Space, Zachary T.", "D-OH-18");
		representativeDet.put("Sutton, Betty", "D-OH-13");
		representativeDet.put("Walberg, Timothy", "R-MI-7");
		representativeDet.put("Wilson, Charles A.", "D-OH-6");
		
		//from 111
		representativeDet.put("Adler, John H.", "D-NJ-3");
		representativeDet.put("Austria, Steve", "R-OH-7");
		representativeDet.put("Boccieri, John A.", "D-OH-16");
		representativeDet.put("Bright, Bobby", "D-AL-2");
		representativeDet.put("Cao, Ahn (Joseph)", "R-LA-2");
		representativeDet.put("Cassidy, Bill", "R-LA-6");
		representativeDet.put("Connolly, Gerald E. (Gerry)", "D-VA-11");
		representativeDet.put("Critz, Mark S.", "D-PA-12");
		representativeDet.put("Dahlkemper, Kathleen A.", "D-PA-3");
		representativeDet.put("Delahunt, Bill", "D-MA-10");
		representativeDet.put("Deutch, Theodore E.", "D-FL-19");
		representativeDet.put("Djou, Charles K.", "R-HI-1");
		representativeDet.put("Driehaus, Steve", "D-OH-1");
		representativeDet.put("Griffith, Parker", "R-AL-5");
		representativeDet.put("Guthrie, Brett", "R-KY-2");
		representativeDet.put("Halvorson, Deborah L.", "D-IL-11");
		representativeDet.put("Heinrich, Martin", "D-NM-1");
		representativeDet.put("Himes, James A.", "D-CT-4");
		representativeDet.put("Kilroy, Mary Jo", "D-OH-15");
		representativeDet.put("Kissell, Larry", "D-NC-8");
		representativeDet.put("Kosmas, Suzanne M.", "D-FL-24");
		representativeDet.put("Kratovil, Frank Jr.", "D-MD-1");
		representativeDet.put("Lee, Christopher J.", "R-NY-26");
		representativeDet.put("Lujan, Ben Ray", "D-NM-3");
		representativeDet.put("Maffei, Daniel B.", "D-NY-25");
		representativeDet.put("Markey, Betsy", "D-CO-4");
		representativeDet.put("Massa, Eric J. J.", "D-NY-29");
		representativeDet.put("McMahon, Michael E.", "D-NY-13");
		representativeDet.put("Minnick, Walter", "D-ID-1");
		representativeDet.put("Murphy, Scott", "D-NY-20");
		representativeDet.put("Nye, Glenn C.", "D-VA-2");
		representativeDet.put("Owens, William L.", "D-NY-23");
		representativeDet.put("Perriello, Thomas S.P.", "D-VA-5");
		representativeDet.put("Peters, Gary C.", "D-MI-9");
		representativeDet.put("Pierluisi, Pedro R.", "D-PR");
		representativeDet.put("Rehberg, Denny", "R-MT");
		representativeDet.put("Roe, David P.", "R-TN-1");
		representativeDet.put("Rooney, Thomas J.", "R-FL-16");
		representativeDet.put("Sablan, Gregorio Kilili Camacho", "D-MP");
		representativeDet.put("Schauer, Mark H.", "D-MI-7");
		representativeDet.put("Schock, Aaron", "R-IL-18");
		representativeDet.put("Stutzman, Marlin A.", "R-IN-3");
		representativeDet.put("Teague, Harry", "D-NM-2");
		representativeDet.put("Thompson, Glenn", "R-PA-5");
		
		//from 112
		representativeDet.put("Adams, Sandy", "R-FL-24");
		representativeDet.put("Berg, Rick", "R-ND");
		representativeDet.put("Buerkle, Ann Marie", "R-NY-25");
		representativeDet.put("Canseco, Francisco R.", "R-TX-23");
		representativeDet.put("Carney, John C., Jr.", "D-DE");
		representativeDet.put("Cicilline, David N.", "D-RI-1");
		representativeDet.put("Clarke, Hansen", "D-MI-13");
		representativeDet.put("Cravaack, Chip", "R-MN-8");
		representativeDet.put("Crawford, Eric A. (Rick)", "R-AR-1");
		representativeDet.put("Dold, Robert J.", "R-IL-10");
		representativeDet.put("Ellmers, Renee L.", "R-NC-2");
		representativeDet.put("Fincher, Stephen Lee", "R-TN-8");
		representativeDet.put("Fleischmann, Charles J. (Chuck)", "R-TN-3");
		representativeDet.put("Gardner, Cory", "R-CO-4");
		representativeDet.put("Gibson, Christopher P.", "R-NY-20");
		representativeDet.put("Griffin, Tim", "R-AR-2");
		representativeDet.put("Griffith, H. Morgan", "R-VA-9");
		representativeDet.put("Grimm, Michael G.", "R-NY-13");
		representativeDet.put("Guinta, Frank C.", "R-NH-1");
		representativeDet.put("Hanabusa, Colleen W.", "D-HI-1");
		representativeDet.put("Hanna, Richard L.", "R-NY-24");
		representativeDet.put("Hayworth, Nan A. S.", "R-NY-19");
		representativeDet.put("Heck, Joseph J.", "R-NV-3");
		representativeDet.put("Keating, William R.", "D-MA-10");
		representativeDet.put("Landry, Jeffrey M.", "R-LA-3");
		representativeDet.put("Lankford, James", "R-OK-5");
		representativeDet.put("Marino, Thomas", "R-PA-10");
		representativeDet.put("McKinley, David B.", "R-WV-1");
		representativeDet.put("Meehan, Patrick", "R-PA-7");
		representativeDet.put("Noem, Kristi L.", "R-SD");
		representativeDet.put("Nunnelee, Alan", "R-MS-1");
		representativeDet.put("Palazzo, Steven M.", "R-MS-4");
		representativeDet.put("Payne, Donald, Jr.", "D-NJ-10");
		representativeDet.put("Quayle, Benjamin", "R-AZ-3");
		representativeDet.put("Renacci, James B.", "R-OH-16");
		representativeDet.put("Ribble, Reid J.", "R-WI-8");
		representativeDet.put("Richmond, Cedric L.", "D-LA-2");
		representativeDet.put("Rigell, E. Scott", "R-VA-2");
		representativeDet.put("Rivera, David", "R-FL-25");
		representativeDet.put("Runyan, Jon", "R-NJ-3");
		representativeDet.put("Schilling, Robert T.", "R-IL-17");
		representativeDet.put("Scott, Tim", "R-SC-1");
		representativeDet.put("Southerland, Steve", "R-FL-2");
		representativeDet.put("Tonko, Paul", "D-NY-21");
		representativeDet.put("Walsh, Joe", "R-IL-8");
		representativeDet.put("West, Allen B.", "R-FL-22");
		representativeDet.put("Woodall, Rob", "R-GA-7");
		representativeDet.put("Young, Todd C.", "R-IN-9");
		
		//from 113
		representativeDet.put("Adams, Alma S.", "D-NC-12");
		representativeDet.put("Amodei, Mark E.", "R-NV-2");
		representativeDet.put("Barber, Ron", "D-AZ-2");
		representativeDet.put("Bentivolio, Kerry L.", "R-MI-11");
		representativeDet.put("Byrne, Bradley", "R-AL-1");
		representativeDet.put("Cardenas, Tony", "D-CA-29");
		representativeDet.put("Cartwright, Matt", "D-PA-17");
		representativeDet.put("Clark, Katherine M.", "D-MA-5");
		representativeDet.put("Clawson, Curt", "R-FL-19");
		representativeDet.put("Cotton, Tom", "R-AR-4");
		representativeDet.put("Daines, Steve", "R-MT");
		representativeDet.put("Delaney, John K.", "D-MD-6");
		representativeDet.put("DelBene, Suzan K.", "D-WA-1");
		representativeDet.put("Enyart, William L.", "D-IL-12");
		representativeDet.put("Esty, Elizabeth H.", "D-CT-5");
		representativeDet.put("Gallego, Pete P.", "D-TX-23");
		representativeDet.put("Garcia, Joe", "D-FL-26");
		representativeDet.put("Holt, Rush", "D-NJ-12");
		representativeDet.put("Horsford, Steven A.", "D-NV-4");
		representativeDet.put("Jeffries, Hakeem S.", "D-NY-8");
		representativeDet.put("Joyce, David P.", "R-OH-14");
		representativeDet.put("Kelly, Robin L.", "D-IL-2");
		representativeDet.put("Kennedy, Joseph P., III", "D-MA-4");
		representativeDet.put("Kildee, Daniel T.", "D-MI-5");
		representativeDet.put("Kuster, Ann M.", "D-NH-2");
		representativeDet.put("Lowenthal, Alan S.", "D-CA-47");
		representativeDet.put("McAllister, Vance M.", "R-LA-5");
		representativeDet.put("Negrete McLeod, Gloria", "D-CA-35");
		representativeDet.put("Nolan, Richard M.", "D-MN-8");
		representativeDet.put("Nugent, Richard B.", "R-FL-11");
		representativeDet.put("Payne, Donald M., Jr.", "D-NJ-10");
		representativeDet.put("Peters, Scott H.", "D-CA-52");
		representativeDet.put("Radel, Trey", "R-FL-19");
		representativeDet.put("Rogers, Mike J.", "R-MI-8");
		representativeDet.put("Ross, Dennis A.", "R-FL-15");
		representativeDet.put("Rothfus, Keith J.", "R-PA-12");
		representativeDet.put("Schneider, Bradley S.", "D-IL-10");
		representativeDet.put("Southerland, Steve II", "R-FL-2");
		representativeDet.put("Stockman, Steve", "R-TX-36");
		representativeDet.put("Tipton, Scott R.", "R-CO-3");
		representativeDet.put("Valadao, David G.", "R-CA-21");
		representativeDet.put("Veasey, Marc A.", "D-TX-33");
		representativeDet.put("Weber, Randy K., Sr.", "R-TX-14");
		representativeDet.put("Wenstrup, Brad R.", "R-OH-2");
		representativeDet.put("Wilson, Frederica S.", "D-FL-24");
		representativeDet.put("Yoho, Ted S.", "R-FL-3");
		
		//from 114
		representativeDet.put("Abraham, Ralph Lee", "R-LA-5");
		representativeDet.put("Allen, Rick W.", "R-GA-12");
		representativeDet.put("Beyer, Donald S., Jr.", "D-VA-8");
		representativeDet.put("Boyle, Brendan F.", "D-PA-13");
		representativeDet.put("Carter, Earl L. Buddy", "R-GA-1");
		representativeDet.put("Connolly, Gerald E.", "D-VA-11");
		representativeDet.put("Costello, Ryan A.", "R-PA-6");
		representativeDet.put("Crawford, Eric A. Rick", "R-AR-1");
		representativeDet.put("Donovan, Daniel M., Jr.", "R-NY-11");
		representativeDet.put("Fleischmann, Charles J. Chuck", "R-TN-3");
		representativeDet.put("Hice, Jody B.", "R-GA-10");
		representativeDet.put("Hill, J. French", "R-AR-2");
		representativeDet.put("Jenkins, Evan H.", "R-WV-3");
		representativeDet.put("Johnson, Henry C. Hank, Jr.", "D-GA-4");
		representativeDet.put("Knight, Stephen", "R-CA-25");
		representativeDet.put("Lawrence, Brenda L.", "D-MI-14");
		representativeDet.put("Love, Mia B.", "R-UT-4");
		representativeDet.put("MacArthur, Thomas", "R-NJ-3");
		representativeDet.put("Moolenaar, John R.", "R-MI-4");
		representativeDet.put("Mooney, Alexander X.", "R-WV-2");
		representativeDet.put("Palmer, Gary J.", "R-AL-6");
		representativeDet.put("Plaskett, Stacey E.", "D-VI");
		representativeDet.put("Radewagen, Aumua Amata Coleman", "R-AS");
		representativeDet.put("Rice, Kathleen M.", "D-NY-4");
		representativeDet.put("Scott, Robert C. Bobby", "D-VA-3");
		representativeDet.put("Stefanik, Elise M.", "R-NY-21");
		representativeDet.put("Torres, Norma J.", "D-CA-35");
		representativeDet.put("Trott, David A.", "R-MI-11");
		representativeDet.put("Zeldin, Lee M.", "R-NY-1");
		representativeDet.put("Zinke, Ryan K.", "R-MT");
		
		//populated from google data
		representativeDet.put("Acevedo-Vila, Anibal", "D-PR");
		representativeDet.put("Ballance, Frank W., Jr.", "D-NC-1");
		representativeDet.put("Ballenger, Cass", "R-NC-10");
		representativeDet.put("Bell, Chris", "D-TX-25");
		representativeDet.put("Bereuter, Doug", "R-NE-1");
		representativeDet.put("Boehlert, Sherwood L.", "R-NY-24");
		representativeDet.put("Burns, Max", "R-GA-12");
		representativeDet.put("Burr, Richard", "R-NC-5");
		representativeDet.put("Carson, Brad", "D-OK-2");
		representativeDet.put("Collins, Mac", "R-GA-8");
		representativeDet.put("Combest, Larry", "R-TX-19");
		representativeDet.put("Crane, Philip M.", "R-IL-8");
		representativeDet.put("DeMint, Jim", "R-SC-4");
		representativeDet.put("Deutsch, Peter", "D-FL-20");
		representativeDet.put("Dooley, Calvin M.", "D-CA-20");
		representativeDet.put("Dunn, Jennifer", "R-WA-8");
		representativeDet.put("Fletcher, Ernie", "R-KY-6");
		representativeDet.put("Frost, Martin", "D-TX-24");
		representativeDet.put("Gephardt, Richard A.", "D-MO-3");
		representativeDet.put("Goss, Porter J.", "R-FL-14");
		representativeDet.put("Greenwood, James C.", "R-PA-8");
		representativeDet.put("Hoeffel, Joseph M.", "D-PA-13");
		representativeDet.put("Houghton, Amo", "R-NY-29");
		representativeDet.put("Isakson, Johnny", "R-GA-6");
		representativeDet.put("Janklow, William J.", "R-SD");
		representativeDet.put("John, Christopher", "D-LA-7");
		representativeDet.put("Kleczka, Gerald D.", "D-WI-4");
		representativeDet.put("Lipinski, William O.", "D-IL-3");
		representativeDet.put("Lucas, Ken", "D-KY-4");
		representativeDet.put("Majette, Denise L.", "D-GA-4");
		representativeDet.put("McCarthy, Karen", "D-MO-5");
		representativeDet.put("McInnis, Scott", "R-CO-3");
		representativeDet.put("Nethercutt, George R., Jr.", "R-WA-5");
		representativeDet.put("Northup, Anne", "R-KY-3");
		representativeDet.put("Ose, Doug", "R-CA-3");
		representativeDet.put("Quinn, Jack", "R-NY-27");
		representativeDet.put("Radanovich, George P.", "R-CA-19");
		representativeDet.put("Rothman, Steve R.", "D-NJ-9");
		representativeDet.put("Sandlin, Max", "D-TX-1");
		representativeDet.put("Schrock, Edward L.", "R-VA-2");
		representativeDet.put("Smith, Nick", "R-MI-7");
		representativeDet.put("Stenholm, Charles W.", "D-TX-17");
		representativeDet.put("Tauzin, W. J. (Billy)", "D/R-LA-3");
		representativeDet.put("Toomey, Patrick J.", "R-PA-15");
		representativeDet.put("Turner, Jim", "D-TX-2");
		representativeDet.put("Vitter, David", "R-LA-1");
		
		representativeDet.put("Armey, Richard K.", "R-TX-26");
		representativeDet.put("Baldacci, John Elias", "D-ME-2");
		representativeDet.put("Barcia, James A.", "D-MI-5");
		representativeDet.put("Barr, Bob", "L-GA-7"); //libertarian
		representativeDet.put("Barrett, Thomas M.", "D-WI-5");
		representativeDet.put("Bentsen, Ken", "D-TX-25");
		representativeDet.put("Bishop, Sanford D. Jr.", "D-GA-2");
		representativeDet.put("Blagojevich, Rod R.", "D-IL-5");
		representativeDet.put("Bonior, David E.", "D-MI-10");
		representativeDet.put("Borski, Robert A.", "D-PA-3");
		representativeDet.put("Bryant, Ed", "R-TN-7");
		representativeDet.put("Buyer, Steve E.", "R-IN-5");
		representativeDet.put("Callahan, Sonny", "R-AL-1");
		representativeDet.put("Chambliss, Saxby", "R-GA-8");
		representativeDet.put("Clayton, Eva M.", "D-NC-1");
		representativeDet.put("Clement, Bob", "D-TN-5");
		representativeDet.put("Condit, Gary A.", "D-CA-18");
		representativeDet.put("Cooksey, John", "R-LA-5");
		representativeDet.put("Coyne, William J.", "D-PA-14");
		representativeDet.put("Cramer, Robert E. (Bud) Jr.", "D-AL-5");
		representativeDet.put("Ehrlich, Robert L., Jr.", "R-MD-2");
		representativeDet.put("Fletcher, Ernest L.", "R-KY-6");
		representativeDet.put("Ford, Harold, Jr.", "D-TN-9");
		representativeDet.put("Ganske, Greg", "R-IA-4");
		representativeDet.put("Gekas, George W.", "R-PA-17");
		representativeDet.put("Gilman, Benjamin A.", "R-NY-20");
		representativeDet.put("Graham, Lindsey O.", "R-SC-3");
		representativeDet.put("Grucci, Felix J., Jr.", "R-NY-1");
		representativeDet.put("Hall, Tony P.", "D-OH-3");
		representativeDet.put("Hansen, James V.", "R-UT-1");
		representativeDet.put("Hilleary, Van", "R-TN-4");
		representativeDet.put("Hilliard, Earl F.", "D-AL-7");
		representativeDet.put("Horn, Stephen", "R-CA-38");
		representativeDet.put("Hutchinson, Asa", "R-AR-3");
		representativeDet.put("Kerns, Brian D.", "R-IN-7");
		representativeDet.put("LaFalce, John J.", "D-NY-29");
		representativeDet.put("Largent, Steve", "R-OK-1");
		representativeDet.put("Luther, Bill", "D-MN-6");
		representativeDet.put("Maloney, James H.", "D-CT-5");
		representativeDet.put("Mascara, Frank", "D-PA-20");
		representativeDet.put("McKinney, Cynthia A.", "D/G-GA-4");
		representativeDet.put("Meek, Carrie P.", "D-FL-17");
		representativeDet.put("Miller, Dan", "R-FL-13");
		representativeDet.put("Mink, Patsy T.", "D-HI-2");
		representativeDet.put("Moakley, John Joseph", "D-MA-9");
		representativeDet.put("Morella, Constance A.", "R-MD-8");
		representativeDet.put("Phelps, David D.", "D-IL-19");
		representativeDet.put("Pickering, Charles (Chip)", "R-MS-3");
		representativeDet.put("Riley, Bob", "R-AL-3");
		representativeDet.put("Rivers, Lynn N.", "D-MI-13");
		representativeDet.put("Rodriguez, Ciro", "D-TX-28");
		representativeDet.put("Roemer, Tim", "D-IN-3");
		representativeDet.put("Roukema, Marge", "R-NJ-5");
		representativeDet.put("Sawyer, Tom", "D-OH-14");
		representativeDet.put("Scarborough, Joe", "R-FL-1");
		representativeDet.put("Schaffer, Bob", "R-CO-4");
		representativeDet.put("Shows, Ronnie", "D-MS-4");
		representativeDet.put("Shuster, Bud", "R-PA-9");
		representativeDet.put("Sisisky, Norman", "D-VA-4");
		representativeDet.put("Skeen, Joe", "R-NM-2");
		representativeDet.put("Spence, Floyd", "R-SC-2");
		representativeDet.put("Stump, Bob", "D/R-AZ-3");
		representativeDet.put("Sununu, John E.", "R-NH-1");
		representativeDet.put("Taylor, G.", "L-MS-5");
		representativeDet.put("Thomas, William M. (Bill)", "R-CA-21");
		representativeDet.put("Thornberry, William (Mac)", "R-TX-13");
		representativeDet.put("Thune, John R.", "R-SD");
		representativeDet.put("Thurman, Karen L.", "D-FL-5");
		representativeDet.put("Traficant, James A., Jr.", "D/I-OH-17");
		representativeDet.put("Underwood, Robert A.", "D-GU");
		representativeDet.put("Watkins, Wes", "D/R-OK-3");
		representativeDet.put("Watts, J. C., Jr.", "R-OK-4");
		
		//106
		representativeDet.put("Archer, Bill", "R-TX-7");
		representativeDet.put("Barrett, Bill", "D-NE-3");
		representativeDet.put("Bateman, Herbert H.", "R-VA-1");
		representativeDet.put("Bliley, Tom", "D/R-VA-7");
		representativeDet.put("Brown, George E., Jr.", "D-CA-42");
		representativeDet.put("Buyer, Stephen E.", "R-IN-5");
		representativeDet.put("Campbell, Tom", "R-CA-15");
		representativeDet.put("Canady, Charles T.", "R-FL-12");
		representativeDet.put("Chenoweth-Hage, Helen", "R-ID-1");
		representativeDet.put("Christensen, Donna MC", "D-VI");
		representativeDet.put("Clay, William (Bill)", "D-MO-1");
		representativeDet.put("Coburn, Tom", "R-OK-2");
		representativeDet.put("Cook, Merrill", "R-UT-2");
		representativeDet.put("Cunningham, Randy \"Duke\"", "R-CA-51");
		representativeDet.put("Danner, Pat", "D-MO-6");
		representativeDet.put("Davis, Thomas M.", "R-VA-11");
		representativeDet.put("Dickey, Jay", "R-AR-4");
		representativeDet.put("Dixon, Julian C.", "D-CA-32");
		representativeDet.put("Ewing, Thomas W.", "R-IL-15");
		representativeDet.put("Forbes, Michael P.", "D/RNY-1");
		representativeDet.put("Fowler, Tillie K.", "R-FL-4");
		representativeDet.put("Franks, Bob", "R-NJ-7");
		representativeDet.put("Gejdenson, Sam", "D-CT-2");
		representativeDet.put("Gingrich, Newt", "D-GA-6");
		representativeDet.put("Goodling, William F.", "R-PA-19");
		representativeDet.put("Hill, Rick", "R-MT-At Large");
		representativeDet.put("Kasich, John R.", "R-OH-12");
		representativeDet.put("Klink, Ron", "D-PA-4");
		representativeDet.put("Kuykendall, Steven T.", "R-CA-36");
		representativeDet.put("Lazio, Rick", "R-NY-2");
		representativeDet.put("Livingston, Bob", "R-LA-1");
		representativeDet.put("McCollum, Bill", "R-FL-8");
		representativeDet.put("McIntosh, David M.", "R-IN-2");
		representativeDet.put("McKeon, Howard P. \"Buck\"", "R-CA-25");
		representativeDet.put("Martinez, Matthew G.", "R-CA-31");
		representativeDet.put("Metcalf, Jack", "R-WA-2");
		representativeDet.put("Minge, David", "D-MN-2");
		representativeDet.put("Packard, Ron", "R-CA-48");
		representativeDet.put("Pease, Edward A.", "R-IN-7");
		representativeDet.put("Pickering, Charles W. \"Chip\"", "D/R-MS-3");
		representativeDet.put("Pickett, Owen B.", "D-VA-2");
		representativeDet.put("Porter, John Edward", "R-IL-10");
		representativeDet.put("Rogan, James E.", "R-CA-27");
		representativeDet.put("Romero-Barcelo, Carlos A.", "D-PR");
		representativeDet.put("Sanford, Marshall \"Mark\"", "R-SC-1");
		representativeDet.put("Sawyer, Thomas C.", "D-OH-14");
		representativeDet.put("Stabenow, Debbie", "D-MI-8");
		representativeDet.put("Talent, James M.", "R-MO-2");
		representativeDet.put("Vento, Bruce F.", "D-MN-4");
		representativeDet.put("Weygand, Robert A.", "D-RI-2");
		representativeDet.put("Wise, Robert E., Jr.", "D-WV-2");
		
		//105
		representativeDet.put("Baesler, Scotty", "D-KY-6");
		representativeDet.put("Bono, Sonny", "R-CA-44");
		representativeDet.put("Bunning, Jim", "R-KY-4");
		representativeDet.put("Capps, Walter H.", "D-CA-22");
		representativeDet.put("Chenoweth, Helen", "R-ID-1");
		representativeDet.put("Christensen, Jon", "R-NE-2");
		representativeDet.put("Christian-Green, Donna", "D-VI");
		representativeDet.put("Clay, William (Bill)", "D-MO-1");
		representativeDet.put("Coburn, Thomas A.", "R-OK-2");
		representativeDet.put("Cramer, Robert E. Bud, Jr.", "D-AL-5");
		representativeDet.put("Crapo, Michael D.", "R-ID-2");
		representativeDet.put("Dellums, Ronald V.", "D-CA-9");
		representativeDet.put("Diaz Balart, Lincoln", "R-FL-21");
		representativeDet.put("Ensign, John E.", "R-NV-1");
		representativeDet.put("Fawell, Harris W.", "R-IL-13");
		representativeDet.put("Fazio, Vic", "D-CA-3");
		representativeDet.put("Flake, Floyd H.", "D-NY-6");
		representativeDet.put("Foglietta, Thomas M.", "D-PA-1");
		representativeDet.put("Fox, Jon D.", "R-PA-13");
		representativeDet.put("Furse, Elizabeth", "D-OR-1");
		representativeDet.put("Gekas, George, W.", "R-PA-17");
		representativeDet.put("Gonzalez, Henry B.", "D-TX-20");
		representativeDet.put("Goodlatte, Robert W. (Bob)", "R-VA-6");
		representativeDet.put("Hamilton, Lee H.", "D-IN-9");
		representativeDet.put("Hefner, W. G. (Bill)", "D-NC-8");
		representativeDet.put("Jackson, Sheila Lee", "D-TX-18");
		representativeDet.put("Jenkins, William L. (Bill)", "R-TN-1");
		representativeDet.put("Johnson, Jay W.", "D-WI-8");
		representativeDet.put("Kennedy, Joseph P., II", "D-MA-8");
		representativeDet.put("Kennelly, Barbara B.", "D-CT-1");
		representativeDet.put("Kim, Jay", "R-CA-41");
		representativeDet.put("Klug, Scott L.", "R-WI-2");
		representativeDet.put("LaTourette, Steven", "R-OH-19");
		representativeDet.put("Maloney, James", "D-CT-5");
		representativeDet.put("Manton, Thomas J.", "D-NY-7");
		representativeDet.put("McDade, Joseph M.", "R-PA-10");
		representativeDet.put("McHale, Paul", "D-PA-15");
		representativeDet.put("McHugh John M.", "R-NY-24");
		representativeDet.put("Meek, Carrie", "D-FL-17");
		representativeDet.put("Meeks, Gregory", "D-NY-6");
		representativeDet.put("Millender-McDonald, Juanita M.", "D-CA-37");
		representativeDet.put("Molinari, Susan", "R-NY-13");
		representativeDet.put("Neumann, Mark W.", "R-WI-1");
		representativeDet.put("Pappas, Michael", "R-NJ-12");
		representativeDet.put("Parker, Mike", "D/R-MS-4");
		representativeDet.put("Paxon, Bill", "R-NY-27");
		representativeDet.put("Pickering, Charles W. Chip", "R-MS-3");
		representativeDet.put("Poshard, Glenn", "D-IL-19");
		representativeDet.put("Redmond, Bill", "R-NM-3");
		representativeDet.put("Riggs, Frank", "R-CA-1");
		representativeDet.put("Rivers, Lynn", "D-MI-13");
		representativeDet.put("Romero-Barcelo, Carlos", "D-PR");
		representativeDet.put("Royce, Edward", "R-CA-39");
		representativeDet.put("Schaefer, Dan", "R-CO-6");
		representativeDet.put("Schiff, Steven H.", "R-NM-1");
		representativeDet.put("Schumer, Charles E.", "D-NY-9");
		representativeDet.put("Serrano,Jose E.", "D-NY-16");
		representativeDet.put("Shadegg, John", "R-AZ-4");
		representativeDet.put("Shimkus, John M.", "R-IL-20");
		representativeDet.put("Sisisky, Norman,", "D-VA-4");
		representativeDet.put("Skaggs, David E.", "D-CO-2");
		representativeDet.put("Smith, Linda", "R-WA-3");
		representativeDet.put("Smith, Robert", "R/I-OR-2");
		representativeDet.put("Snowbarger, Vince", "R-KS-3");
		representativeDet.put("Solomon, Gerald B. H.", "R-NY-22");
		representativeDet.put("Spence, Floyd,", "R-SC-2");
		representativeDet.put("Stokes, Louis", "D-OH-11");
		representativeDet.put("Tauzin, W.J. Billy", "D/R-LA-3");
		representativeDet.put("Thornberry, William M. Mac", "R-TX-13");
		representativeDet.put("Tierney, John", "D-MA-6");
		representativeDet.put("Torres, Esteban Edward", "D-CA-34");
		representativeDet.put("Watts J.C., Jr.", "R-OK-4");
		representativeDet.put("White, Rick", "R-WA-1");
		representativeDet.put("Yates, Sidney R.,", "F-IL-9");
	
		//104
		representativeDet.put("Allard, Wayne", "R-CO-4");
		representativeDet.put("Armey, Dick", "R-TX-26");
		representativeDet.put("Baker, Bill", "R-CA-10");
		representativeDet.put("Beilenson, Anthony C.", "D-CA-24");
		representativeDet.put("Bevill, Tom", "D-AL-4");
		representativeDet.put("Bliley, Thomas J., Jr.", "R-VA-7");
		representativeDet.put("Blute, Peter I.", "R-MA-3");
		representativeDet.put("Brewster, Bill K.", "D-OK-3");
		representativeDet.put("Browder, Glen", "D-AL-3");
		representativeDet.put("Brownback, Sam", "R-KS-2");
		representativeDet.put("Bryant, John W.", "D-TX-5");
		representativeDet.put("Bunn, Jim", "R-OR-5");
		representativeDet.put("Burr, Richard M.", "R-NC-5");
		representativeDet.put("Chapman, Jim", "D-TX-1");
		representativeDet.put("Chrysler, Dick", "R-MI-8");
		representativeDet.put("Clinger, William F., Jr.", "R-PA-5");
		representativeDet.put("Coburn, Tom A.", "R-OK-2");
		representativeDet.put("Coleman, Ronald D.", "D-TX-16");
		representativeDet.put("Collins, Barbara Rose", "D-MI-15");
		representativeDet.put("Collins, Cardiss", "D-IL-7");
		representativeDet.put("Cooley, Wes", "R-OR-2");
		representativeDet.put("Cremeans, Frank A.", "R-OH-6");
		representativeDet.put("de la Garza, E", "D-TX-150");
		representativeDet.put("Dornan, Robert K.", "R-CA-46");
		representativeDet.put("Durbin, Richard J.", "D-IL-20");
		representativeDet.put("Ehrlich, Robert, Jr.", "R-MD-2");
		representativeDet.put("Emerson, Bill", "R-MO-8");
		representativeDet.put("Fields, Cleo", "D-LA-4");
		representativeDet.put("Fields, Jack", "R-TX-8");
		representativeDet.put("Flanagan, Michael Patrick", "IL-5");
		representativeDet.put("Franks, Gary A.", "CT-5");
		representativeDet.put("Frazer, Victor O.", "VI");
		representativeDet.put("Frisa, Dan", "NY-4");
		representativeDet.put("Funderburk, David", "NC-21");
		representativeDet.put("Geren, Pete", "TX-12");
		representativeDet.put("Gibbons, Sam", "FL-11");
		representativeDet.put("Graham, Lindsey", "R-SC-3");
		representativeDet.put("Gunderson, Steve", "R-WI-3");
		representativeDet.put("Hayes, James A.", "D/R-LA-7");
		representativeDet.put("Heineman, Frederick K. (Fred)", "R-NC-4");
		representativeDet.put("Hoke, Martin R.", "R-OH-10");
		representativeDet.put("Horn, Steve", "R-CA-38");
		representativeDet.put("Hutchinson, Tim", "R-AR-3");
		representativeDet.put("Jacobs, Andrew, Jr.", "D-IN-10");
		representativeDet.put("Johnson, Tim", "D-SD-At large");
		representativeDet.put("Johnston, Harry", "D-FL-19");
		representativeDet.put("Kelly, Sue", "R-NY-19");
		representativeDet.put("Laughlin, Greg", "D/R-TX-14");
		representativeDet.put("Lazio, Rick A.", "R/C-NY-2");
		representativeDet.put("Lee, Sheila Jackson,", "D-TX-18");
		representativeDet.put("Lightfoot, Jim", "R-IA-3");
		representativeDet.put("Lincoln, Blanche Lambert", "D-AR-1");
		representativeDet.put("Longley, James B., Jr.", "R-ME-1");
		representativeDet.put("Lucas, Frank,", "R-OK-6");
		representativeDet.put("Manzullo, Donald", "R-IL-16");
		representativeDet.put("Martini, William J.", "R-NJ-8");
		representativeDet.put("Meyers, Jan", "R-KS-3");
		representativeDet.put("Mfume, Kweisi", "D-MD-7");
		representativeDet.put("Millender McDonald, Juanita M.", "D-CA-37");
		representativeDet.put("Mineta, Norman Y.", "D-CA-15");
		representativeDet.put("Montgomery, G. V. (Sonny)", "D-MS-3");
		representativeDet.put("Moorhead, Carlos J.", "R-CA-27");
		representativeDet.put("Myers, John T.", "R-IN-7");
		representativeDet.put("Nethercutt, George, R., Jr.", "R-WA-5");
		representativeDet.put("Neumann, Mark, W.", "R-WI-1");
		representativeDet.put("Orton, Bill", "D-UT-3");
		representativeDet.put("Payne, Lewis F.", "D-VA-5");
		representativeDet.put("Peterson, Douglas (Pete)", "D-FL-2");
		representativeDet.put("Quillen, James H. (Jimmy)", "R-TN-1");
		representativeDet.put("Reed, Jack", "D-RI-2");
		representativeDet.put("Reynolds, Mel", "D-IL-2");
		representativeDet.put("Richardson, Bill", "D-NM-3");
		representativeDet.put("Roberts, Pat", "R-KS-1");
		representativeDet.put("Romero Barcelo, Carlos", "D-PR");		
		representativeDet.put("Rose, Charlie", "D-NC-7");		
		representativeDet.put("Roth, Toby", "R-WI-8");
		representativeDet.put("Roybal Allard, Lucille", "D-CA-33");
		representativeDet.put("Sanford, Marshall (Mark)", "R-SC-1");
		representativeDet.put("Schiff, Steven", "R-NM-1");
		representativeDet.put("Schroeder, Patricia", "D-CO-1");
		representativeDet.put("Seastrand, Andrea H.", "R-CA-22");
		representativeDet.put("Studds, Gerry E.", "D-MA-10");
		representativeDet.put("Tate, Randy", "R-WA-9");
		representativeDet.put("Tejeda, Frank", "D-TX-28");
		representativeDet.put("Thornberry, William M. (Mac)", "R-TX-13");
		representativeDet.put("Thornton, Ray", "D-AR-2");
		representativeDet.put("Torkildsen, Peter G.", "R-MA-6");
		representativeDet.put("Torricelli, Robert G.", "D-NJ-9");
		representativeDet.put("Tucker, Walter R., III", "D-CA-37");
		representativeDet.put("Volkmer, Harold L.", "D-MO-9");
		representativeDet.put("Vucanovich, Barbara F.", "R-NV-2");
		representativeDet.put("Waldholtz, Enid G.", "R-UT-2");
		representativeDet.put("Walker, Robert S.", "R-PA-16");
		representativeDet.put("Ward, Mike", "D-KY-3");
		representativeDet.put("Watts, J. C.", "R-OK-4");
		representativeDet.put("Williams, Pat", "D-MT-At large");
		representativeDet.put("Wilson, Charles", "D-TX-2");
		representativeDet.put("Wyden, Ron", "D-OR-3");
		representativeDet.put("Zeliff, William H., Jr.", "R-NH-1");
		representativeDet.put("Zimmer, Dick", "R-NJ-12");
		
		//103
		representativeDet.put("Andrews, Michael A.", "D-TX-25");
		representativeDet.put("Andrews, Thomas H.", "D-ME-1");
		representativeDet.put("Applegate, Douglas", "D-OH-18");
		representativeDet.put("Aspin, Les", "D-WI-1");
		representativeDet.put("Bacchus, Jim", "D-FL-15");
		representativeDet.put("Barca, Peter", "D-WI-1");
		representativeDet.put("Barlow, Tom", "D-KY-1");
		representativeDet.put("Bentley, Helen Delich", "R-MD-2");
		representativeDet.put("Bilbray, James H.", "D-NV-1");
		representativeDet.put("Bishop, Sanford", "D-GA-2");
		representativeDet.put("Blackwell, Lucien E.", "D-PA-2");
		representativeDet.put("Brooks, Jack B.", "D-TX-9");
		representativeDet.put("Bryant, John", "D-TX-5");
		representativeDet.put("Byrne, Leslie L.", "D-VA-11");
		representativeDet.put("Cantwell, Maria", "D-WA-1");
		representativeDet.put("Carr, Bob", "D-MI-8");
		representativeDet.put("Clayton, Eva", "D-NC-1");
		representativeDet.put("Collins, Barbara-Rose", "D-MI-15");
		representativeDet.put("Cooper, James H.", "D-TN-4");
		representativeDet.put("Coppersmith, Sam", "D-AZ-1");
		representativeDet.put("Cramer, Robert E. (Bud)", "D-AL-5");
		representativeDet.put("Darden, George (Buddy)", "D-GA-7");
		representativeDet.put("Derrick, Butler C.", "D-SC-3");
		representativeDet.put("Edwards, Don", "D-CA-16");
		representativeDet.put("English, Glenn", "D-OK-6");
		representativeDet.put("English, Karan", "D-AZ-6");
		representativeDet.put("Espy, Mike", "D-MS-2");
		representativeDet.put("Ewing, Thomas", "R-IL-15th");
		representativeDet.put("Fingerhut, Eric D.", "D-OH-19");
		representativeDet.put("Fish, Hamilton", "R-NY-19");
		representativeDet.put("Foley, Thomas S.", "D-WA-5");
		representativeDet.put("Ford, William D.", "D-MI-13");
		representativeDet.put("Gallo, Dean A.", "R-NJ-11");
		representativeDet.put("Glickman, Dan", "D-KS-4");
		representativeDet.put("Gradison, Willis, Jr.", "R-OH-2");
		representativeDet.put("Grams, Rod", "R-MN-6");
		representativeDet.put("Grandy, Fred", "R-IA-5");
		representativeDet.put("Hamburg, Dan", "D-CA-1");
		representativeDet.put("Hancock, Mel", "R-MI-7");
		representativeDet.put("Henry, Paul", "R-MI-3");
		representativeDet.put("Hoagland, Peter", "D-NE-2");
		representativeDet.put("Hochbrueckner, George J.", "D-NY-1");
		representativeDet.put("Huffington, Michael", "R-CA-22");
		representativeDet.put("Hughes, William J.", "D-NJ-2");
		representativeDet.put("Hutto, Earl", "D-FL-1");
		representativeDet.put("Inhofe, James M.", "R-OK-1");
		representativeDet.put("Johnson, Don", "R-GA-10");
		representativeDet.put("Klein, Herbert", "D-NJ-8");
		representativeDet.put("Kopetski, Mike", "D-OR-5");
		representativeDet.put("Kreidler, Mike", "D-WA-9");
		representativeDet.put("Kyl, Jon", "R-AZ-4");
		representativeDet.put("Lambert, Blanche M.", "D-AR-1");
		representativeDet.put("Lancaster, H. Martin", "D-NC-3");
		representativeDet.put("LaRocco, Larry", "D-ID-1");
		representativeDet.put("Lehman, Richard H.", "D-CA-19");
		representativeDet.put("Levy, David A.", "D-NY-4");
		representativeDet.put("Lewis, Thomas F.", "R-FL-16");
		representativeDet.put("Lloyd, Marilyn", "D-TN-3");
		representativeDet.put("Long, Jill L.", "D-IN-4");
		representativeDet.put("Machtley, Ronald K.", "R-RI-1");
		representativeDet.put("Mann, David", "D-OH-1");
		representativeDet.put("Margolies Mezvinsky, Marjorie", "D-PA-13");
		representativeDet.put("Mazzoli, Romano L.", "D-KY-3");
		representativeDet.put("McCandless, Alfred A. (Al)", "R-CA-44");
		representativeDet.put("McCloskey, Frank", "D-IN-8");
		representativeDet.put("McCurdy, Dave", "D-OK-4");
		representativeDet.put("McMillan, J. Alex", "R-NC-9");
		representativeDet.put("Michel, Robert H.", "R-IL-18");
		representativeDet.put("Murphy, Austin J.", "D-PA-20");
		representativeDet.put("Natcher, William H.", "D-KY-2");
		representativeDet.put("Neal, Stephen L.", "D-NC-5");
		representativeDet.put("Panetta, Leon", "D-CA-17");
		representativeDet.put("Payne, Lewis F., Jr.", "D-VA-5");
		representativeDet.put("Penny, Timothy J.", "I-MN-1");
		representativeDet.put("Pickle, J. J.", "D-TX-10");
		representativeDet.put("Ravenel, Arthur, Jr.", "R-SC-1");				
		representativeDet.put("Ridge, Thomas J.", "R-PA-21");
		representativeDet.put("Ros Lehtinen, Ileana", "R-FL-18");
		representativeDet.put("Rostenkowski, Dan", "D-IL-5");
		representativeDet.put("Rowland, J. Roy", "D-GA-8");
		representativeDet.put("Sangmeister, George E.", "D-IL-11");
		representativeDet.put("Santorum, Rick", "R-PA-18");
		representativeDet.put("Sarpalius, Bill", "D-TX-13");
		representativeDet.put("Schenk, Lynn", "D-CA-49");
		representativeDet.put("Sharp, Philip R.", "D-IN-2");
		representativeDet.put("Shepherd, Karen", "D-UH-2");
		representativeDet.put("Slattery, Jim", "D-KS-2");
		representativeDet.put("Smith, Neal Edward", "D-IA-4");
		representativeDet.put("Smith, Robert F.", "D-OR-2");
		representativeDet.put("Snowe, Olympia J.", "R-ME-2");
		representativeDet.put("Sundquist, Don", "R-TN-7");
		representativeDet.put("Swett, Dick", "D-NH-2");
		representativeDet.put("Swift, Al", "D-WA-2");
		representativeDet.put("Synar, Mike", "D-OK-2");
		representativeDet.put("Tauzin, W.J. (Billy)", "D-R-LA-3");
		representativeDet.put("Thomas, Craig", "R-WY-At large");
		representativeDet.put("Unsoeld, Jolene", "D-WA-3");
		representativeDet.put("Valentine, Tim", "D-NC-2");
		representativeDet.put("Washington, Craig A.", "D-TX-18");
		representativeDet.put("Watt, Melvin", "D-NC-12");
		representativeDet.put("Wheat, Alan", "D-MO-5");
		representativeDet.put("Whitten, Jamie L.", "D-MS-1");
		
		//102
		representativeDet.put("Alexander, Bill", "D-AR-1");
		representativeDet.put("Allard, A. Wayne", "R-CO-4");
		representativeDet.put("Allen, George", "R-VA-7");
		representativeDet.put("Anderson, Glenn M.", "D-CA-32");
		representativeDet.put("Andrews, Michael", "L-TX-25");
		representativeDet.put("Annunzio, Frank", "D-IL-11");
		representativeDet.put("Anthony, Beryl, Jr.", "D-AR-4");
		representativeDet.put("Atkins, Chester G.", "D-MA-5");
		representativeDet.put("AuCoin, Les", "D-OR-1");
		representativeDet.put("Barnard, Doug, Jr.", "D-GA-10");
		representativeDet.put("Barrett, William E. (Bill)", "R-NE-3");
		representativeDet.put("Bartlett, Steve", "R-TX-3");
		representativeDet.put("Bennett, Charles E.", "D-FL-3");
		representativeDet.put("Blackwell, Lucien", "D-PA-2");
		representativeDet.put("Blaz, Ben G.", "R-GU-R");
		representativeDet.put("Bonior, David", "D-MI-12");
		representativeDet.put("Boxer, Barbara", "D-CA-6");
		representativeDet.put("Broomfield, William S.", "R-MI-18");
		representativeDet.put("Bruce, Terry L.", "D-IL-19");
		representativeDet.put("Bustamante, Albert G.", "D-TX-23");
		representativeDet.put("Byron, Beverly B.", "D-MD-6");
		representativeDet.put("Campbell, Ben Nighthorse", "D/R-CO-3");
		representativeDet.put("Carper, Thomas R.", "D-DE-At large");
		representativeDet.put("Chandler, Rod D.", "R-WA-8");
		representativeDet.put("Coleman, E. Thomas", "R-MO-6");
		representativeDet.put("Colorado, Antonio", "D-PR");		
		representativeDet.put("Conte, Silvio O.", "R-MA-1");
		representativeDet.put("Coughlin, Lawrence", "R-PA-13");
		representativeDet.put("Cox, John W., Jr.", "D-IL-16");
		representativeDet.put("Cramer, William E. (Bud)", "R-AL-5");
		representativeDet.put("Dannemeyer, William E.", "R-CA-39");
		representativeDet.put("Davis, Robert W.", "R-MI-11");
		representativeDet.put("de Lugo, Ron", "D-VI");
		representativeDet.put("Derrick, Butler C., Jr.", "D-SC-3");
		representativeDet.put("Dickinson, William L.", "R-AL-2");
		representativeDet.put("Donnelly, Brian J.", "D-MA-11");
		representativeDet.put("Dooley, Calvin M., Jr.", "D-CA-17");
		representativeDet.put("Dorgan, Byron L.", "D-ND-At large");
		representativeDet.put("Downey, Thomas J.", "D-NY-2");
		representativeDet.put("Dwyer, Bernard J.", "D-NJ-6");
		representativeDet.put("Dymally, Mervyn M.", "D-CA-31");
		representativeDet.put("Early, Joseph D.", "D-MA-3");
		representativeDet.put("Eckart, Dennis E.", "D-OH-11");
		representativeDet.put("Edwards, Mickey", "R-OK-5");
		representativeDet.put("Erdreich, Ben", "D-AL-6");
		representativeDet.put("Fascell, Dante B.", "D-FL-19");
		representativeDet.put("Feighan, Edward F.", "D-OH-19");
		representativeDet.put("Fish, Hamilton, Jr.", "R-NY-19");
		representativeDet.put("Franks, Gary", "R-CT-5");
		representativeDet.put("Fuster, Jamie B.", "D-PR");
		representativeDet.put("Gaydos, Joseph M.", "D-PA-20");
		representativeDet.put("Gradison, Willis D., Jr.", "R-OH-2");		
		representativeDet.put("Gray, William H., III", "D-PA-2");
		representativeDet.put("Green, S. William", "D-NY-15");
		representativeDet.put("Guarini, Frank J.", "D-NJ-14");
		representativeDet.put("Hammerschmidt, John P.", "R-AR-3");
		representativeDet.put("Harris, Claude", "D-AL-7");
		representativeDet.put("Hatcher, Charles", "D-GA-2");
		representativeDet.put("Hayes, Charles A.", "D-IL-1");
		representativeDet.put("Henry, Paul B.", "R-MI-5");
		representativeDet.put("Hertel, Dennis M.", "D-MI-14");
		representativeDet.put("Holloway, Clyde", "R-LA-8");
		representativeDet.put("Hopkins, Larry J.", "R-KY-6");		
		representativeDet.put("Horn, Joan Kelly", "D-MO-2");
		representativeDet.put("Horton, Frank J.", "R-NY-29");
		representativeDet.put("Hubbard, Carroll, Jr.", "D-KY-1");
		representativeDet.put("Huckaby, Thomas J. (Jerry)", "D-LA-5");
		representativeDet.put("Ireland, Andrew P.", "D/R-FL-10");
		representativeDet.put("James, Craig T.", "R-FL-4");
		representativeDet.put("Jenkins, Edgar L.", "D-GA-9");
		representativeDet.put("Jones, Ben", "D-GA-4");
		representativeDet.put("Jontz, Jim", "D-IN-5");
		representativeDet.put("Klug, Scott", "R-WI-2");
		representativeDet.put("Kolter, Joseph P.", "D-PA-4");
		representativeDet.put("Kostmayer, Peter H.", "D-PA-8");
		representativeDet.put("Lagomarsino, Robert J.", "R-CA-19");
		representativeDet.put("Lehman, William", "D-FL-17");
		representativeDet.put("Lent, Norman F.", "R-NY-4");
		representativeDet.put("Levine, Mel", "D-CA-27");
		representativeDet.put("Lowery, Bill", "R-CA-41");
		representativeDet.put("Luken, Charles", "D-OH-1");
		representativeDet.put("Madigan, Edward R.", "R-IL-15");
		representativeDet.put("Marlenee, Ron", "R-MT-2");
		representativeDet.put("Martin, David O'B.", "R-NY-26");
		representativeDet.put("Mavroules, Nicholas", "D-MA-6");
		representativeDet.put("McEwen, Bob", "R-OH-6");
		representativeDet.put("McGrath, Raymond J.", "R-NY-5");
		representativeDet.put("McHugh, Matthew F.", "D-NY-28");
		representativeDet.put("McMillen, Thomas", "D-MD-4");
		representativeDet.put("Miller, Clarence E.", "R-OH-10");
		representativeDet.put("Miller, John R.", "R-WA-1");
		representativeDet.put("Moody, Jim", "D-WI-5");
		representativeDet.put("Morrison, Sid", "R-WA-4");
		representativeDet.put("Mrazek, Robert J.", "D-NY-3");
		representativeDet.put("Nagle, Dave R.", "D-IA-3");
		representativeDet.put("Nichols, Dick", "D-KS-5");
		representativeDet.put("Nowak, Henry", "D-NY-33");
		representativeDet.put("Nussle, James Allen", "R-IA-2");
		representativeDet.put("Oakar, Mary Rose", "D-OH-20");		
		representativeDet.put("Olin, James R.", "D-VA-6");
		representativeDet.put("Owens, Wayne", "D-UT-2");
		representativeDet.put("Patterson, Elizabeth", "D-SC-4");
		representativeDet.put("Pease, Donald J.", "D-OH-13");
		representativeDet.put("Perkins, Carl C.", "D-KY-7");
		representativeDet.put("Peterson, Pete", "D-FL-2");
		representativeDet.put("Pursell, Carl D.", "R-MI-2");
		representativeDet.put("Ray, Richard B.", "R-GA-3");
		representativeDet.put("Reed, John F.", "D-RI-2");
		representativeDet.put("Rhodes, John J., III", "R-AZ-1");
		representativeDet.put("Rinaldo, Matthew J.", "R-NJ-7");
		representativeDet.put("Ritter, Don", "R-PA-15");
		representativeDet.put("Roe, Robert A.", "D-NJ-8");
		representativeDet.put("Roybal, Edward R.", "D-CA-25");
		representativeDet.put("Russo, Martin A.", "D-IL-3");
		representativeDet.put("Santorum, Richard John", "R-PA-18");
		representativeDet.put("Savage, Gus", "D-IL-2");
		representativeDet.put("Scheuer, James H.", "D-NY-8");		
		representativeDet.put("Schulze, Richard T.", "R-PA-5");
		representativeDet.put("Sikorski, Gerry E.", "D-MN-6");
		representativeDet.put("Slaughter, D. French, Jr.", "R/D/I-VA-7");
		representativeDet.put("Smith, Lawrence", "R-FL-16");
		representativeDet.put("Solarz, Stephen J.", "D-NY-13");
		representativeDet.put("Staggers, Harley O., Jr.", "D-WV-2");
		representativeDet.put("Stallings, Richard H.", "D-ID-2");
		representativeDet.put("Tallon, Robin", "D-SC-6");
		representativeDet.put("Thomas, Robert Lindsay", "D-GA-1");
		representativeDet.put("Traxler, Bob", "D-MI-8");
		representativeDet.put("Udall, Morris K.", "D-AZ-2");
		representativeDet.put("Vander Jagt, Guy", "R-MI-9");
		representativeDet.put("Weber, Vin", "R-MN-2");
		representativeDet.put("Weiss, Ted", "D-NY-17");
		representativeDet.put("Wolpe, Howard E.", "D-MI-3");
		representativeDet.put("Wylie, Chalmers P.", "R-OH-15");
		representativeDet.put("Yatron, Gus", "D-PA-6");
		representativeDet.put("Young Don", "R-AK-At large");
		representativeDet.put("Zeliff, Bill, Jr.", "R-NH-1");
		
		//101
		representativeDet.put("Akaka, Daniel K.", "D-HI-2");
		representativeDet.put("Bates, Jim", "D-CA-44");
		representativeDet.put("Boggs, Corinne C. (Lindy)", "D-LA-2");
		representativeDet.put("Bosco, Douglas H.", "D-CA-1");
		representativeDet.put("Brennan, Joseph E", "D-ME-1");
		representativeDet.put("Brown, Hank", "R-CO-4");
		representativeDet.put("Buechner, Jack", "R-MO-2");
		representativeDet.put("Cheney, Dick", "R-WY-At large");
		representativeDet.put("Clarke, James McC.", "D-NC-11");
		representativeDet.put("Coelho, Anthony Lee", "D-CA-15");
		representativeDet.put("Courter, Jim", "R-NJ-12");
		representativeDet.put("Craig, Larry", "R-ID-1");
		representativeDet.put("Crockett, George W., Jr.", "D-MI-13");
		representativeDet.put("DeWine, Michael", "R-OH-7");
		representativeDet.put("Douglas, Chuck", "R-NH-2");
		representativeDet.put("Dyson, Roy", "D-MD-1");
		representativeDet.put("Fauntroy, Walter E.", "D-DC");
		representativeDet.put("Florio, James J.", "D-NJ-1");
		representativeDet.put("Frenzel, Bill", "R-MN-3");
		representativeDet.put("Garcia, Robert", "D-NY-18");
		representativeDet.put("Grant, Bill", "R-FL-2");
		representativeDet.put("Hawkins, Augustus F.", "D-CA-29");
		representativeDet.put("Hiler, John Patrick", "R-IN-3");
		representativeDet.put("Kastenmeier, Robert W.", "D-WI-2");
		representativeDet.put("Leath, Marvin", "D-TX-11");
		representativeDet.put("Leland, Mickey", "D-TX-18");
		representativeDet.put("Luken, Thomas A.", "D-OH-1");
		representativeDet.put("Lukens, Donald E.", "R-OH-8");
		representativeDet.put("Martin, Lynn M.", "R-IL-16");
		representativeDet.put("Molinari, Guy", "R-NY-14");
		representativeDet.put("Morrison, Bruce A.", "D-CT-3");
		representativeDet.put("Nelson, Bill", "D-FL-11");
		representativeDet.put("Nielson, Howard C.", "R-UT-3");
		representativeDet.put("Parris, Stanford E. (Stan)", "R-VA-8");
		representativeDet.put("Pashayan, Charles, Jr.", "R-CA-17");
		representativeDet.put("Pepper, Claude", "D-FL-18");
		representativeDet.put("Robinson, Tommy F.", "D/R-AR-2");
		representativeDet.put("Rowland, John G.", "R-CT-5");
		representativeDet.put("Saiki, Patricia F.", "R-HI-1");
		representativeDet.put("Schneider, Claudine", "R-RI-2");
		representativeDet.put("Schuette, Bill", "R-MI-10");
		representativeDet.put("Shumway, Norman D.", "R-CA-14");
		representativeDet.put("Smith, Denny", "R-OR-5");
		representativeDet.put("Smith, Larkin", "R-MS-5");
		representativeDet.put("Smith, Peter", "R-VT-At large");
		representativeDet.put("Smith, Robert C.", "R/I-NH-1");
		representativeDet.put("Smith, Virginia", "D/R-NE-3");
		representativeDet.put("Stangeland, Arlan", "R-MN-7");
		representativeDet.put("Tauke, Thomas Joseph", "R-IA-2");
		representativeDet.put("Walgren, Doug", "D-PA-18");
		representativeDet.put("Whittaker, Bob", "R-KS-5");
		representativeDet.put("Wright, James C., Jr.", "D-TX-12");
		representativeDet.put("Brennan, Joseph E.", "D-ME-1");
		
		return representativeDet;
	}
}
