package edu.usc.cssl.tacit.crawlers.uscongress.services;

import java.util.HashMap;

public class RepresentativeDetails {
	static HashMap<String, String> representativeDet = new HashMap<String, String>();
	public static HashMap<String, String> getRepersentativeDetails() {
		representativeDet.put("Byrne,Bradley", "R-AL");
		representativeDet.put("Roby, Martha", "R-AL");
		representativeDet.put("Rogers, Mike", "R-AL");
		representativeDet.put("Aderholt, Robert", "R-AL");
		representativeDet.put("Brooks, Mo", "R-AL");
		representativeDet.put("Palmer, Gary", "R-AL");
		representativeDet.put("Sewell, Terri A.", "D-AL");
		representativeDet.put("Young, Don", "R-AK");
		representativeDet.put("Radewagen, Amata", "R-AS");
		representativeDet.put("Kirkpatrick, Ann", "D-AZ");
		representativeDet.put("McSally, Martha", "R-AZ");
		representativeDet.put("Grijalva, Raul", "D-AZ");
		representativeDet.put("Gosar, Paul A.", "R-AZ");
		representativeDet.put("Salmon, Matt", "R-AZ");
		representativeDet.put("Schweikert, David", "R-AZ");
		representativeDet.put("Gallego, Ruben", "D-AZ");
		representativeDet.put("Franks, Trent", "R-AZ");
		representativeDet.put("Sinema, Kyrsten", "D-AZ");
		representativeDet.put("Crawford, Rick", "R-AR");
		representativeDet.put("Hill, French", "R-AR");
		representativeDet.put("Womack, Steve", "R-AR");
		representativeDet.put("Westerman, Bruce", "R-AR");
		representativeDet.put("LaMalfa, Doug", "R-CA");
		representativeDet.put("Huffman, Jared", "D-CA");
		representativeDet.put("Garamendi, John", "D-CA");
		representativeDet.put("McClintock, Tom", "R-CA");
		representativeDet.put("Thompson, Mike", "D-CA");
		representativeDet.put("Matsui, Doris O.", "D-CA");
		representativeDet.put("Bera, Ami", "D-CA");
		representativeDet.put("Cook, Paul", "R-CA");
		representativeDet.put("McNerney, Jerry", "D-CA");
		representativeDet.put("Denham, Jeff", "R-CA");
		representativeDet.put("DeSaulnier, Mark", "D-CA");
		representativeDet.put("Pelosi, Nancy", "D-CA");
		representativeDet.put("Lee, Barbara", "D-CA");
		representativeDet.put("Speier, Jackie", "D-CA");
		representativeDet.put("Swalwell, Eric", "D-CA");
		representativeDet.put("Costa, Jim", "D-CA");
		representativeDet.put("Honda, Mike", "D-CA");
		representativeDet.put("Eshoo, Anna G.", "D-CA");
		representativeDet.put("Lofgren, Zoe", "D-CA");
		representativeDet.put("Farr, Sam", "D-CA");
		representativeDet.put("Valadao, David", "R-CA");
		representativeDet.put("Nunes, Devin", "R-CA");
		representativeDet.put("McCarthy, Kevin", "R-CA");
		representativeDet.put("Capps, Lois", "D-CA");
		representativeDet.put("Knight, Steve", "R-CA");
		representativeDet.put("Brownley, Julia", "D-CA");
		representativeDet.put("Chu, Judy", "D-CA");
		representativeDet.put("Schiff, Adam", "D-CA");
		representativeDet.put("Cárdenas, Tony", "D-CA");
		representativeDet.put("Sherman, Brad", "D-CA");
		representativeDet.put("Aguilar, Pete", "D-CA");
		representativeDet.put("Napolitano, Grace", "D-CA");
		representativeDet.put("Lieu, Ted", "D-CA");
		representativeDet.put("Becerra, Xavier", "D-CA");
		representativeDet.put("Torres, Norma", "D-CA");
		representativeDet.put("Ruiz, Raul", "D-CA");
		representativeDet.put("Bass, Karen", "D-CA");
		representativeDet.put("Sánchez, Linda", "D-CA");
		representativeDet.put("Royce, Ed", "R-CA");
		representativeDet.put("Roybal-Allard, Lucille", "D-CA");
		representativeDet.put("Takano, Mark", "D-CA");
		representativeDet.put("Calvert, Ken", "R-CA");
		representativeDet.put("Waters, Maxine", "D-CA");
		representativeDet.put("Hahn, Janice", "D-CA");
		representativeDet.put("Walters, Mimi", "R-CA");
		representativeDet.put("Sanchez, Loretta", "D-CA");
		representativeDet.put("Lowenthal, Alan", "D-CA");
		representativeDet.put("Rohrabacher, Dana", "R-CA");
		representativeDet.put("Issa, Darrell", "R-CA");
		representativeDet.put("Hunter, Duncan D.", "R-CA");
		representativeDet.put("Vargas, Juan", "D-CA");
		representativeDet.put("Peters, Scott", "D-CA");
		representativeDet.put("Davis, Susan", "D-CA");
		representativeDet.put("DeGette, Diana", "D-CO");
		representativeDet.put("Polis, Jared", "D-CO");
		representativeDet.put("Tipton, Scott", "R-CO");
		representativeDet.put("Buck, Ken", "R-CO");
		representativeDet.put("Lamborn, Doug", "R-CO");
		representativeDet.put("Coffman, Mike", "R-CO");
		representativeDet.put("Perlmutter, Ed", "D-CO");
		representativeDet.put("Larson, John B.", "D-CT");
		representativeDet.put("Courtney, Joe", "D-CT");
		representativeDet.put("DeLauro, Rosa L.", "D-CT");
		representativeDet.put("Himes, Jim", "D-CT");
		representativeDet.put("Esty, Elizabeth", "D-CT");
		representativeDet.put("Carney, John", "D-DE");
		representativeDet.put("Norton, Eleanor Holmes", "D-DC");
		representativeDet.put("Miller, Jeff", "R-FL");
		representativeDet.put("Graham, Gwen", "D-FL");
		representativeDet.put("Yoho, Ted", "R-FL");
		representativeDet.put("Crenshaw, Ander", "R-FL");
		representativeDet.put("Brown, Corrine", "D-FL");
		representativeDet.put("DeSantis, Ron", "R-FL");
		representativeDet.put("Mica, John", "R-FL");
		representativeDet.put("Posey, Bill", "R-FL");
		representativeDet.put("Grayson, Alan", "D-FL");
		representativeDet.put("Webster, Daniel", "R-FL");
		representativeDet.put("Nugent, Richard", "R-FL");
		representativeDet.put("Bilirakis, Gus M.", "R-FL");
		representativeDet.put("Jolly, David", "R-FL");
		representativeDet.put("Castor, Kathy", "D-FL");
		representativeDet.put("Ross, Dennis", "R-FL");
		representativeDet.put("Buchanan, Vern", "R-FL");
		representativeDet.put("Rooney, Tom", "R-FL");
		representativeDet.put("Murphy, Patrick", "D-FL");
		representativeDet.put("Clawson,Curt", "R-FL");
		representativeDet.put("Hastings, Alcee L.", "D-FL");
		representativeDet.put("Deutch, Ted", "D-FL");
		representativeDet.put("Frankel, Lois", "D-FL");
		representativeDet.put("Wasserman Schultz, Debbie", "D-FL");
		representativeDet.put("Wilson, Frederica", "D-FL");
		representativeDet.put("Diaz-Balart, Mario", "R-FL");
		representativeDet.put("Curbelo, Carlos", "R-FL");
		representativeDet.put("Ros-Lehtinen, Ileana", "R-FL");
		representativeDet.put("Carter, Buddy", "R-GA");
		representativeDet.put("Bishop Jr., Sanford D.", "D-GA");
		representativeDet.put("Westmoreland, Lynn A.", "R-GA");
		representativeDet.put("Johnson, Henry C. \"Hank\" Jr.", "D-GA");
		representativeDet.put("Lewis, John", "D-GA");
		representativeDet.put("Price, Tom", "R-GA");
		representativeDet.put("Woodall, Robert", "R-GA");
		representativeDet.put("Scott, Austin", "R-GA");
		representativeDet.put("Collins, Doug", "R-GA");
		representativeDet.put("Hice, Jody", "R-GA");
		representativeDet.put("Loudermilk, Barry", "R-GA");
		representativeDet.put("Allen, Rick", "R-GA");
		representativeDet.put("Scott, David", "D-GA");
		representativeDet.put("Graves, Tom", "R-GA");
		representativeDet.put("Bordallo, Madeleine", "D-GU");
		representativeDet.put("Takai, Mark", "D-HI");
		representativeDet.put("Gabbard, Tulsi", "D-HI");
		representativeDet.put("Labrador, Raul R.", "R-ID");
		representativeDet.put("Simpson, Mike", "R-ID");
		representativeDet.put("Rush, Bobby L.", "D-IL");
		representativeDet.put("Kelly, Robin", "D-IL");
		representativeDet.put("Lipinski, Daniel", "D-IL");
		representativeDet.put("Gutierrez, Luis", "D-IL");
		representativeDet.put("Quigley, Mike", "D-IL");
		representativeDet.put("Roskam, Peter J.", "R-IL");
		representativeDet.put("Davis, Danny K.", "D-IL");
		representativeDet.put("Duckworth, Tammy", "D-IL");
		representativeDet.put("Schakowsky, Jan", "D-IL");
		representativeDet.put("Dold, Bob", "R-IL");
		representativeDet.put("Foster, Bill", "D-IL");
		representativeDet.put("Bost, Mike", "R-IL");
		representativeDet.put("Davis, Rodney", "R-IL");
		representativeDet.put("Hultgren, Randy", "R-IL");
		representativeDet.put("Shimkus, John", "R-IL");
		representativeDet.put("Kinzinger, Adam", "R-IL");
		representativeDet.put("Bustos, Cheri", "D-IL");
		representativeDet.put("Schock, Aaron -- Vacancy", "Vacancy-IL");
		representativeDet.put("Visclosky, Peter", "D-IN");
		representativeDet.put("Walorski, Jackie", "R-IN");
		representativeDet.put("Stutzman, Marlin", "R-IN");
		representativeDet.put("Rokita, Todd", "R-IN");
		representativeDet.put("Brooks, Susan W.", "R-IN");
		representativeDet.put("Messer, Luke", "R-IN");
		representativeDet.put("Carson, André", "D-IN");
		representativeDet.put("Bucshon, Larry", "R-IN");
		representativeDet.put("Young, Todd", "R-IN");
		representativeDet.put("Blum, Rod", "R-IA");
		representativeDet.put("Loebsack, David", "D-IA");
		representativeDet.put("Young, David", "R-IA");
		representativeDet.put("King, Steve", "R-IA");
		representativeDet.put("Huelskamp, Tim", "R-KS");
		representativeDet.put("Jenkins, Lynn", "R-KS");
		representativeDet.put("Yoder, Kevin", "R-KS");
		representativeDet.put("Pompeo, Mike", "R-KS");
		representativeDet.put("Whitfield, Ed", "R-KY");
		representativeDet.put("Guthrie, S. Brett", "R-KY");
		representativeDet.put("Yarmuth, John A.", "D-KY");
		representativeDet.put("Massie, Thomas", "R-KY");
		representativeDet.put("Rogers, Harold", "R-KY");
		representativeDet.put("Barr, Andy", "R-KY");
		representativeDet.put("Scalise, Steve", "R-LA");
		representativeDet.put("Richmond, Cedric", "D-LA");
		representativeDet.put("Boustany Jr., Charles W.", "R-LA");
		representativeDet.put("Fleming, John", "R-LA");
		representativeDet.put("Abraham, Ralph", "R-LA");
		representativeDet.put("Graves, Garret", "R-LA");
		representativeDet.put("Pingree, Chellie", "D-ME");
		representativeDet.put("Poliquin, Bruce", "R-ME");
		representativeDet.put("Harris, Andy", "R-MD");
		representativeDet.put("Ruppersberger, C. A. Dutch", "D-MD");
		representativeDet.put("Sarbanes, John P.", "D-MD");
		representativeDet.put("Edwards, Donna F.", "D-MD");
		representativeDet.put("Hoyer, Steny H.", "D-MD");
		representativeDet.put("Delaney, John", "D-MD");
		representativeDet.put("Cummings, Elijah", "D-MD");
		representativeDet.put("Van Hollen, Chris", "D-MD");
		representativeDet.put("Neal, Richard E.", "D-MA");
		representativeDet.put("McGovern, James", "D-MA");
		representativeDet.put("Tsongas, Niki", "D-MA");
		representativeDet.put("Kennedy III, Joseph P.", "D-MA");
		representativeDet.put("Clark, Katherine", "D-MA");
		representativeDet.put("Moulton, Seth", "D-MA");
		representativeDet.put("Capuano, Michael E.", "D-MA");
		representativeDet.put("Lynch, Stephen F.", "D-MA");
		representativeDet.put("Keating, William", "D-MA");
		representativeDet.put("Benishek, Dan", "R-MI");
		representativeDet.put("Huizenga, Bill", "R-MI");
		representativeDet.put("Amash, Justin", "R-MI");
		representativeDet.put("Moolenaar, John", "R-MI");
		representativeDet.put("Kildee, Daniel", "D-MI");
		representativeDet.put("Upton, Fred", "R-MI");
		representativeDet.put("Walberg, Tim", "R-MI");
		representativeDet.put("Bishop, Mike", "R-MI");
		representativeDet.put("Levin, Sander", "D-MI");
		representativeDet.put("Miller, Candice", "R-MI");
		representativeDet.put("Trott, Dave", "R-MI");
		representativeDet.put("Dingell, Debbie", "D-MI");
		representativeDet.put("Conyers Jr., John", "D-MI");
		representativeDet.put("Lawrence, Brenda", "D-MI");
		representativeDet.put("Walz, Timothy J.", "D-MN");
		representativeDet.put("Kline, John", "R-MN");
		representativeDet.put("Paulsen, Erik", "R-MN");
		representativeDet.put("McCollum, Betty", "D-MN");
		representativeDet.put("Ellison, Keith", "D-MN");
		representativeDet.put("Emmer, Tom", "R-MN");
		representativeDet.put("Peterson, Collin C.", "D-MN");
		representativeDet.put("Nolan, Rick", "D-MN");
		representativeDet.put("Kelly, Trent", "R-MS");
		representativeDet.put("Thompson, Bennie G.", "D-MS");
		representativeDet.put("Harper, Gregg", "R-MS");
		representativeDet.put("Palazzo, Steven", "R-MS");
		representativeDet.put("Clay Jr., William \"Lacy\"", "D-MO");
		representativeDet.put("Wagner, Ann", "R-MO");
		representativeDet.put("Luetkemeyer, Blaine", "R-MO");
		representativeDet.put("Hartzler, Vicky", "R-MO");
		representativeDet.put("Cleaver, Emanuel", "D-MO");
		representativeDet.put("Graves, Sam", "R-MO");
		representativeDet.put("Long, Billy", "R-MO");
		representativeDet.put("Smith, Jason", "R-MO");
		representativeDet.put("Zinke, Ryan", "R-MT");
		representativeDet.put("Fortenberry, Jeff", "R-NE");
		representativeDet.put("Ashford, Brad", "D-NE");
		representativeDet.put("Smith, Adrian", "R-NE");
		representativeDet.put("Titus, Dina", "D-NV");
		representativeDet.put("Amodei, Mark", "R-NV");
		representativeDet.put("Heck, Joe", "R-NV");
		representativeDet.put("Hardy, Cresent", "R-NV");
		representativeDet.put("Guinta, Frank", "R-NH");
		representativeDet.put("Kuster, Ann", "D-NH");
		representativeDet.put("Norcross, Donald", "D-NJ");
		representativeDet.put("LoBiondo, Frank", "R-NJ");
		representativeDet.put("MacArthur, Tom", "R-NJ");
		representativeDet.put("Smith, Chris", "R-NJ");
		representativeDet.put("Garrett, Scott", "R-NJ");
		representativeDet.put("Pallone Jr., Frank", "D-NJ");
		representativeDet.put("Lance, Leonard", "R-NJ");
		representativeDet.put("Sires, Albio", "D-NJ");
		representativeDet.put("Pascrell Jr., Bill", "D-NJ");
		representativeDet.put("Payne Jr., Donald", "D-NJ");
		representativeDet.put("Frelinghuysen, Rodney", "R-NJ");
		representativeDet.put("Watson Coleman, Bonnie", "D-NJ");
		representativeDet.put("Lujan Grisham, Michelle", "D-NM");
		representativeDet.put("Pearce, Steve", "R-NM");
		representativeDet.put("Lujan, Ben R.", "D-NM");
		representativeDet.put("Zeldin, Lee", "R-NY");
		representativeDet.put("King, Pete", "R-NY");
		representativeDet.put("Israel, Steve", "D-NY");
		representativeDet.put("Rice, Kathleen", "D-NY");
		representativeDet.put("Meeks, Gregory W.", "D-NY");
		representativeDet.put("Meng, Grace", "D-NY");
		representativeDet.put("Velázquez, Nydia M.", "D-NY");
		representativeDet.put("Jeffries, Hakeem", "D-NY");
		representativeDet.put("Clarke, Yvette D.", "D-NY");
		representativeDet.put("Nadler, Jerrold", "D-NY");
		representativeDet.put("Donovan, Daniel", "R-NY");
		representativeDet.put("Maloney, Carolyn", "D-NY");
		representativeDet.put("Rangel, Charles B.", "D-NY");
		representativeDet.put("Crowley, Joseph", "D-NY");
		representativeDet.put("Serrano, José E.", "D-NY");
		representativeDet.put("Engel, Eliot", "D-NY");
		representativeDet.put("Lowey, Nita", "D-NY");
		representativeDet.put("Maloney, Sean Patrick", "D-NY");
		representativeDet.put("Gibson, Chris", "R-NY");
		representativeDet.put("Tonko, Paul D.", "D-NY");
		representativeDet.put("Stefanik, Elise", "R-NY");
		representativeDet.put("Hanna, Richard", "R-NY");
		representativeDet.put("Reed, Tom", "R-NY");
		representativeDet.put("Katko, John", "R-NY");
		representativeDet.put("Slaughter, Louise", "D-NY");
		representativeDet.put("Higgins, Brian", "D-NY");
		representativeDet.put("Collins, Chris", "R-NY");
		representativeDet.put("Butterfield, G.K.", "D-NC");
		representativeDet.put("Ellmers, Renee", "R-NC");
		representativeDet.put("Jones, Walter B.", "R-NC");
		representativeDet.put("Price, David", "D-NC");
		representativeDet.put("Foxx, Virginia", "R-NC");
		representativeDet.put("Walker, Mark", "R-NC");
		representativeDet.put("Rouzer, David", "R-NC");
		representativeDet.put("Hudson, Richard", "R-NC");
		representativeDet.put("Pittenger, Robert", "R-NC");
		representativeDet.put("McHenry, Patrick T.", "R-NC");
		representativeDet.put("Meadows, Mark", "R-NC");
		representativeDet.put("Adams, Alma", "D-NC");
		representativeDet.put("Holding, George", "R-NC");
		representativeDet.put("Cramer, Kevin", "R-ND");
		representativeDet.put("Sablan, Gregorio", "D-MP");
		representativeDet.put("Chabot, Steve", "R-OH");
		representativeDet.put("Wenstrup, Brad", "R-OH");
		representativeDet.put("Beatty, Joyce", "D-OH");
		representativeDet.put("Jordan, Jim", "R-OH");
		representativeDet.put("Latta, Robert E.", "R-OH");
		representativeDet.put("Johnson, Bill", "R-OH");
		representativeDet.put("Gibbs, Bob", "R-OH");
		representativeDet.put("Boehner, John A.", "R-OH");
		representativeDet.put("Kaptur, Marcy", "D-OH");
		representativeDet.put("Turner, Michael", "R-OH");
		representativeDet.put("Fudge, Marcia L.", "D-OH");
		representativeDet.put("Tiberi, Pat", "R-OH");
		representativeDet.put("Ryan, Tim", "D-OH");
		representativeDet.put("Joyce, David", "R-OH");
		representativeDet.put("Stivers, Steve", "R-OH");
		representativeDet.put("Renacci, Jim", "R-OH");
		representativeDet.put("Bridenstine, Jim", "R-OK");
		representativeDet.put("Mullin, Markwayne", "R-OK");
		representativeDet.put("Lucas, Frank", "R-OK");
		representativeDet.put("Cole, Tom", "R-OK");
		representativeDet.put("Russell, Steve", "R-OK");
		representativeDet.put("Bonamici, Suzanne", "D-OR");
		representativeDet.put("Walden, Greg", "R-OR");
		representativeDet.put("Blumenauer, Earl", "D-OR");
		representativeDet.put("DeFazio, Peter", "D-OR");
		representativeDet.put("Schrader, Kurt", "D-OR");
		representativeDet.put("Brady, Robert", "D-PA");
		representativeDet.put("Fattah, Chaka", "D-PA");
		representativeDet.put("Kelly, Mike", "R-PA");
		representativeDet.put("Perry, Scott", "R-PA");
		representativeDet.put("Thompson, Glenn W.", "R-PA");
		representativeDet.put("Costello, Ryan", "R-PA");
		representativeDet.put("Meehan, Pat", "R-PA");
		representativeDet.put("Fitzpatrick, Michael G.", "R-PA");
		representativeDet.put("Shuster, Bill", "R-PA");
		representativeDet.put("Marino, Tom", "R-PA");
		representativeDet.put("Barletta, Lou", "R-PA");
		representativeDet.put("Rothfus, Keith", "R-PA");
		representativeDet.put("Boyle, Brendan", "D-PA");
		representativeDet.put("Doyle, Mike", "D-PA");
		representativeDet.put("Dent, Charles W.", "R-PA");
		representativeDet.put("Pitts, Joseph R.", "R-PA");
		representativeDet.put("Cartwright, Matthew", "D-PA");
		representativeDet.put("Murphy, Tim", "R-PA");
		representativeDet.put("Pierluisi, Pedro", "D-PR");
		representativeDet.put("Cicilline, David", "D-RI");
		representativeDet.put("Langevin, Jim", "D-RI");
		representativeDet.put("Sanford, Mark", "R-SC");
		representativeDet.put("Wilson, Joe", "R-SC");
		representativeDet.put("Duncan, Jeff", "R-SC");
		representativeDet.put("Gowdy, Trey", "R-SC");
		representativeDet.put("Mulvaney, Mick", "R-SC");
		representativeDet.put("Clyburn, James E.", "D-SC");
		representativeDet.put("Rice, Tom", "R-SC");
		representativeDet.put("Noem, Kristi", "R-SD");
		representativeDet.put("Roe, Phil", "R-TN");
		representativeDet.put("Duncan Jr., John J.", "R-TN");
		representativeDet.put("Fleischmann, Chuck", "R-TN");
		representativeDet.put("DesJarlais, Scott", "R-TN");
		representativeDet.put("Cooper, Jim", "D-TN");
		representativeDet.put("Black, Diane", "R-TN");
		representativeDet.put("Blackburn, Marsha", "R-TN");
		representativeDet.put("Fincher, Stephen", "R-TN");
		representativeDet.put("Cohen, Steve", "D-TN");
		representativeDet.put("Gohmert, Louie", "R-TX");
		representativeDet.put("Poe, Ted", "R-TX");
		representativeDet.put("Johnson, Sam", "R-TX");
		representativeDet.put("Ratcliffe, John", "R-TX");
		representativeDet.put("Hensarling, Jeb", "R-TX");
		representativeDet.put("Barton, Joe", "R-TX");
		representativeDet.put("Culberson, John", "R-TX");
		representativeDet.put("Brady, Kevin", "R-TX");
		representativeDet.put("Green, Al", "D-TX");
		representativeDet.put("McCaul, Michael T.", "R-TX");
		representativeDet.put("Conaway, K. Michael", "R-TX");
		representativeDet.put("Granger, Kay", "R-TX");
		representativeDet.put("Thornberry, Mac", "R-TX");
		representativeDet.put("Weber, Randy", "R-TX");
		representativeDet.put("Hinojosa, Rubén", "D-TX");
		representativeDet.put("O'Rourke, Beto", "D-TX");
		representativeDet.put("Flores, Bill", "R-TX");
		representativeDet.put("Jackson Lee, Sheila", "D-TX");
		representativeDet.put("Neugebauer, Randy", "R-TX");
		representativeDet.put("Castro, Joaquin", "D-TX");
		representativeDet.put("Smith, Lamar", "R-TX");
		representativeDet.put("Olson, Pete", "R-TX");
		representativeDet.put("Hurd, Will", "R-TX");
		representativeDet.put("Marchant, Kenny", "R-TX");
		representativeDet.put("Williams, Roger", "R-TX");
		representativeDet.put("Burgess, Michael", "R-TX");
		representativeDet.put("Farenthold, Blake", "R-TX");
		representativeDet.put("Cuellar, Henry", "D-TX");
		representativeDet.put("Green, Gene", "D-TX");
		representativeDet.put("Johnson, Eddie Bernice", "D-TX");
		representativeDet.put("Carter, John", "R-TX");
		representativeDet.put("Sessions, Pete", "R-TX");
		representativeDet.put("Veasey, Marc", "D-TX");
		representativeDet.put("Vela, Filemon", "D-TX");
		representativeDet.put("Doggett, Lloyd", "D-TX");
		representativeDet.put("Babin, Brian", "R-TX");
		representativeDet.put("Bishop, Rob", "R-UT");
		representativeDet.put("Stewart, Chris", "R-UT");
		representativeDet.put("Chaffetz, Jason", "R-UT");
		representativeDet.put("Love, Mia", "R-UT");
		representativeDet.put("Welch, Peter", "D-VT");
		representativeDet.put("Plaskett, Stacey", "D-VI");
		representativeDet.put("Wittman, Robert J.", "R-VA");
		representativeDet.put("Rigell, Scott", "R-VA");
		representativeDet.put("Scott, Robert C.", "D-VA");
		representativeDet.put("Forbes, J. Randy", "R-VA");
		representativeDet.put("Hurt, Robert", "R-VA");
		representativeDet.put("Goodlatte, Bob", "R-VA");
		representativeDet.put("Brat, Dave", "R-VA");
		representativeDet.put("Beyer, Don", "D-VA");
		representativeDet.put("Griffith, Morgan", "R-VA");
		representativeDet.put("Comstock, Barbara", "R-VA");
		representativeDet.put("Connolly, Gerald E. \"Gerry\"", "D-VA");
		representativeDet.put("DelBene, Suzan", "D-WA");
		representativeDet.put("Larsen, Rick", "D-WA");
		representativeDet.put("Herrera Beutler, Jaime", "R-WA");
		representativeDet.put("Newhouse, Dan", "R-WA");
		representativeDet.put("McMorris Rodgers, Cathy", "R-WA");
		representativeDet.put("Kilmer, Derek", "D-WA");
		representativeDet.put("McDermott, Jim", "D-WA");
		representativeDet.put("Reichert, David G.", "R-WA");
		representativeDet.put("Smith, Adam", "D-WA");
		representativeDet.put("Heck, Denny", "D-WA");
		representativeDet.put("McKinley, David", "R-WV");
		representativeDet.put("Mooney, Alex", "R-WV");
		representativeDet.put("Jenkins, Evan", "R-WV");
		representativeDet.put("Ryan, Paul", "R-WI");
		representativeDet.put("Pocan, Mark", "D-WI");
		representativeDet.put("Kind, Ron", "D-WI");
		representativeDet.put("Moore, Gwen", "D-WI");
		representativeDet.put("Sensenbrenner, F. James", "R-WI");
		representativeDet.put("Grothman, Glenn", "R-WI");
		representativeDet.put("Duffy, Sean P.", "R-WI");
		representativeDet.put("Ribble, Reid", "R-WI");
		representativeDet.put("Lummis, Cynthia M.", "R-WY");
		
		return representativeDet;
	}
}
