package edu.usc.cssl.tacit.crawlers.uscongress.services;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class SenatorDetails {

	static List<String> senatorDet = new ArrayList<String>();
	public static ArrayList<String> getSenatorDetails() {
		//101
		senatorDet.add("Gorton, Slade [R-WA]");
		senatorDet.add("Lott, Trent [R-MS]");
		senatorDet.add("Jeffords, James [I-VT]");
		senatorDet.add("Coats, Dan [R-IN]");
		senatorDet.add("Mack, Connie [R-FL]");
		senatorDet.add("Bryan, Richard H. [D-NV]");
		senatorDet.add("Robb, Charles [D-VA]");
		senatorDet.add("Kerrey, Bob [D-NE]");	
		senatorDet.add("Kerrey, J. Robert [D-NE]");
		senatorDet.add("Kohl, Herb [D-WI]");
		senatorDet.add("Lieberman, Joseph I. [D-CT]");
		senatorDet.add("Burns, Conrad R. [R-MT]");		
		senatorDet.add("Akaka, Daniel K. [D-HI]");
		senatorDet.add("Smith, Robert C. [R-NH]");
		//102
		senatorDet.add("Brown, Hank [R-CO");
		senatorDet.add("Craig, Larry E. [R-ID");
		senatorDet.add("Wellstone, Paul D. [D-MN");
		senatorDet.add("Wellstone, Paul David [D-MN");
		senatorDet.add("Seymour, John [R-CA");
		senatorDet.add("Wofford, Harris [D-PA");
		senatorDet.add("Burdick, Jocelyn [D-ND");		
		senatorDet.add("Feinstein, Dianne [D-CA");
		senatorDet.add("Conrad, Kent [D-ND");
		senatorDet.add("Dorgan, Byron L. [D-ND");
		senatorDet.add("Mathews, Harlan [D-TN");
		//103			
		senatorDet.add("Boxer, Barbara [D-CA");
		senatorDet.add("Gregg, Judd [R-NH");
		senatorDet.add("Campbell, Ben Nighthorse [D/R-CO");
		senatorDet.add("Moseley Braun, Carol [D-IL");
		senatorDet.add("Faircloth, Lauch [R-NC");		
		senatorDet.add("Coverdell, Paul [R-GA");
		senatorDet.add("Murray, Patty [D-WA");		
		senatorDet.add("Feingold, Russell D. [D-WI");
		//senatorDet.add("Bennett, Robert [R-UT");
		senatorDet.add("Kempthorne, Dirk [R-ID");		
		senatorDet.add("Krueger, Robert C. [D-TX");
		senatorDet.add("Krueger, Bob [D-TX");
		senatorDet.add("Hutchison, Kay Bailey [R-TX");
		senatorDet.add("Inhofe, James [R-OK");
		senatorDet.add("Inhofe, Jim [R-OK");
		senatorDet.add("Thompson, Fred [R-TN");
		//104
		senatorDet.add("Snowe, Olympia [R-ME");
		senatorDet.add("Kyl, Jon [R-AZ");
		senatorDet.add("DeWine, Mike [R-OH");
		senatorDet.add("Thomas, Craig [R-WY");
		senatorDet.add("Santorum, Rick [R-PA");
		senatorDet.add("Grams, Rod [R-MN");
		senatorDet.add("Ashcroft, John [R-MO");
		senatorDet.add("Abraham, Spencer [R-MI");
		senatorDet.add("Frist, Bill [R-TN");
		senatorDet.add("Frist, William [R-TN");
		senatorDet.add("Frist, William H. [R-TN");
		senatorDet.add("Wyden, Ron [D-OR");
		senatorDet.add("Frahm, Sheila [R-KS");
		senatorDet.add("Brownback, Sam [R-KS");
		//105
		senatorDet.add("Roberts, Pat [R-KS");
		senatorDet.add("Durbin, Richard [D-IL");
		senatorDet.add("Torricelli, Robert [D-NJ");
		senatorDet.add("Johnson, Tim [D-SD");
		//senatorDet.add("Allard, Wayne [R-CO");
		senatorDet.add("Reed, Jack [D-RI");
		senatorDet.add("Hutchinson, Tim [R-AR");
		senatorDet.add("Cleland, Max [D-GA");
		senatorDet.add("Landrieu, Mary [D-LA");
		senatorDet.add("Sessions, Jeff [R-AL");
		senatorDet.add("Smith, Gordon [R-OR");
		senatorDet.add("Hagel, Chuck [R-NE");
		senatorDet.add("Collins, Susan [R-ME");
		senatorDet.add("Enzi, Michael [R-WY");
		//106
		senatorDet.add("Schumer, Charles [D-NY");
		senatorDet.add("Bunning, Jim [R-KY");
		senatorDet.add("Crapo, Mike [R-ID");
		senatorDet.add("Crapo, Michael D. [R-ID");
		senatorDet.add("Lincoln, Blanche [D-AR");
		senatorDet.add("Voinovich, George [R-OH");
		senatorDet.add("Voinovich, George V. [R-OH");
		senatorDet.add("Bayh, Evan [D-IN");
		senatorDet.add("Fitzgerald, Peter [R-IL");
		senatorDet.add("Fitzgerald, Peter G. [R-IL");
		senatorDet.add("Edwards, John [D-NC");
		senatorDet.add("Chafee, Lincoln [R-RI");
		senatorDet.add("Miller, Zell [D-GA");
		//107
		senatorDet.add("Nelson, Bill [D-FL");
		senatorDet.add("Carper, Tom [D-DE");
		senatorDet.add("Carper, Thomas R. [D-DE");
		senatorDet.add("Stabenow, Debbie [D-MI");
		senatorDet.add("Ensign, John [R-NV");
		senatorDet.add("Allen, George [R-VA");
		senatorDet.add("Cantwell, Maria [D-WA");
		senatorDet.add("Nelson, Ben [D-NE");
		senatorDet.add("Clinton, Hillary Rodham [D-NY");
		senatorDet.add("Corzine, Jon [D-NJ");
		senatorDet.add("Corzine, Jon S. [D-NJ");
		senatorDet.add("Carnahan, Jean [D-MO");
		senatorDet.add("Dayton, Mark [D-MN");
		senatorDet.add("Barkley, Dean [I-MN");
		senatorDet.add("Barkley, Dean M. [I-MN");
		senatorDet.add("Talent, James [R-MO");
		senatorDet.add("Cornyn, John [R-TX");
		senatorDet.add("Murkowski, Lisa [R-AK");
		//108		
		senatorDet.add("Lautenberg, Frank R. [D-NJ");
		senatorDet.add("Chambliss, Saxby [R-GA");
		senatorDet.add("Graham, Lindsey [R-SC");
		senatorDet.add("Sununu, John [R-NH");
		senatorDet.add("Alexander, Lamar [R-TN");
		senatorDet.add("Dole, Elizabeth [R-NC");
		senatorDet.add("Dole, Elizabeth H. [R-NC");
		senatorDet.add("Coleman, Norm [R-MN");
		senatorDet.add("Pryor, Mark [D-AR");
		senatorDet.add("Pryor, Mark Lunsford [D-AR");
		// Additional senators
		senatorDet.add("Lautenberg, Frank [D-NJ");
		// All senators
		senatorDet.add("Bassett, Richard [Anti-Admin/Pro-Admin-DE");
		senatorDet.add("Butler, Pierce [Pro-Admin/Anti-Admin/R-SC");
		senatorDet.add("Carroll, Charles [Pro-Admin-MD");
		senatorDet.add("Dalton, Tristram [Pro-Admin-MA");
		senatorDet.add("Ellsworth, Oliver [Pro-Admin/F-CT");
		senatorDet.add("Elmer, Jonathan [Pro-Admin-NJ");
		senatorDet.add("Few, William [Anti-Admin-GA");
		senatorDet.add("Grayson, William [Anti-Admin-VA");
		senatorDet.add("Gunn, James [Anti-Admin/F-GA");
		senatorDet.add("Henry, John [Pro-Admin/F-MD");
		senatorDet.add("Izard, Ralph [Pro-Admin-SC");
		senatorDet.add("Johnson, William S. [Pro-Admin-CT");
		senatorDet.add("Langdon, John [Pro-Admin/Anti-Admin/R-NH");
		senatorDet.add("Lee, Richard Henry [Anti-Admin-VA");
		senatorDet.add("Maclay, William [Anti-Admin-PA");
		senatorDet.add("Morris, Robert [Pro-Admin-PA");
		senatorDet.add("Paterson, William [Pro-Admin-NJ");
		senatorDet.add("Read, George [Pro-Admin-DE");
		senatorDet.add("Schuyler, Philip John [Pro-Admin-NY");
		senatorDet.add("Strong, Caleb [Pro-Admin/F-MA");
		senatorDet.add("Wingate, Paine [Anti-Admin-NH");
		senatorDet.add("King, Rufus [Pro-Admin/F-NY");
		senatorDet.add("Johnston, Samuel [Pro-Admin-NC");
		senatorDet.add("Hawkins, Benjamin [Pro-Admin/Anti-Admin-NC");
		senatorDet.add("Walker, John [Pro-Admin-VA");
		senatorDet.add("Foster, Theodore [Pro-Admin/F/R-RI");
		senatorDet.add("Stanton, Joseph, Jr. [Anti-Admin-RI");
		senatorDet.add("Monroe, James [Anti-Admin-VA");
		senatorDet.add("Dickinson, Philemon [Pro-Admin-NJ");
		senatorDet.add("Bradley, Stephen R. [Anti-Admin-VT");
		senatorDet.add("Burr, Aaron [Anti-Admin/R-NY");
		senatorDet.add("Cabot, George [Pro-Admin/F-MA");
		senatorDet.add("Rutherfurd, John [Pro-Admin/F-NJ");
		senatorDet.add("Sherman, Roger [Pro-Admin-CT");
		senatorDet.add("Robinson, Moses [Anti-Admin/R-VT");
		senatorDet.add("Brown, John [Anti-Admin/R-KY");
		senatorDet.add("Edwards, John [Anti-Admin-KY");
		senatorDet.add("Taylor, John [Anti-Admin-VA");
		senatorDet.add("Potts, Richard [Pro-Admin/F-MD");
		senatorDet.add("Bradford, William [Pro-Admin/F-RI");
		senatorDet.add("Frelinghuysen, Frederick [Pro-Admin/F-NJ");
		senatorDet.add("Jackson, James [Anti-Admin-GA");
		senatorDet.add("Livermore, Samuel [Pro-Admin/F-NH");
		senatorDet.add("Martin, Alexander [Anti-Admin/R-NC");
		senatorDet.add("Vining, John [Pro-Admin/F-DE");
		senatorDet.add("Mitchell, Stephen M. [Pro-Admin-CT");
		senatorDet.add("Ross, James [Pro-Admin/F-PA");
		senatorDet.add("Mason, Stevens T. [R-VA");
		senatorDet.add("Tazewell, Henry [Anti-Admin/R-VA");
		senatorDet.add("Latimer, Henry [F-DE");
		senatorDet.add("Bingham, William [F-PA");
		senatorDet.add("Bloodworth, Timothy [R-NC");
		senatorDet.add("Marshall, Humphrey [F-KY");
		senatorDet.add("Paine, Elijah [F-VT");
		senatorDet.add("Read, Jacob [F-SC");
		senatorDet.add("Trumbull, Jonathan, Jr. [F-CT");
		senatorDet.add("Walton, George [F-GA");
		senatorDet.add("Tattnall, Josiah [R-GA");
		senatorDet.add("Hillhouse, James [F-CT");
		senatorDet.add("Goodhue, Benjamin [F-MA");
		senatorDet.add("Sedgwick, Theodore [F-MA");
		senatorDet.add("Blount, William [R-TN");
		senatorDet.add("Cocke, William [R-TN");
		senatorDet.add("Tracy, Uriah [F-CT");
		senatorDet.add("Tichenor, Isaac [F-VT");
		senatorDet.add("Laurance, John [F-NY");
		senatorDet.add("Stockton, Richard [F-NJ");
		senatorDet.add("Howard, John E. [F-MD");
		senatorDet.add("Hunter, John [R-SC");
		senatorDet.add("Schuyler, Philip J. [F-NY");
		senatorDet.add("Anderson, Joseph [R-TN");
		senatorDet.add("Jackson, Andrew [R-TN");
		senatorDet.add("Chipman, Nathaniel [F-VT");
		senatorDet.add("Greene, Ray [F-RI");
		senatorDet.add("Lloyd, James [F-MD");
		senatorDet.add("Hobart, John S. [F-NY");
		senatorDet.add("Clayton, Joshua [F-DE");
		senatorDet.add("North, William [F-NY");
		senatorDet.add("Watson, James [F-NY");
		senatorDet.add("Smith, Daniel [R-TN");
		senatorDet.add("Pinckney, Charles [R-SC");
		senatorDet.add("Wells, William Hill [F-DE");
		senatorDet.add("Anderson, Joseph [R-TN");
		senatorDet.add("Baldwin, Abraham [R-GA");
		senatorDet.add("Dayton, Jonathan [F-NJ");
		senatorDet.add("Dexter, Samuel [F-MA");
		senatorDet.add("Schureman, James [F-NJ");
		senatorDet.add("Nicholas, Wilson C. [R-VA");
		senatorDet.add("Morris, Gouverneur [F-NY");
		senatorDet.add("Foster, Dwight [F-MA");
		senatorDet.add("Armstrong, John, Jr. [R-NY");
		senatorDet.add("Mason, Jonathan [F-MA");
		senatorDet.add("Hindman, William [F-MD");
		senatorDet.add("Ogden, Aaron [F-NJ");
		senatorDet.add("White, Samuel [F-DE");
		senatorDet.add("Breckinridge, John [R-KY");
		senatorDet.add("Colhoun, John Ewing [R-SC");
		senatorDet.add("Muhlenberg, John Peter G. [R-PA");
		senatorDet.add("Sheafe, James [F-NH");
		senatorDet.add("Stone, David [R-NC");
		senatorDet.add("Ellery, Christopher [R-RI");
		senatorDet.add("Olcott, Simeon [F-NH");
		senatorDet.add("Logan, George [R-PA");
		senatorDet.add("Wright, Robert [R-MD");
		senatorDet.add("Sumter, Thomas [R-SC");
		senatorDet.add("Clinton, De Witt [R-NY");
		senatorDet.add("Plumer, William [F-NH");
		senatorDet.add("Butler, Pierce [R-SC");
		senatorDet.add("Adams, John Quincy [F-MA");
		senatorDet.add("Bailey, Theodorus [R-NY");
		senatorDet.add("Maclay, Samuel [R-PA");
		senatorDet.add("Pickering, Timothy [R-MA");
		senatorDet.add("Potter, Samuel J. [R-RI");
		senatorDet.add("Smith, Israel [R-VT");
		senatorDet.add("Smith, Samuel [R-MD");
		senatorDet.add("Smith, John [R-OH");
		senatorDet.add("Worthington, Thomas [R-OH");
		senatorDet.add("Condit, John [R-NJ");
		senatorDet.add("Armstrong, John, Jr. [R-NY");
		senatorDet.add("Venable, Abraham B. [R-VA");
		senatorDet.add("Armstrong, John, Jr. [R-NY");
		senatorDet.add("Giles, William B. [R-VA");
		senatorDet.add("Moore, Andrew [R-VA");
		senatorDet.add("Howland, Benjamin [R-RI");
		senatorDet.add("Mitchill, Samuel [R-NY");
		senatorDet.add("Bayard, James Asheton, Sr. [F-DE");
		senatorDet.add("Gaillard, John [R/CRR/J-SC");
		senatorDet.add("Fenner, James [R-RI");
		senatorDet.add("Gilman, Nicholas [R-NH");
		senatorDet.add("Kitchell, Aaron [R-NJ");
		senatorDet.add("Thruston, Buckner [R-KY");
		senatorDet.add("Turner, James [R-NC");
		senatorDet.add("Adair, John [R-KY");
		senatorDet.add("Milledge, John [R-GA");
		senatorDet.add("Reed, Philip [R-MD");
		senatorDet.add("Clay, Henry [R-KY");
		senatorDet.add("Gregg, Andrew [R-PA");
		senatorDet.add("Mathewson, Elisha [R-RI");
		senatorDet.add("Parker, Nahum [R-NH");
		senatorDet.add("Pope, John [R-KY");
		senatorDet.add("Tiffin, Edward [R-OH");
		senatorDet.add("Jones, George [R-GA");
		senatorDet.add("Robinson, Jonathan [R-VT");
		senatorDet.add("Goodrich, Chauncey [F-CT");
		senatorDet.add("Crawford, William H. [R-GA");
		senatorDet.add("Meigs, Return Jonathan, Jr. [R-OH");
		senatorDet.add("Leib, Michael [R-PA");
		senatorDet.add("Brent, Richard [R-VA");
		senatorDet.add("German, Obadiah [R-NY");
		senatorDet.add("Lambert, John [R-NJ");
		senatorDet.add("Malbone, Francis [F-RI");
		senatorDet.add("Condit, John [R-NJ");
		senatorDet.add("Whiteside, Jenkin [R-TN");
		senatorDet.add("Griswold, Stanley [R-OH");
		senatorDet.add("Champlin, Christopher G. [F-RI");
		senatorDet.add("Tait, Charles [R-GA");
		senatorDet.add("Campbell, Alexander [R-OH");
		senatorDet.add("Clay, Henry [R-KY");
		senatorDet.add("Horsey, Outerbridge [F-DE");
		senatorDet.add("Dana, Samuel W. [F-CT");
		senatorDet.add("Cutts, Charles [R-NH");
		senatorDet.add("Worthington, Thomas [R-OH");
		senatorDet.add("Taylor, John [R-SC");
		senatorDet.add("Bibb, George M. [R-KY");
		senatorDet.add("Howell, Jeremiah B. [R-RI");
		senatorDet.add("Varnum, Joseph B. [R-MA");
		senatorDet.add("Campbell, George W. [R-TN");
		senatorDet.add("Hunter, William [F-RI");
		senatorDet.add("Destrehan, John N. [NA-LA)");
		senatorDet.add("Magruder, Allan B. [R-LA");
		senatorDet.add("Posey, Thomas [R-LA");
		senatorDet.add("Brown, James [R-LA");
		senatorDet.add("Bledsoe, Jesse [R-KY");
		senatorDet.add("Chase, Dudley [R-VT");
		senatorDet.add("Fromentin, Eligius [R-LA");
		senatorDet.add("Lacock, Abner [R-PA");
		senatorDet.add("Morrow, Jeremiah [R-OH");
		senatorDet.add("Bulloch, William B. [R-GA");
		senatorDet.add("Gore, Christopher [F-MA");
		senatorDet.add("Daggett, David [F-CT");
		senatorDet.add("Goldsborough, Robert H. [F-MD");
		senatorDet.add("Mason, Jeremiah [F-NH");
		senatorDet.add("Bibb, William Wyatt [R-GA");
		senatorDet.add("1814 Locke, Francis [NA-NC");
		senatorDet.add("Roberts, Jonathan [R-PA");
		senatorDet.add("Wharton, Jesse [R-TN");
		senatorDet.add("Thompson, Thomas W. [F-NH");
		senatorDet.add("Walker, George [R-KY");
		senatorDet.add("Kerr, Joseph [R-OH");
		senatorDet.add("Barry, William T. [R-KY");
		senatorDet.add("Barbour, James [R/CRR-VA");
		senatorDet.add("Talbot, Isham [R-KY");
		senatorDet.add("Ruggles, Benjamin [R/CRR/Adams/AJ-OH");
		senatorDet.add("Sanford, Nathan [R-NY");
		senatorDet.add("Wilson, James J. [R-NJ");
		senatorDet.add("Williams, John [R-TN");
		senatorDet.add("Macon, Nathaniel [R/CRR/J-NC");
		senatorDet.add("Mason, Armistead T. [R-VA");
		senatorDet.add("Harper, Robert G. [F-MD");
		senatorDet.add("Ashmun, Eli P. [F-MA");
		senatorDet.add("Troup, George M. [R-GA");
		senatorDet.add("Hardin, Martin D. [F-KY");
		senatorDet.add("Smith, William [R-SC");
		senatorDet.add("Stokes, Montfort [R-NC");
		senatorDet.add("Noble, James [R/CRR/Adams/AJ-IN");
		senatorDet.add("Taylor, Waller [R/Adams-Clay R-IN");
		senatorDet.add("Hanson, Alexander Contee [F-MD");
		senatorDet.add("Burrill, James, Jr. [F-RI");
		senatorDet.add("Claiborne, William C. C. [D-LA");
		senatorDet.add("Crittenden, John J. [R-KY");
		senatorDet.add("Dickerson, Mahlon [R/CRR/J-NJ");
		senatorDet.add("Eppes, John W. [R-VA");
		senatorDet.add("Morril, David L. [R-NH");
		senatorDet.add("Otis, Harrison Gray [F-MA");
		senatorDet.add("Van Dyke, Nicholas [F/Adams-Clay F/Adams-DE");
		senatorDet.add("Storer, Clement [R-NH");
		senatorDet.add("Fisk, James [R-VT");
		senatorDet.add("Leake, Walter [R-MS");
		senatorDet.add("Williams, Thomas [R/JR/J-MS");
		senatorDet.add("Johnson, Henry [R/Adams-Clay R-LA");
		senatorDet.add("Mellen, Prentiss [F-MA");
		senatorDet.add("Eaton, John H. [R/JR/J-TN");
		senatorDet.add("Palmer, William A. [R/Adams-Clay R-VT");
		senatorDet.add("Forsyth, John [R-GA");
		senatorDet.add("Thomas, Jesse B. [R/CRR/Adams-IL");
		senatorDet.add("Edwards, Ninian [R/Adams-Clay R-IL");
		senatorDet.add("Elliott, John [R/CRR-GA");
		senatorDet.add("Lanman, James [R/CRR-CT");
		senatorDet.add("Logan, William [R-KY");
		senatorDet.add("Lowrie, Walter [R/CRR-PA");
		senatorDet.add("Parrott, John F. [R/Adams-Clay R-NH");
		senatorDet.add("Trimble, William A. [R-OH");
		senatorDet.add("Walker, Freeman [R-GA");
		senatorDet.add("Johnson, Richard M. [R/JR/J-KY");
		senatorDet.add("Pleasants, James [R-VA");
		senatorDet.add("King, William R. [R/JR/J/D-AL");
		senatorDet.add("Walker, John W. [R-AL");
		senatorDet.add("Pinkney, William [R-MD");
		senatorDet.add("Lloyd, Edward [R/CRR/J-MD");
		senatorDet.add("Mills, Elijah H. [F/Adams-Clay F/Adams-MA");
		senatorDet.add("Holmes, John [R/CRR/Adams-ME");
		senatorDet.add("Chandler, John [R/CRR/J-ME");
		senatorDet.add("Holmes, David [R/JR-MS");
		senatorDet.add("Knight, Nehemiah R. [R/CRR/Adams/AJ/W-RI");
		senatorDet.add("Southard, Samuel L. [R-NJ");
		senatorDet.add("Boardman, Elijah [R-CT");
		senatorDet.add("De Wolf, James [R/CRR-RI");
		senatorDet.add("Seymour, Horatio [R/Adams-Clay R/Adams/AJ-VT");
		senatorDet.add("Van Buren, Martin [R/CRR/J-NY");
		senatorDet.add("Barton, David [R/Adams-Clay R/Adams/AJ-MO");
		senatorDet.add("Benton, Thomas Hart [R/JR/J/D-MO");
		senatorDet.add("Ware, Nicholas [R/CRR-GA");
		senatorDet.add("Findlay, William [R/JR/J-PA");
		senatorDet.add("Brown, Ethan Allen [R/Adams-Clay R-OH");
		senatorDet.add("Rodney, Caesar A. [R-DE");
		senatorDet.add("Kelly, William [R/JR-AL");
		senatorDet.add("Smith, Samuel [R/CRR/J-MD");
		senatorDet.add("Taylor, John [R/CRR-VA");
		senatorDet.add("Bell, Samuel [Adams-Clay R/Adams/AJ-NH");
		senatorDet.add("Branch, John [CRR/J-NC");
		senatorDet.add("Hayne, Robert Young [JR/J/N-SC");
		senatorDet.add("Edwards, Henry W. [JR/J-CT");
		senatorDet.add("McIlvaine, Joseph [Adams-Clay R/Adams-NJ");
		senatorDet.add("Clayton, Thomas [Adams-Clay F/Adams-DE");
		senatorDet.add("Johnston, Josiah S. [Adams-Clay R/Adams/AJ-LA");
		senatorDet.add("Cobb, Thomas W. [CRR/J-GA");
		senatorDet.add("Bouligny, Dominique [Adams-Clay R/Adams-LA");
		senatorDet.add("McLean, John [CRR-IL");
		senatorDet.add("Tazewell, Littleton W. [JR/J-VA");
		senatorDet.add("Berrien, John Macpherson [J-GA");
		senatorDet.add("Chambers, Henry H. [J-AL");
		senatorDet.add("Harrison, William H. [Adams-OH");
		senatorDet.add("Hendricks, William [Adams/AJ-IN");
		senatorDet.add("Kane, Elias K. [J-IL");
		senatorDet.add("Marks, William [Adams/AJ-PA");
		senatorDet.add("Rowan, John [J-KY");
		senatorDet.add("Willey, Calvin [Adams/AJ-CT");
		senatorDet.add("Woodbury, Levi [J-NH");
		senatorDet.add("Ellis, Powhatan [J-MS");
		senatorDet.add("White, Hugh Lawson [J/AJ/W-TN");
		senatorDet.add("Robbins, Asher [Adams/AJ/W-RI");
		senatorDet.add("Randolph, John [J-VA");
		senatorDet.add("Chambers, Ezekiel F. [Adams/AJ-MD");
		senatorDet.add("Reed, Thomas B. [J-MS");
		senatorDet.add("Pickens, Israel [J-AL");
		senatorDet.add("Harper, William [J-SC");
		senatorDet.add("Silsbee, Nathaniel [Adams/AJ-MA");
		senatorDet.add("Rodney, Daniel [Adams-DE");
		senatorDet.add("Bateman, Ephraim [Adams-NJ");
		senatorDet.add("McKinley, John [J-AL");
		senatorDet.add("Smith, William [R-SC");
		senatorDet.add("Ridgely, Henry M. [J-DE");
		senatorDet.add("Barnard, Isaac D. [J-PA");
		senatorDet.add("Ellis, Powhatan [J-MS");
		senatorDet.add("Foot, Samuel A. [Adams/AJ-CT");
		senatorDet.add("McLane, Louis [J-DE");
		senatorDet.add("Parris, Albion K. [J-ME");
		senatorDet.add("Tyler, John [J/AJ-VA");
		senatorDet.add("Webster, Daniel [Adams/AJ/W-MA");
		senatorDet.add("Prince, Oliver H. [J-GA");
		senatorDet.add("Burnet, Jacob [Adams/AJ-OH");
		senatorDet.add("Iredell, James [J-NC");
		senatorDet.add("Dudley, Charles E. [J-NY");
		senatorDet.add("Clayton, John M. [AJ-DE");
		senatorDet.add("Frelinghuysen, Theodore [AJ-NJ");
		senatorDet.add("Livingston, Edward [J-LA");
		senatorDet.add("McLean, John [J-IL");
		senatorDet.add("Sprague, Peleg [AJ-ME");
		senatorDet.add("Troup, George M. [J-GA");
		senatorDet.add("Grundy, Felix [J/D-TN");
		senatorDet.add("Forsyth, John [J-GA");
		senatorDet.add("Brown, Bedford [J/D-NC");
		senatorDet.add("Adams, Robert H. [J-MS");
		senatorDet.add("Naudain, Arnold [AJ-DE");
		senatorDet.add("Poindexter, George [J/AJ-MS");
		senatorDet.add("Baker, David J. [D-IL");
		senatorDet.add("Robinson, John M. [J/D-IL");
		senatorDet.add("Buckner, Alexander [J-MO");
		senatorDet.add("Ewing, Thomas [AJ-OH");
		senatorDet.add("Hill, Isaac [J-NH");
		senatorDet.add("Mangum, Willie P. [J/AJ-NC");
		senatorDet.add("Marcy, William L. [J-NY");
		senatorDet.add("Miller, Stephen D. [N-SC");
		senatorDet.add("Moore, Gabriel [J/AJ-AL");
		senatorDet.add("Prentiss, Samuel [AJ/W-VT");
		senatorDet.add("Tomlinson, Gideon [AJ-CT");
		senatorDet.add("Wilkins, William [J-PA");
		senatorDet.add("Hanna, Robert [AJ-IN");
		senatorDet.add("Clay, Henry [AJ/W-KY");
		senatorDet.add("Dallas, George M. [J-PA");
		senatorDet.add("Tipton, John [J/D-IN");
		senatorDet.add("Black, John [J/AJ/W-MS");
		senatorDet.add("Rives, William C. [J-VA");
		senatorDet.add("Calhoun, John C. [N/D-SC");
		senatorDet.add("Wright, Silas, Jr. [J/D-NY");
		senatorDet.add("Kent, Joseph [AJ/W-MD");
		senatorDet.add("Morris, Thomas [J/D-OH");
		senatorDet.add("Shepley, Ether [J-ME");
		senatorDet.add("Smith, Nathan [AJ-CT");
		senatorDet.add("Swift, Benjamin [AJ/W-VT");
		senatorDet.add("Tallmadge, Nathaniel P. [J/D/W-NY");
		senatorDet.add("Linn, Lewis F. [J/D-MO");
		senatorDet.add("King, John Pendleton [J/D-GA");
		senatorDet.add("Preston, William C. [N/W-SC");
		senatorDet.add("McKean, Samuel [J/D-PA");
		senatorDet.add("Porter, Alexander [AJ-LA");
		senatorDet.add("Leigh, Benjamin W. [AJ-VA");
		senatorDet.add("Buchanan, James [J/D-PA");
		senatorDet.add("Cuthbert, Alfred [J/D-GA");
		senatorDet.add("Ruggles, John [J/D-ME");
		senatorDet.add("Davis, John [AJ/W-MA");
		senatorDet.add("Hubbard, Henry [J/D-NH");
		senatorDet.add("Walker, Robert J. [J/D-MS");
		senatorDet.add("Wall, Garret D. [J/D/-NJ");
		senatorDet.add("Niles, John M. [J/D-CT");
		senatorDet.add("Ewing, William Lee D. [J-IL");
		senatorDet.add("Nicholas, Robert C. [J/D-LA");
		senatorDet.add("Rives, William C. [J/D-VA");
		senatorDet.add("Page, John [J-NH");
		senatorDet.add("Bayard, Richard H. [AJ/W-DE");
		senatorDet.add("Fulton, William S [J/D-AR");
		senatorDet.add("Sevier, Ambrose H. [J/D-AR");
		senatorDet.add("Strange, Robert [J/D-NC");
		senatorDet.add("Dana, Judah [J-ME");
		senatorDet.add("Parker, Richard E. [J/D-VA");
		senatorDet.add("Spence, John S. [AJ/W-MD");
		senatorDet.add("Mouton, Alexander [J/D-LA");
		senatorDet.add("Lyon, Lucius [J/D-MI");
		senatorDet.add("Norvell, Joh [J/D-MI");
		senatorDet.add("Allen, William [D-OH");
		senatorDet.add("McKinley, John [D-AL");
		senatorDet.add("Smith, Oliver H. [W-IN");
		senatorDet.add("Smith, Perry [D-CT");
		senatorDet.add("Williams, Reuel [D-ME");
		senatorDet.add("Young, Richard M. [D-IL");
		senatorDet.add("Roane, William H. [D-VA");
		senatorDet.add("Clay, Clement Comer [D-AL");
		senatorDet.add("Lumpkin, Wilson [D-GA");
		senatorDet.add("Merrick, William D. [W-MD");
		senatorDet.add("Trotter, James F. [D-MS");
		senatorDet.add("Foster, Ephraim H. [W-TN");
		senatorDet.add("Williams, Thomas Hickman [D-MS");
		senatorDet.add("Betts, Thaddeus [W-CT");
		senatorDet.add("Dixon, Nathan F. 1st, [W-RI");
		senatorDet.add("Henderson, John [W-MS");
		senatorDet.add("Phelps, Samuel S. [W-VT");
		senatorDet.add("Tappan, Benjamin [D-OH");
		senatorDet.add("White, Albert S. [W-IN");
		senatorDet.add("Grundy, Felix [D-TN");
		senatorDet.add("Sturgeon, Daniel [D-PA");
		senatorDet.add("Porter, Augustus S. [W-MI");
		senatorDet.add("Anderson, Alexander [D-TN");
		senatorDet.add("Huntington, Jabez W. [W-CT");
		senatorDet.add("Graham, William A. [W-NC");
		senatorDet.add("Mangum, Willie [W-NC");
		senatorDet.add("Nicholson, Alfred O.P. [D-TN");
		senatorDet.add("Kerr, John Leeds [W-MD");
		senatorDet.add("Bayard, Richard Henry [W-DE");
		senatorDet.add("Bates, Isaac C. [W-MA");
		senatorDet.add("Choate, Rufus [W-MA");
		senatorDet.add("Archer, William S. [W-VA");
		senatorDet.add("Barrow, Alexander [W-LA");
		senatorDet.add("Berrien, John Macpherso [W-GA");
		senatorDet.add("Evans, George [W-ME");
		senatorDet.add("McRoberts, Samuel [D-IL");
		senatorDet.add("Miller, Jacob W. [W-NJ");
		senatorDet.add("Morehead, James T. [W-KY");
		senatorDet.add("Simmons, James F. [W-RI");
		senatorDet.add("Woodbridge, William [W-MI");
		senatorDet.add("Bagby, Arthur [D-AL");
		senatorDet.add("Sprague, William [W-RI");
		senatorDet.add("Wilcox, Leonard [D-NH");
		senatorDet.add("Conrad, Charles M. [W-LA");
		senatorDet.add("Crafts, Samuel C. [W-VT");
		senatorDet.add("Dayton, William L. [W-NJ");
		senatorDet.add("McDuffie, George [D-SC");
		senatorDet.add("Atherton, Charles G. [D-NH");
		senatorDet.add("Breese, Sidney [D-IL");
		senatorDet.add("Colquitt, Walter T. [D-GA");
		senatorDet.add("Hannegan, Edward A. [D-IN");
		senatorDet.add("Haywood, William H., Jr. [D-NC");
		senatorDet.add("Huger, Daniel Elliott [D-SC");
		senatorDet.add("Niles, John M. [D-CT");
		senatorDet.add("Pearce, James A. [W/OP/D-MD");
		senatorDet.add("Upham, William [W-VT");
		senatorDet.add("Fairfield, John [D-ME");
		senatorDet.add("Semple, James [D-IL");
		senatorDet.add("Atchison, David R. [D-MO");
		senatorDet.add("Foster, Ephraim H. [W-TN");
		senatorDet.add("Jarnagin, Spencer [W-TN");
		senatorDet.add("Francis, John B. [LO-RI");
		senatorDet.add("Lewis, Dixon H. [D-AL");
		senatorDet.add("Ashley, Chester [D-AR");
		senatorDet.add("Dickinson, Daniel S. [D-NY");
		senatorDet.add("Foster, Henry A. [D-NY");
		senatorDet.add("Dix, John A. [D-NY");
		senatorDet.add("Bright, Jesse D. [D-IN");
		senatorDet.add("Cass, Lewis [D-MI");
		senatorDet.add("Corwin, Thomas [W-OH");
		senatorDet.add("Greene, Albert C. [W-RI");
		senatorDet.add("Johnson, Reverdy [W-MD");
		senatorDet.add("Speight, Jesse [D-MS");
		senatorDet.add("Turney, Hopkins L. [D-TN");
		senatorDet.add("Webster, Daniel [W-MA");
		senatorDet.add("Cameron, Simon [D-PA");
		senatorDet.add("Westcott, James D., Jr. [D-FL");
		senatorDet.add("Yulee, David Levy [D-FL");
		senatorDet.add("Chalmers, Joseph W. [D-MS");
		senatorDet.add("Berrien, John Macpherson [W-GA");
		senatorDet.add("Calhoun, John C. [D-SC");
		senatorDet.add("Jenness, Benning W. [D-NH");
		senatorDet.add("Pennybacker, Isaac S. [D-VA");
		senatorDet.add("Houston, Samuel [D/Am-TX");
		senatorDet.add("Rusk, Thomas J. [D-TX");
		senatorDet.add("Cilley, Joseph [L-NH");
		senatorDet.add("Badger, George E. [W-NC");
		senatorDet.add("Butler, Andrew P. [D-SC");
		senatorDet.add("Soule, Pierre [D-LA");
		senatorDet.add("Mason, James M. [D-VA");
		senatorDet.add("Bradbury, James W. [D-ME");
		senatorDet.add("Clarke, John H. [W-RI");
		senatorDet.add("Douglas, Stephen A. [D-IL");
		senatorDet.add("Downs, Solomon W. [D-LA");
		senatorDet.add("Felch, Alpheus [D-MI");
		senatorDet.add("Foote, Henry Stuart [D-MS");
		senatorDet.add("Hale, John P. [ID/FS-NH");
		senatorDet.add("Hunter, Robert M.T. [D-VA");
		senatorDet.add("Spruance, Presley [W-DE");
		senatorDet.add("Underwood, Joseph R. [W-KY");
		senatorDet.add("Davis, Jefferson [D-MS");
		senatorDet.add("Baldwin, Roger S. [W-CT");
		senatorDet.add("Bell, John [W/OP/Am-TN");
		senatorDet.add("Moor, Wyman B.S. [D-ME");
		senatorDet.add("Johnson, Herschel V. [D-GA");
		senatorDet.add("Borland, Solon [D-AR");
		senatorDet.add("Sebastian, William K. [D-AR");
		senatorDet.add("Hamlin, Hannibal [D/R-ME");
		senatorDet.add("Dodge, Henry [D-WI");
		senatorDet.add("Walker, Isaac P. [D-WI");
		senatorDet.add("Fitzgerald, Thomas [D-MI");
		senatorDet.add("Metcalfe, Thomas [W-KY");
		senatorDet.add("King, William R. [D-AL");
		senatorDet.add("Fitzpatrick, Benjamin [D-AL");
		senatorDet.add("Dodge, Augustus C. [D-IA");
		senatorDet.add("Jones, George W. [D-IA");
		senatorDet.add("Wales, John [W-DE");
		senatorDet.add("Chase, Salmon P. [FS-OH");
		senatorDet.add("Cooper, James [W-PA");
		senatorDet.add("Dawson, William C. [W-GA");
		senatorDet.add("Morton, Jackson [W-FL");
		senatorDet.add("Norris, Moses, Jr. [D-NH");
		senatorDet.add("Seward, William H. [W/OP/R-NY");
		senatorDet.add("Smith, Truman [W-CT");
		senatorDet.add("Whitcomb, James [D-IN");
		senatorDet.add("Shields, James [D-IL");
		senatorDet.add("Clemens, Jeremiah [D-AL");
		senatorDet.add("Stewart, David [W-MD");
		senatorDet.add("Pratt, Thomas G. [W/OP-MD");
		senatorDet.add("Barnwell, Robert W. [D-SC");
		senatorDet.add("Winthrop, Robert C. [W-MA");
		senatorDet.add("Fremont, John C. [D-CA");
		senatorDet.add("Gwin, William M. [D-CA");
		senatorDet.add("Rhett, Robert Barnwell [D-SC");
		senatorDet.add("Rantoul, Robert, Jr. [D-MA");
		senatorDet.add("Bayard, James Asheton, Jr. [D-DE");
		senatorDet.add("Brodhead, Richard [D-PA");
		senatorDet.add("Geyer, Henry S. [W/OP-MO");
		senatorDet.add("Fish, Hamilton [W/OP-NY");
		senatorDet.add("Foot, Solomon [W/OP/R-VT");
		senatorDet.add("James, Charles T. [D-RI");
		senatorDet.add("Jones, James C. [W/OP-TN");
		senatorDet.add("Mallory, Stephen R. [D-FL");
		senatorDet.add("Stockton, Robert F. [D-NJ");
		senatorDet.add("Wade, Benjamin F. [W/OP/R-OH");
		senatorDet.add("Sumner, Charles [FS/OP/R/LR-MA");
		senatorDet.add("McRae, John J. [D-MS");
		senatorDet.add("Weller, John B. [D-CA");
		senatorDet.add("Brooke, Walker [W-MS");
		senatorDet.add("Adams, Stephen [D-MS");
		senatorDet.add("De Saussure, William F. [D-SC");
		senatorDet.add("Toucey, Isaac [D-CT");
		senatorDet.add("Charlton, Robert M. [D-GA");
		senatorDet.add("Meriwether, David [D-KY");
		senatorDet.add("Dixon, Archibald [W-KY");
		senatorDet.add("Cathcart, Charles W. [D-IN");
		senatorDet.add("Pettit, John [D-IN");
		senatorDet.add("Fitzpatrick, Benjamin [D-AL");
		senatorDet.add("Allen, Philip [D-RI");
		senatorDet.add("Benjamin, Judah P. [W/OP/D-LA");
		senatorDet.add("Clay, Clement Claiborne, Jr. [D-AL");
		senatorDet.add("Evans, Josiah J. [D-SC");
		senatorDet.add("Everett, Edward [W-MA");
		senatorDet.add("Stuart, Charles E. [D-MI");
		senatorDet.add("Thompson, John B. [W/OP/Am-KY");
		senatorDet.add("Thomson, John R. [D-NJ");
		senatorDet.add("Toombs, Robert [W/D-GA");
		senatorDet.add("Wright, William [D-NJ");
		senatorDet.add("Slidell, John [D-LA");
		senatorDet.add("Johnson, Robert W. [D-AR");
		senatorDet.add("Williams, Jared W. [D-NH");
		senatorDet.add("Brown, Albert G. [D-MS");
		senatorDet.add("Fessenden, William Pitt [W/OP/R-ME");
		senatorDet.add("Gillette, Francis [FS-CT");
		senatorDet.add("Rockwell, Julius [W-MA");
		senatorDet.add("Brainerd, Lawrence [FS-VT");
		senatorDet.add("Reid, David S. [D-NC");
		senatorDet.add("Wells, John S. [D-NH");
		senatorDet.add("Wilson, Henry [Am/OP/R-MA");
		senatorDet.add("Biggs, Asa [D-NC");
		senatorDet.add("Collamer, Jacob [OP/R-VT");
		senatorDet.add("Durkee, Charles [OP/R-WI");
		senatorDet.add("Foster, Lafayette S. [OP/R-CT");
		senatorDet.add("Iverson, Alfred, Sr. [D-GA");
		senatorDet.add("Pugh, George E. [D-OH");
		senatorDet.add("Trumbull, Lyman [D/R-IL");
		senatorDet.add("Yulee, David L. [D-FL");
		senatorDet.add("Bell, James [OP/R-NH");
		senatorDet.add("Harlan, James [OP-IA");
		senatorDet.add("Bigler, William [D-PA");
		senatorDet.add("Comegys, Joseph P. [OP-DE");
		senatorDet.add("Green, James S. [D-MO");
		senatorDet.add("Bates, Martin W. [D-DE");
		senatorDet.add("Nourse, Amos [R-ME");
		senatorDet.add("Harlan, James [R-IA");
		senatorDet.add("Fitch, Graham N. [D-IN");
		senatorDet.add("Broderick, David C. [D-CA");
		senatorDet.add("Chandler, Zachariah [R-MI");
		senatorDet.add("Dixon, James [R-CT");
		senatorDet.add("Doolittle, James R. [R-WI");
		senatorDet.add("King, Preston [R-NY");
		senatorDet.add("Polk, Trusten [D-MO");
		senatorDet.add("Kennedy, Anthony [Am/U-MD");
		senatorDet.add("Clark, Daniel [R-NH");
		senatorDet.add("Johnson, Andrew [D-TN");
		senatorDet.add("Henderson, J. Pinckney [D-TX");
		senatorDet.add("Hammond, James H. [D-SC");
		senatorDet.add("Clingman, Thomas L. [D-NC");
		senatorDet.add("Hayne, Arthur P. [D-SC");
		senatorDet.add("Rice, Henry M. [D-MN");
		senatorDet.add("Ward, Matthias [D-TX");
		senatorDet.add("Chesnut, James Jr. [D-SC");
		senatorDet.add("Lane, Joseph [D-OR");
		senatorDet.add("Smith, Delazon [D-OR");
		senatorDet.add("Anthony, Henry B. [R-RI");
		senatorDet.add("Bingham, Kinsley S. [R-MI");
		senatorDet.add("Bragg, Thomas [D-NC");
		senatorDet.add("Hemphill, John [D-TX");
		senatorDet.add("Grimes, James W. [R-IA");
		senatorDet.add("Nicholson, Alfred O.P. [D-TN");
		senatorDet.add("Powell, Lazarus W. [D-KY");
		senatorDet.add("Saulsbury, Willard, Sr. [D-DE");
		senatorDet.add("Ten Eyck, John C. [R-NJ");
		senatorDet.add("Wilkinson, Morton S. [R-MN");
		senatorDet.add("Haun, Henry P. [D-CA");
		senatorDet.add("Wigfall, Louis T. [D-TX");
		senatorDet.add("Latham, Milton S. [D-CA");
		senatorDet.add("Baker, Edward D. [R-OR");
		senatorDet.add("Morrill, Lot Myrick [R-ME");
		senatorDet.add("Breckinridge, John C. [D-KY");
		senatorDet.add("Cowan, Edgar [R-PA");
		senatorDet.add("Harris, Ira [R-NY");
		senatorDet.add("Howe, Timothy O. [R-WI");
		senatorDet.add("Lane, Henry S. [R-IN");
		senatorDet.add("McDougall, James A. [D-CA");
		senatorDet.add("Mitchel, Charles B. [D-AR");
		senatorDet.add("Nesmith, James W. [D-OR");
		senatorDet.add("Stark, Benjamin [D-OR");
		senatorDet.add("Wilmot, David [R-PA");
		senatorDet.add("Johnson, Waldo P. [D-MO");
		senatorDet.add("Sherman, John [R-OH");
		senatorDet.add("Lane, James H. [R-KS");
		senatorDet.add("Pomeroy, Samuel C. [R-KS");
		senatorDet.add("Browning, Orville H. [R-IL");
		senatorDet.add("Willey, Waitman T. [UU-VA");
		senatorDet.add("Carlile, John S. [U-VA");
		senatorDet.add("Davis, Garrett [U/D-KY");
		senatorDet.add("Howard, Jacob M. [R-MI");
		senatorDet.add("Henderson, John B. [U/UU/R-MO");
		senatorDet.add("Wilson, Robert [U-MO");
		senatorDet.add("Wright, Joseph A. [U-IN");
		senatorDet.add("Arnold, Samuel G. [R-RI");
		senatorDet.add("Harding, Benjamin F. [D-OR");
		senatorDet.add("Field, Richard S. [R-NJ");
		senatorDet.add("Hicks, Thomas H. [U/UU-MD");
		senatorDet.add("Richardson, William A. [D-IL");
		senatorDet.add("Turpie, David [D-IN");
		senatorDet.add("Wall, James W. [D-NJ");
		senatorDet.add("Bowden, Lemuel J. [U-VA");
		senatorDet.add("Buckalew, Charles R. [D-PA");
		senatorDet.add("Conness, John [R-CA");
		senatorDet.add("Hendricks, Thomas A. [D-IN");
		senatorDet.add("Morgan, Edwin D. [R-NY");
		senatorDet.add("Ramsey, Alexander [R-MN");
		senatorDet.add("Sprague, William 2 [R/LR-RI");
		senatorDet.add("Van Winkle, Peter G. [UU/R-WV");
		senatorDet.add("Brown, B. Gratz [UU/R-MO");
		senatorDet.add("Riddle, George Read [D-DE");
		senatorDet.add("Farwell, Nathan A. [R-ME");
		senatorDet.add("Stewart, William M. [R-NV");
		senatorDet.add("Nye, James W. [R-NV");
		senatorDet.add("Cragin, Aaron H. [R-NH");
		senatorDet.add("Guthrie, James [D-KY");
		senatorDet.add("Norton, Daniel S. [R/D-MN");
		senatorDet.add("Poland, Luke P. [R-VT");
		senatorDet.add("Williams, George Henry [R-OR");
		senatorDet.add("Yates, Richard [R-IL");
		senatorDet.add("Creswell, John A.J. [UU-MD");
		senatorDet.add("Stockton, John P. [D-NJ");
		senatorDet.add("Kirkwood, Samuel J. [R-IA");
		senatorDet.add("Edmunds, George F. [R-VT");
		senatorDet.add("Ross, Edmund G. [R-KS");
		senatorDet.add("Fowler, Joseph S. [UU/R-TN");
		senatorDet.add("Patterson, David T. [U/D-TN");
		senatorDet.add("Fogg, George G. [R-NH");
		senatorDet.add("Cattell, Alexander G. [R-NJ");
		senatorDet.add("Frelinghuysen, Frederick T. [R-NJ");
		senatorDet.add("Thayer, John M. [R-NE");
		senatorDet.add("Tipton, Thomas [R/LR-NE");
		senatorDet.add("Cole, Cornelius [R-CA");
		senatorDet.add("Conkling, Roscoe [R-NY");
		senatorDet.add("Corbett, Henry W. [R-OR");
		senatorDet.add("Drake, Charles D. [R-MO");
		senatorDet.add("Ferry, Orris S. [R/LR/R-CT");
		senatorDet.add("Morrill, Justin S. [R-VT");
		senatorDet.add("Morton, Oliver H.P.T. [R-IN");
		senatorDet.add("Patterson, James W. [R-NH");
		senatorDet.add("McCreery, Thomas C. [D-KY");
		senatorDet.add("Vickers, George [D-MD");
		senatorDet.add("McDonald, Alexander [R-AR");
		senatorDet.add("Rice, Benjamin F. [R-AR");
		senatorDet.add("Osborn, Thomas W. [R-FL");
		senatorDet.add("Welch, Adonijah S. [R-FL");
		senatorDet.add("Harris, John S. [R-LA");
		senatorDet.add("Kellogg, William P. [R-LA");
		senatorDet.add("Whyte, William Pinkney [D-MD");
		senatorDet.add("Abbott, Joseph C. [R-NC");
		senatorDet.add("Pool, John [R-NC");
		senatorDet.add("Robertson, Thomas J. [R-SC");
		senatorDet.add("Sawyer, Frederick A. [R-SC");
		senatorDet.add("Spencer, George E. [R-AL");
		senatorDet.add("Warner, Willard [R-AL");
		senatorDet.add("Bayard, Thomas F., Sr. [D-DE");
		senatorDet.add("Boreman, Arthur [R-WV");
		senatorDet.add("Brownlow, William G. [R-TN");
		senatorDet.add("Buckingham William A. [R-CT");
		senatorDet.add("Carpenter, Matthew H. [R-WI");
		senatorDet.add("Casserly, Eugene [D-CA");
		senatorDet.add("Fenton, Reuben E. [R/LR-NY");
		senatorDet.add("Gilbert, Abijah [R-FL");
		senatorDet.add("Hamilton, William T. [D-MD");
		senatorDet.add("Pratt, Daniel D. [R-IN");
		senatorDet.add("Schurz, Carl [R/LR-MO");
		senatorDet.add("Scott, John [R-PA");
		senatorDet.add("Thurman, Allen G. [D-OH");
		senatorDet.add("Howell, James B. [R-IA");
		senatorDet.add("Johnston, John W. [D-VA");
		senatorDet.add("Lewis, John F. [R-VA");
		senatorDet.add("Ames, Adelbert [R-MS");
		senatorDet.add("Revels, Hiram R. [R-MS");
		senatorDet.add("Flanagan, J. W. [R-TX");
		senatorDet.add("Hamilton, Morgan C. [R/LR/R-TX");
		senatorDet.add("Windom, William [R-MN");
		senatorDet.add("Jewett, Daniel T. [D-MO");
		senatorDet.add("Blair, Francis P. [D-MO");
		senatorDet.add("Stearns, Ozora P. [R-MN");
		senatorDet.add("Hill, Joshua [R-GA");
		senatorDet.add("Miller, Homer V. M. [D-GA");
		senatorDet.add("Caldwell, Alexander [R-KS");
		senatorDet.add("Cooper, Henry [D-TN");
		senatorDet.add("Davis, Henry G. [D-WV");
		senatorDet.add("Ferry, Thomas W. [R-MI");
		senatorDet.add("Frelinghuysen, Frederick T. [R-NJ");
		senatorDet.add("Goldthwaite, George [D-AL");
		senatorDet.add("Hitchcock, Phineas W. [R-NE");
		senatorDet.add("Kelly, James K. [D-OR");
		senatorDet.add("Logan, John A. [R-IL");
		senatorDet.add("Saulsbury, Eli [D-DE");
		senatorDet.add("Stevenson, John W. [D-KY");
		senatorDet.add("West, J. Rodman [R-LA");
		senatorDet.add("Wright, George G. [R-IA");
		senatorDet.add("Clayton, Powell [R-AR");
		senatorDet.add("Norwood, Thomas M. [D-GA");
		senatorDet.add("Alcorn, James L. [R-MS");
		senatorDet.add("Ransom, Matt W. [D-NC");
		senatorDet.add("Machen, Willis B. [D-KY");
		senatorDet.add("Allison, William B. [R-IA");
		senatorDet.add("Bogy, Lewis V. [D-MO");
		senatorDet.add("Conover, Simon B. [R-FL");
		senatorDet.add("Dennis, George R. [D-MD");
		senatorDet.add("Dorsey, Stephen W. [R-AR");
		senatorDet.add("Gordon, John B. [D-GA");
		senatorDet.add("Ingalls, John J. [R-KS");
		senatorDet.add("Jones, John P. [R/S/R-NV");
		senatorDet.add("Merrimon, Augustus S. [D-NC");
		senatorDet.add("Mitchell, John H. [R-OR");
		senatorDet.add("Oglesby, Richard J. [R-IL");
		senatorDet.add("Patterson, John J. [R-SC");
		senatorDet.add("Sargent, Aaron A. [R-CA");
		senatorDet.add("Wadleigh, Bainbridge [R-NH");
		senatorDet.add("Boutwell, George S. [R-MA");
		senatorDet.add("Crozier, Robert [R-KS");
		senatorDet.add("Hager, John S. [D-CA");
		senatorDet.add("Pease, Henry R. [R-MS");
		senatorDet.add("Harvey, James M. [R-KS");
		senatorDet.add("Washburn, William B. [R-MA");
		senatorDet.add("Eaton, William W. [D-CT");
		senatorDet.add("Booth, Newton [IR/R-CA");
		senatorDet.add("Bruce, Blanche K. [R-MS");
		senatorDet.add("Burnside, Ambrose [R-RI");
		senatorDet.add("Cameron, Angus [R-WI");
		senatorDet.add("Caperton, Allen T. [D-WV");
		senatorDet.add("Christiancy, Isaac P. [R-MI");
		senatorDet.add("Cockrell, Francis M. [D-MO");
		senatorDet.add("Dawes, Henry L. [R-MA");
		senatorDet.add("Jones, Charles W. [D-FL");
		senatorDet.add("Kernan, Francis [D-NY");
		senatorDet.add("Maxey, Samuel B. [D-TX");
		senatorDet.add("McDonald, Joseph E. [D-IN");
		senatorDet.add("McMillan, Samuel J.R. [R-MN");
		senatorDet.add("Paddock, Algernon S. [R-NE");
		senatorDet.add("Randolph, Theodore F. [D-NJ");
		senatorDet.add("Sharon, William [R-NV");
		senatorDet.add("Wallace, William A. [D-PA");
		senatorDet.add("Withers, Robert E. [D-VA");
		senatorDet.add("Key, David M. [D-TN");
		senatorDet.add("English, James E. [D-CT");
		senatorDet.add("Eustis, James B. [D-LA");
		senatorDet.add("Barnum, William H. [D-CT");
		senatorDet.add("Blaine, James G. [R-ME");
		senatorDet.add("Price, Samuel [D-WV");
		senatorDet.add("Teller, Henry M. [R-CO");
		senatorDet.add("Chaffee, Jerome B. [R-CO");
		senatorDet.add("Bailey, James E. [D-TN");
		senatorDet.add("Beck, James B. [D-KY");
		senatorDet.add("Butler, Mathew C. [D-SC");
		senatorDet.add("Coke, Richard [D-TX");
		senatorDet.add("Davis, David [I-IL");
		senatorDet.add("Garland, Augustus H. [D-AR");
		senatorDet.add("Grover, La Fayette [D-OR");
		senatorDet.add("Harris, Isham G. [D-TN");
		senatorDet.add("Hill, Benjamin H. [D-GA");
		senatorDet.add("Hoar, George F. [R-MA");
		senatorDet.add("Lamar, Lucius Q.C. [D-MS");
		senatorDet.add("McPherson, John R. [D-NJ");
		senatorDet.add("Morgan, John T. [D-AL");
		senatorDet.add("Plumb, Preston B. [R-KS");
		senatorDet.add("Rollins, Edward H. [R-NH");
		senatorDet.add("Cameron, James Donald [R-PA");
		senatorDet.add("Matthews, Stanley [R-OH");
		senatorDet.add("Saunders, Alvin [R-NE");
		senatorDet.add("Armstrong, David H. [D-MO");
		senatorDet.add("Voorhees, Daniel W. [D-IN");
		senatorDet.add("Call, Wilkinson [D-FL");
		senatorDet.add("Farley, James T. [D-CA");
		senatorDet.add("Groome, James B. [D-MD");
		senatorDet.add("Hampton, Wade [D-SC");
		senatorDet.add("Hill, Nathaniel P. [R-CO");
		senatorDet.add("Houston, George S. [D-AL");
		senatorDet.add("Jonas, Benjamin F. [D-LA");
		senatorDet.add("Pendleton, George H. [D-OH");
		senatorDet.add("Platt, Orville H. [R-CT");
		senatorDet.add("Slater, James H. [D-OR");
		senatorDet.add("Vance, Zebulon [D-NC");
		senatorDet.add("Vest, George G. [D-MO");
		senatorDet.add("Walker, James D. [D-AR");
		senatorDet.add("Williams, John Stuart [D-KY");
		senatorDet.add("Bell, Charles H. [R-NH");
		senatorDet.add("Blair, Henry W. [R-NH");
		senatorDet.add("Baldwin, Henry P. [R-MI");
		senatorDet.add("Pryor, Luke [D-AL");
		senatorDet.add("Brown, Joseph E. [D-GA");
		senatorDet.add("Pugh, James L. [D-AL");
		senatorDet.add("MCamden, Johnson N. [D-WV");
		senatorDet.add("Conger, Omar D. [R-MI");
		senatorDet.add("Fair, James G. [D-NV");
		senatorDet.add("George, James Z. [D-MS");
		senatorDet.add("Gorman, Arthur P. [D-MD");
		senatorDet.add("Hale, Eugene [R-ME");
		senatorDet.add("Harrison, Benjamin [R-IN");
		senatorDet.add("Hawley, Joseph R. [R-CT");
		senatorDet.add("Jackson, Howell E. [D-TN");
		senatorDet.add("Mahone, William [RA/R-VA");
		senatorDet.add("Miller, John F. [R-CA");
		senatorDet.add("Mitchell, John I. [R-PA");
		senatorDet.add("Platt, Thomas C. [R-NY");
		senatorDet.add("Sawyer, Philetus [R-WI");
		senatorDet.add("Sewell, William J. [R-NJ");
		senatorDet.add("Van Wyck, Charles H. [R-NE");
		senatorDet.add("McDill, James W. [R-IA");
		senatorDet.add("Edgerton, A.J. [R-MN");
		senatorDet.add("Frye, William P. [R-ME");
		senatorDet.add("Miller, Warner [R-NY");
		senatorDet.add("Lapham, Elbridge G. [R-NY");
		senatorDet.add("Aldrich, Nelson W. [R-RI");
		senatorDet.add("Chilcott, George M. [R-CO");
		senatorDet.add("Barrow, Pope [D-GA");
		senatorDet.add("Tabor, Horace A.W. [R-CO");
		senatorDet.add("Bowen, Thomas M. [R-CO");
		senatorDet.add("Cullom, Shelby M. [R-IL");
		senatorDet.add("Colquitt, Alfred H. [D-GA");
		senatorDet.add("Dolph, Joseph N. [R-OR");
		senatorDet.add("Gibson, Randall L. [D-LA");
		senatorDet.add("Kenna, John E. [D-WV");
		senatorDet.add("Manderson, Charles F. [R-NE");
		senatorDet.add("Palmer, Thomas W. [R-MI");
		senatorDet.add("Pike, Austin F. [R-NH");
		senatorDet.add("Riddleberger, Harrison H. [RA/R-VA");
		senatorDet.add("Sabin, Dwight M. [R-MN");
		senatorDet.add("Wilson, James F. [R-IA");
		senatorDet.add("Sheffield, William P. [R-RI");
		senatorDet.add("Chace, Jonathan [R-RI");
		senatorDet.add("Blackburn, Joseph C.S. [D-KY");
		senatorDet.add("Evarts, William M. [R-NY");
		senatorDet.add("Jones, James K. [D-AR");
		senatorDet.add("Payne, Henry B. [D-OH");
		senatorDet.add("Spooner, John Coit [R-WI");
		senatorDet.add("Stanford, Leland [R-CA");
		senatorDet.add("Teller, Henry M. [R/SR/D-CO");
		senatorDet.add("Wilson, Ephraim King [D-MD");
		senatorDet.add("Walthall, Edward C. [D-MS");
		senatorDet.add("Gray, George [D-DE");
		senatorDet.add("Berry, James H. [D-AR");
		senatorDet.add("Mitchell, John H. [R-OR");
		senatorDet.add("Hearst, George [D-CA");
		senatorDet.add("Whitthorne, Washington C. [D-TN");
		senatorDet.add("Williams, Abram P. [R-CA");
		senatorDet.add("Cheney, Person C. [R-NH");
		senatorDet.add("Farwell, Charles B. [R-IL");
		senatorDet.add("Bate, William B. [D-TN");
		senatorDet.add("Blodgett, Rufus [D-NJ");
		senatorDet.add("Daniel, John W. [D-VA");
		senatorDet.add("Davis, Cushman K. [R-MN");
		senatorDet.add("Faulkner, Charles J. [D-WV");
		senatorDet.add("Quay, Matthew S. [R-PA");
		senatorDet.add("Reagan, John H. [D-TX");
		senatorDet.add("Stewart, William M. [R/S/R-NV");
		senatorDet.add("Stockbridge, Francis B. [R-MI");
		senatorDet.add("Pasco, Samuel [D-FL");
		senatorDet.add("Chandler, William E. [R-NH");
		senatorDet.add("Barbour, John S., Jr. [D-VA");
		senatorDet.add("Higgins, Anthony [R-DE");
		senatorDet.add("Marston, Gilman [R-NH");
		senatorDet.add("McMillan, James [R-MI");
		senatorDet.add("Washburn, William D. [R-MN");
		senatorDet.add("Wolcott, Edward O. [R-CO");
		senatorDet.add("Dixon, Nathan F. [R-RI");
		senatorDet.add("Moody, Gideon C. [R-SD");
		senatorDet.add("Pettigrew, Richard F. [R/SR-SD");
		senatorDet.add("Allen, John B. [R-WA");
		senatorDet.add("Squire, Watson C. [R-WA");
		senatorDet.add("Pierce, Gilbert A. [R-ND");
		senatorDet.add("Casey, Lyman R. [R-ND");
		senatorDet.add("Sanders, Wilbur F. [R-MT");
		senatorDet.add("Power, Thomas C. [R-MT");
		senatorDet.add("Carlisle, John G. [D-KY");
		senatorDet.add("Carey, Joseph M. [R-WY");
		senatorDet.add("Warren, Francis E. [R-WY");
		senatorDet.add("McConnell, William J. [R-ID");
		senatorDet.add("Shoup, George L. [R-ID");
		senatorDet.add("Brice, Calvin S. [D-OH");
		senatorDet.add("Dubois, Fred T. [R-ID");
		senatorDet.add("Gallinger, Jacob H. [R-NH");
		senatorDet.add("Hansbrough, Henry C. [R-ND");
		senatorDet.add("Irby, John L.M. [D-SC");
		senatorDet.add("Kyle, James H. [PO/R-SD");
		senatorDet.add("Palmer, John M. [D-IL");
		senatorDet.add("Peffer, William A. [FA-KS");
		senatorDet.add("Vilas, William F. [D-WI");
		senatorDet.add("White, Edward D. [D-LA");
		senatorDet.add("Felton, Charles N. [R-CA");
		senatorDet.add("Chilton, Horace [D-TX");
		senatorDet.add("Proctor, Redfield [R-VT");
		senatorDet.add("Gibson, Charles H. [D-MD");
		senatorDet.add("Perkins, Bishop W. [R-KS");
		senatorDet.add("Hill, David B. [D-NY");
		senatorDet.add("Mills, Roger Q. [D-TX");
		senatorDet.add("Hunton, Eppa [D-VA");
		senatorDet.add("Caffery, Donelson [D-LA");
		senatorDet.add("Camden, Johnson N. [D-WV");
		senatorDet.add("Lindsay, William [D-KY");
		senatorDet.add("Roach, William N. [D-ND");
		senatorDet.add("White, Stephen M. [D-CA");
		senatorDet.add("Allen, William V. [PO-NE");
		senatorDet.add("Lodge, Henry Cabot [R-MA");
		senatorDet.add("Martin, John [D-KS");
		senatorDet.add("Mitchell, John L. [D-WI");
		senatorDet.add("Murphy, Edward, Jr. [D-NY");
		senatorDet.add("Smith, James, Jr. [D-NJ");
		senatorDet.add("Perkins, George C. [R-CA");
		senatorDet.add("McLaurin, Anselm J. [D-MS");
		senatorDet.add("Blanchard, Newton [D-LA");
		senatorDet.add("Walsh, Patrick [D-GA");
		senatorDet.add("Jarvis, Thomas J. [D-NC");
		senatorDet.add("Patton, John, Jr. [R-MI");
		senatorDet.add("Mantle, Lee [R/SR-MT");
		senatorDet.add("Burrows, Julius C. [R-MI");
		senatorDet.add("Pritchard, Jeter C. [R-NC");
		senatorDet.add("Clark, Clarence D. [R-WY");
		senatorDet.add("Wilson, John L. [R-WA");
		senatorDet.add("Bacon, Augustus O. [D-GA");
		senatorDet.add("Baker, Lucien [R-KS");
		senatorDet.add("Butler, Marion [PO-NC");
		senatorDet.add("Carter, Thomas H. [R-MT");
		senatorDet.add("Elkins, Stephen B. [R-WV");
		senatorDet.add("Gear, John H. [R-IA");
		senatorDet.add("Martin, Thomas S. [D-VA");
		senatorDet.add("McBride, George W. [R-OR");
		senatorDet.add("Nelson, Knute [R-MN");
		senatorDet.add("Thurston, John M. [R-NE");
		senatorDet.add("Tillman, Benjamin R. [D-SC");
		senatorDet.add("Warren, Francis E. [R-WY");
		senatorDet.add("Wetmore, George P. [R-RI");
		senatorDet.add("Brown, Arthur [R-UT");
		senatorDet.add("Kenney, Richard R. [D-DE");
		senatorDet.add("Clay, Alexander S. [D-GA");
		senatorDet.add("Deboe, William J. [R-KY");
		senatorDet.add("Earle, Joseph H. [D-SC");
		senatorDet.add("Fairbanks, Charles W. [R-IN");
		senatorDet.add("Foraker, Joseph B. [R-OH");
		senatorDet.add("Harris, William A. [PO-KS");
		senatorDet.add("Heitfeld, Henry [PO/D-ID");
		senatorDet.add("Mason, William E. [R-IL");
		senatorDet.add("McEnery, Samuel D. [D-LA");
		senatorDet.add("Penrose, Boies [R-PA");
		senatorDet.add("Pettus, Edmund W. [D-AL");
		senatorDet.add("Rawlins, Joseph L. [D-UT");
		senatorDet.add("Spooner, John C. [R-WI");
		senatorDet.add("Turner, Georg [SR/D-WA");
		senatorDet.add("Wellington, George L. [R-MD");
		senatorDet.add("Hanna, Marcus A. [R-OH");
		senatorDet.add("Mallory, Stephen [D-FL");
		senatorDet.add("McLaurin, John L. [D-SC");
		senatorDet.add("Turley, Thomas B. [D-TN");
		senatorDet.add("Money, Hernando D. [D-MS");
		senatorDet.add("Sullivan, William Van Amberg [D-MS");
		senatorDet.add("Simon, Joseph [R-OR");
		senatorDet.add("Ross, Jonathan [R-VT");
		senatorDet.add("Beveridge, Albert J. [R-IN");
		senatorDet.add("Clark, William A. [D-MT");
		senatorDet.add("Culberson, Charles A. [D-TX");
		senatorDet.add("Depew, Chauncey M. [R-NY");
		senatorDet.add("Foster, Addison G. [R-WA");
		senatorDet.add("Kean, John [R-NJ");
		senatorDet.add("McComas, Louis E. [R-MD");
		senatorDet.add("McCumber, Porter J. [R-ND");
		senatorDet.add("Quarles, Joseph V. [R-WI");
		senatorDet.add("Scott, Nathan B. [R-WV");
		senatorDet.add("Hayward, Monroe L. [R-NE)");
		senatorDet.add("Taliaferro, James P. [D-FL");
		senatorDet.add("Allen, William V. [PO-NE");
		senatorDet.add("Bard, Thomas R. [R-CA");
		senatorDet.add("Dolliver, Jonathan P. [R-IA");
		senatorDet.add("Dillingham, William P. [R-VT");
		senatorDet.add("Towne, Charles A. [D-MN");
		senatorDet.add("Kearns, Thomas [R-UT");
		senatorDet.add("Clapp, Moses E. [R-MN");
		senatorDet.add("Bailey, Joseph W. [D-TX");
		senatorDet.add("Burnham, Henry E. [R-NH");
		senatorDet.add("Burton, Joseph R. [R-KS");
		senatorDet.add("Carmack, Edward W. [D-TN");
		senatorDet.add("Foster, Murphy J. [D-LA");
		senatorDet.add("Gamble, Robert J. [R-SD");
		senatorDet.add("Patterson, Thomas M. [D-CO");
		senatorDet.add("Simmons, Furnifold M. [D-NC");
		senatorDet.add("Gibson, Paris [D-MT");
		senatorDet.add("Dietrich, Charles H. [R-NE");
		senatorDet.add("Millard, Joseph H. [R-NE");
		senatorDet.add("Kittredge, Alfred B. [R-SD");
		senatorDet.add("Dryden, John F. [R-NJ");
		senatorDet.add("Alger, Russell A. [R-MI");
		senatorDet.add("Ball, L. Heisler [R-DE");
		senatorDet.add("Ankeny, Levi [R-WA");
		senatorDet.add("Clarke, James P. [D-AR");
		senatorDet.add("Fulton, Charles W. [R-OR");
		senatorDet.add("Heyburn, Weldon B. [R-ID");
		senatorDet.add("Hopkins, Albert J. [R-IL");
		senatorDet.add("Latimer, Asbury C. [D-SC");
		senatorDet.add("Long, Chester I. [R-KS");
		senatorDet.add("McCreary, James B. [D-KY");
		senatorDet.add("Newlands, Francis G. [D-NV");
		senatorDet.add("Overman, Lee S. [D-NC");
		senatorDet.add("Smoot, Reed [R-UT");
		senatorDet.add("Stone, William J. [D-MO");
		senatorDet.add("Dick, Charles W.F. [R-OH");
		senatorDet.add("Knox, Philander C. [R-PA");
		senatorDet.add("Crane, Winthrop Murray [R-MA");
		senatorDet.add("Bulkeley, Morgan G. [R-CT");
		senatorDet.add("Burkett, Elmer J. [R-NE");
		senatorDet.add("Hemenway, James A. [R-IN");
		senatorDet.add("Nixon, George S. [R-NV");
		senatorDet.add("Piles, Samuel H. [R-WA");
		senatorDet.add("Rayner, Isidor [D-MD");
		senatorDet.add("Sutherland, George [R-UT");
		senatorDet.add("Warner, William [R-MO");
		senatorDet.add("Frazier, James B. [D-TN");
		senatorDet.add("Gearin, John M. [D-OR");
		senatorDet.add("La Follette, Robert M. [R-WI");
		senatorDet.add("Benson, Alfred W. [R-KS");
		senatorDet.add("du Pont, Henry A. [R-DE");
		senatorDet.add("Mulkey, Frederick W. [R-OR");
		senatorDet.add("Curtis, Charles [R-KS");
		senatorDet.add("Smith, William Alden [R-MI");
		senatorDet.add("Borah, William E. [R-ID");
		senatorDet.add("Bourne, Jonathan, Jr. [R-OR");
		senatorDet.add("Brown, Norris [R-NE");
		senatorDet.add("Davis, Jeff [D-AR");
		senatorDet.add("Dixon, Joseph M. [R-MT");
		senatorDet.add("Guggenheim, Simon [R-CO");
		senatorDet.add("Paynter, Thomas H. [D-KY");
		senatorDet.add("Richardson, Harry A. [R-DE");
		senatorDet.add("Taylor, Robert L. [D-TN");
		senatorDet.add("Stephenson, Isaac [R-WI");
		senatorDet.add("Bankhead, John H. [D-AL");
		senatorDet.add("Johnston, Joseph F. [D-AL");
		senatorDet.add("Gore, Thomas P. [D-OK");
		senatorDet.add("Owen, Robert L. [D-OK");
		senatorDet.add("Bryan, William J. [D-FL");
		senatorDet.add("Wetmore, George Peabody [R-RI");
		senatorDet.add("Stewart, John W. [R-VT");
		senatorDet.add("Smith, John Walter [D-MD");
		senatorDet.add("Milton, William H. [D-FL");
		senatorDet.add("Page, Carroll S. [R-VT");
		senatorDet.add("Cummins, Albert B. [R-IA");
		senatorDet.add("Bradley, William O. [R-KY");
		senatorDet.add("Bristow, Joseph L. [R-KS");
		senatorDet.add("Burton, Theodore E. [R-OH");
		senatorDet.add("Chamberlain, George E. [D-OR");
		senatorDet.add("Crawford, Coe I. [R-SD");
		senatorDet.add("Fletcher, Duncan U. [D-FL");
		senatorDet.add("Hughes, Charles James, Jr. [D-CO");
		senatorDet.add("Johnson, Martin N. [R-ND");
		senatorDet.add("Jones, Wesley L. [R-WA");
		senatorDet.add("Root, Elihu [R-NY");
		senatorDet.add("Shively, Benjamin F. [D-IN");
		senatorDet.add("Smith, Ellison D. [D-SC");
		senatorDet.add("Oliver, George T. [R-PA");
		senatorDet.add("Lorimer, William [D-IL");
		senatorDet.add("Thompson, Fountain L. [D-ND");
		senatorDet.add("Gordon, James [D-MS");
		senatorDet.add("Purcell, William E. [D-ND");
		senatorDet.add("Percy, Le Roy [D-MS");
		senatorDet.add("Swanson, Claude A. [D-VA");
		senatorDet.add("Young, Lafayette [R-IA");
		senatorDet.add("Terrell, Joseph M. [D-GA");
		senatorDet.add("Thornton, John R. [D-LA");
		senatorDet.add("Elkins, Davis [R-WV");
		senatorDet.add("Gronna, Asle J. [R-ND");
		senatorDet.add("Watson, Clarence W. [D-WV");
		senatorDet.add("Bryan, Nathan P. [D-FL");
		senatorDet.add("Chilton, William E. [D-WV");
		senatorDet.add("Lea, Luke [D-TN");
		senatorDet.add("Lippitt, Henry F. [R-RI");
		senatorDet.add("Hitchcock, Gilbert M. [D-NE");
		senatorDet.add("Johnson, Charles F. [D-ME");
		senatorDet.add("Kern, John W. [D-IN");
		senatorDet.add("McLean, George P. [R-CT");
		senatorDet.add("Martine, James E. [D-NJ");
		senatorDet.add("Myers, Henry L. [D-MT");
		senatorDet.add("Poindexter, Miles [R/PR/R-WA");
		senatorDet.add("Pomerene, Atlee [D-OH");
		senatorDet.add("Reed, James A. [D-MO");
		senatorDet.add("Townsend, Charles [R-MI");
		senatorDet.add("Williams, John Sharp [D-MS");
		senatorDet.add("Works, John D. [R-CA");
		senatorDet.add("O'Gorman, James A. [D-NY");
		senatorDet.add("Kenyon, William S. [R-IA");
		senatorDet.add("Gardner, Obadiah [D-ME");
		senatorDet.add("Smith, Hoke [D-GA");
		senatorDet.add("Ashurst, Henry F [D-AZ");
		senatorDet.add("Catron, Thomas B. [R-NM");
		senatorDet.add("Fall, Albert B. [R-NM");
		senatorDet.add("Smith, Marcus A. [D-AZ");
		senatorDet.add("Sanders, Newell [R-TN");
		senatorDet.add("Massey, William A. [R-NV");
		senatorDet.add("Perky, Kirtland I. [D-ID");
		senatorDet.add("Jackson, William P. [R-MD");
		senatorDet.add("Johnston, Rienzi [D-TX");
		senatorDet.add("Heiskell, John N. [D-AR");
		senatorDet.add("Thomas, Charles S. [D-CO");
		senatorDet.add("Webb, William R. [D-TN");
		senatorDet.add("Kavanaugh, William M. [D-AR");
		senatorDet.add("Pittman, Key [D-NV");
		senatorDet.add("Sheppard, Morris4 [D-TX");
		senatorDet.add("Brady, James H. [R-ID");
		senatorDet.add("Burleigh, Edwin C. [R-ME");
		senatorDet.add("Colt, LeBaron B. [R-RI");
		senatorDet.add("Goff, Nathan [R-WV");
		senatorDet.add("Hughes, William [D-NJ");
		senatorDet.add("James, Ollie M. [D-KY");
		senatorDet.add("Lane, Harry [D-OR");
		senatorDet.add("Norris, George W. [R/I-NE");
		senatorDet.add("Ransdell, Joseph E. [D-LA");
		senatorDet.add("Robinson, Joseph T. [D-AR");
		senatorDet.add("Saulsbury, Willard, Jr. [D-DE");
		senatorDet.add("Shafroth, John F. [D-CO");
		senatorDet.add("Shields, John K. [D-TN");
		senatorDet.add("Sterling, Thomas [R-SD");
		senatorDet.add("Thompson, William H. [D-KS");
		senatorDet.add("Vardaman, James K. [D-MS");
		senatorDet.add("Walsh, Thomas J. [D-MT");
		senatorDet.add("Weeks, John W. [R-MA");
		senatorDet.add("Hollis, Henry F. [D-NH");
		senatorDet.add("Lewis, James Hamilton [D-IL");
		senatorDet.add("Sherman, Lawrence Y. [R-IL");
		senatorDet.add("Lee, Blair [D-MD");
		senatorDet.add("West, William S. [D-GA");
		senatorDet.add("White, Francis S. [D-AL");
		senatorDet.add("Camden, Johnson N., Jr. [D-KY");
		senatorDet.add("Hardwick, Thomas W. [D-GA");
		senatorDet.add("Beckham, John C.W. [D-KY");
		senatorDet.add("Broussard, Robert F. [D-LA");
		senatorDet.add("Harding, Warren G. [R-OH");
		senatorDet.add("Husting, Paul O. [D-WI");
		senatorDet.add("Johnson, Edwin S. [D-SD");
		senatorDet.add("Phelan, James D. [D-CA");
		senatorDet.add("Underwood, Oscar W. [D-AL");
		senatorDet.add("Wadsworth, James W., Jr. [R-NY");
		senatorDet.add("Taggart, Thomas [D-IN");
		senatorDet.add("Fernald, Bert M. [R-ME");
		senatorDet.add("Kirby, William F. [D-AR");
		senatorDet.add("Watson, James E. [R-IN");
		senatorDet.add("Calder, William M. [R-NY");
		senatorDet.add("France, Joseph I. [R-MD");
		senatorDet.add("Frelinghuysen, Joseph S. [R-NJ");
		senatorDet.add("Gerry, Peter G. [D-RI");
		senatorDet.add("Hale, Frederick [R-ME");
		senatorDet.add("Jones, Andrieus A. [D-NM");
		senatorDet.add("Kendrick, John B. [D-WY");
		senatorDet.add("King, William H. [D-UT");
		senatorDet.add("McKellar, Kenneth [D-TN");
		senatorDet.add("New, Harry S. [R-IN");
		senatorDet.add("Sutherland, Howard [R-WV");
		senatorDet.add("Trammel, Park [D-FL");
		senatorDet.add("Wolcott, Josiah O. [D-DE");
		senatorDet.add("Johnson, Hiram W. [R-CA");
		senatorDet.add("McNary, Charles L. [R-OR");
		senatorDet.add("Henderson, Charles B. [D-NV");
		senatorDet.add("Nugent, John F. [D-ID");
		senatorDet.add("Baird, David [R-NJ");
		senatorDet.add("Lenroot, Irvine L. [R-WI");
		senatorDet.add("Guion, Walter [D-LA");
		senatorDet.add("Wilfley, Xenophon P. [D-MO");
		senatorDet.add("Benet, Christie [D-SC");
		senatorDet.add("Drew, Irving W. [R-NH");
		senatorDet.add("Martin, George B. [D-KY");
		senatorDet.add("Gay, Edward J. [D-LA");
		senatorDet.add("Moses, George H. [R-NH");
		senatorDet.add("Pollock, William P. [D-SC");
		senatorDet.add("Spencer, Selden P. [R-MO");
		senatorDet.add("McNary, Charles L. [R-OR");
		senatorDet.add("Capper, Arthur [R-KS");
		senatorDet.add("Dial, Nathaniel B. [D-SC");
		senatorDet.add("Edge, Walter E. [R-NJ");
		senatorDet.add("Harris, William J. [D-GA");
		senatorDet.add("Harrison, Pat [D-MS");
		senatorDet.add("Keyes, Henry W. [R-NH");
		senatorDet.add("McCormick, J. Medill [R-IL");
		senatorDet.add("Newberry, Truman H. [R-MI");
		senatorDet.add("Phipps, Lawrence C. [R-CO");
		senatorDet.add("Stanley, A. Owsley [D-KY");
		senatorDet.add("Walsh, David I. [D-MA");
		senatorDet.add("Glass, Carter [D-VA");
		senatorDet.add("Comer, Braxton B. [D-AL");
		senatorDet.add("Heflin, J. Thomas [D-AL");
		senatorDet.add("Broussard, Edwin S. [D-LA");
		senatorDet.add("Cameron, Ralph H. [R-AZ");
		senatorDet.add("Caraway, T.H. [D-AR");
		senatorDet.add("Ernst, Richard P. [R-KY");
		senatorDet.add("Harreld, John W. [R-OK");
		senatorDet.add("Ladd, Edwin F. [R-ND");
		senatorDet.add("McKinley, William B. [R-IL");
		senatorDet.add("Nicholson, Samuel D. [D-CO");
		senatorDet.add("Norbeck, Peter [R-SD");
		senatorDet.add("Oddie, Tasker L. [R-NV");
		senatorDet.add("Shortridge, Samuel M. [R-CA");
		senatorDet.add("Stanfield, Robert Nelson [R-OR");
		senatorDet.add("Watson, Thomas E. [D-GA");
		senatorDet.add("Weller, Ovington E. [R-MD");
		senatorDet.add("Bursum, Holm O. [R-NM");
		senatorDet.add("du Pont, T. Coleman [R-DE");
		senatorDet.add("Crow, William E. [R-PA");
		senatorDet.add("Pepper, George Wharton [R-PA");
		senatorDet.add("Rawson, Charles A. [R-IA");
		senatorDet.add("Reed, David A. [R-PA");
		senatorDet.add("Felton, Rebecca L. [D-GA");
		senatorDet.add("Bayard, Thomas F., Jr. [D-DE");
		senatorDet.add("George, Walter F. [D-GA");
		senatorDet.add("Couzens, James [R-MI");
		senatorDet.add("Brookhart, Smith W. [R-IA");
		senatorDet.add("Bruce, William Cabell [D-MD");
		senatorDet.add("Copeland, Royal S. [D-NY");
		senatorDet.add("Dill, Clarence C. [D-WA");
		senatorDet.add("Edwards, Edward I. [D-NJ");
		senatorDet.add("Ferris, Woodbridge N. [D-MI");
		senatorDet.add("Fess, Simeon D. [R-OH");
		senatorDet.add("Frazier, Lynn J. [R-ND");
		senatorDet.add("Howell, Robert B. [R-NE");
		senatorDet.add("Mayfield, Earle B. [D-TX");
		senatorDet.add("Neely, Matthew M. [D-WV");
		senatorDet.add("Ralston, Samuel Moffet [D-IN");
		senatorDet.add("Shipstead, Henrik [FL/R-MN");
		senatorDet.add("Stephens, Hubert D. [D-MS");
		senatorDet.add("Wheeler, Burton K. [D-MT");
		senatorDet.add("Adams, Alva B. [D-CO");
		senatorDet.add("Johnson, Magnus [FL-MN");
		senatorDet.add("Dale, Porter H. [R-VT");
		senatorDet.add("Metcalf, Jesse H. [R-RI");
		senatorDet.add("Butler, William M. [R-MA");
		senatorDet.add("Means, Rice W. [R-CO");
		senatorDet.add("Bingham, Hiram [R-CT");
		senatorDet.add("Deneen, Charles S. [R-IL");
		senatorDet.add("Blease, Coleman L. [D-SC");
		senatorDet.add("Bratton, Sam G. [D-NM");
		senatorDet.add("Gillett, Frederick H. [R-MA");
		senatorDet.add("Goff, Guy D. [R-WV");
		senatorDet.add("McMaster, William H. [R-SD");
		senatorDet.add("Pine, William B. [R-OK");
		senatorDet.add("Sackett, Frederic M. [R-KY");
		senatorDet.add("Schall, Thomas D. [R-MN");
		senatorDet.add("Tyson, Lawrence D. [D-TN");
		senatorDet.add("Williams, George H. [R-MO");
		senatorDet.add("La Follette, Robert M., Jr [R/PR-WI");
		senatorDet.add("Robinson, Arthur R. [R-IN");
		senatorDet.add("Nye, Gerald P. [R-ND");
		senatorDet.add("Steck, Daniel F. [D-IA");
		senatorDet.add("Stewart, David W. [R-IA");
		senatorDet.add("Gould, Arthur R. [R-ME");
		senatorDet.add("Hawes, Harry B. [D-MO");
		senatorDet.add("Barkley, Alben W. [D-KY");
		senatorDet.add("Black, Hugo L [D-AL");
		senatorDet.add("Blaine, John J. [R-WI");
		senatorDet.add("Hayden, Carl [D-AZ");
		senatorDet.add("Steiwer, Frederick [R-OR");
		senatorDet.add("Thomas, J.W. Elmer [D-OK");
		senatorDet.add("Tydings, Millard E. [D-MD");
		senatorDet.add("Vare, William S. [R-PA)");
		senatorDet.add("Wagner Robert F. [D-NY");
		senatorDet.add("Waterman, Charles W. [R-CO");
		senatorDet.add("Cutting, Bronson [R-NM");
		senatorDet.add("Vandenberg, Arthur H. [R-MI");
		senatorDet.add("Locher, Cyrus [D-OH");
		senatorDet.add("Thomas, John [R-ID");
		senatorDet.add("Glenn, Otis F. [R-IL");
		senatorDet.add("Larrazolo, Octaviano A. [R-NM");
		senatorDet.add("Hastings, Daniel O. [R-DE");
		senatorDet.add("Burton, Theodore E. [R-OH");
		senatorDet.add("Connally, Tom [D-TX");
		senatorDet.add("Cutting, Bronson [R-NM");
		senatorDet.add("Goldsborough, Phillips Lee [R-MD");
		senatorDet.add("Hatfield, Henry D. [R-WV");
		senatorDet.add("Hebert, Felix [R-RI");
		senatorDet.add("Kean, Hamilton [R-NJ");
		senatorDet.add("Patterson, Roscoe C. [R-MO");
		senatorDet.add("Townsend, John G., Jr. [R-DE");
		senatorDet.add("Walcott, Frederic C. [R-CT");
		senatorDet.add("Allen, Henry J. [R-KS");
		senatorDet.add("Brock, William E. [D-TN");
		senatorDet.add("McCulloch, Roscoe C. [R-OH");
		senatorDet.add("Baird, David, Jr. [R-NJ");
		senatorDet.add("Sullivan, Patrick J. [R-WY");
		senatorDet.add("Grundy, Joseph R [R-PA");
		senatorDet.add("Robsion, John M. [R-KY");
		senatorDet.add("Bulkley, Robert J. [D-OH");
		senatorDet.add("Carey, Robert D. [R-WY");
		senatorDet.add("McGill, George [D-KS");
		senatorDet.add("Williamson, Ben M. [D-KY");
		senatorDet.add("Davis, James J. [R-PA");
		senatorDet.add("Morrow, Dwight W. [R-NJ");
		senatorDet.add("Morrison, Cameron A. [D-NC");
		senatorDet.add("Bailey, Josiah W. [D-NC");
		senatorDet.add("Bankhead, John H., 2d [D-AL");
		senatorDet.add("Bulow, William J. [D-SD");
		senatorDet.add("Byrnes, James F. [D-SC");
		senatorDet.add("Coolidge, Marcus A. [D-MA");
		senatorDet.add("Costigan, Edward P. [D-CO");
		senatorDet.add("Dickinson, L.J. [R-IA");
		senatorDet.add("Gore, Thomas P. [D-OK");
		senatorDet.add("Hull, Cordell [D-TN");
		senatorDet.add("Lewis, James Hamilto [D-IL");
		senatorDet.add("Logan, Marvel M. [D-KY");
		senatorDet.add("White, Wallace H., Jr. [R-ME");
		senatorDet.add("Austin, Warren R. [R-VT");
		senatorDet.add("Caraway, Hattie W. [D-AR");
		senatorDet.add("Barbour, W. Warren [D-NJ");
		senatorDet.add("Long, Huey P. [D-LA");
		senatorDet.add("Cohen, John S. [D-GA");
		senatorDet.add("Walker, Walter [D-CO");
		senatorDet.add("Grammer, Elijah S. [R-WA");
		senatorDet.add("Reynolds, Robert R. [D-NC");
		senatorDet.add("Schuyler, Karl C. [R-CO");
		senatorDet.add("Russell, Richard B., Jr. [D-GA");
		senatorDet.add("Clark, Joel Bennett [Champ) (D-MO");
		senatorDet.add("Bachman, Nathan L. [D-TN");
		senatorDet.add("Bone, Homer T. [D-WA");
		senatorDet.add("Brown, Fred H. [D-NH");
		senatorDet.add("Byrd, Harry Flood [D-VA");
		senatorDet.add("Dieterich, William H. [D-IL");
		senatorDet.add("Duffy, F. Ryan [D-WI");
		senatorDet.add("Lonergan, Augustine [D-CT");
		senatorDet.add("McAdoo, William Gibbs [D-CA");
		senatorDet.add("McCarran, Patrick A. [Pat) (D-NV");
		senatorDet.add("Murphy, Richard Louis [D-IA");
		senatorDet.add("Overton, John H. [D-LA");
		senatorDet.add("Pope, James P. [D-ID");
		senatorDet.add("Thomas, Elbert D. [D-UT");
		senatorDet.add("Van Nuys, Frederick [D-IN");
		senatorDet.add("Erickson, John E. [D-MT");
		senatorDet.add("Hatch, Carl A. [D-NM");
		senatorDet.add("Gibson, Ernest W. [R-VT");
		senatorDet.add("O'Mahoney, Joseph C. [D-WY");
		senatorDet.add("Murray, James E. [D-MT");
		senatorDet.add("Hunter, Richard C. [D-NE");
		senatorDet.add("Bilbo, Theodore G. [D-MS");
		senatorDet.add("Burke, Edward R. [D-NE");
		senatorDet.add("Donahey, Vic [D-OH");
		senatorDet.add("Guffey, Joseph F. [D-PA");
		senatorDet.add("Maloney, Francis T. [D-CT");
		senatorDet.add("Minton, Sherman [D-IN");
		senatorDet.add("Moore, A. Harry [D-NJ");
		senatorDet.add("Radcliffe, George L.P. [D-MD");
		senatorDet.add("Schwellenbach, Lewis B. [D-WA");
		senatorDet.add("Truman, Harry S. [D-MO");
		senatorDet.add("Chavez, Dennis [D-NM");
		senatorDet.add("Holt, Rush D. [D-WV");
		senatorDet.add("Benson, Elmer A. [FL-MN");
		senatorDet.add("Long, Rose McConnell [D-LA");
		senatorDet.add("Loftin, Scott M. [D-FL");
		senatorDet.add("Hill, William L. [D-FL");
		senatorDet.add("Andrews, Charles O. [D-FL");
		senatorDet.add("Gillette, Guy M. [D-IA");
		senatorDet.add("Howard, Guy V. [R-MN");
		senatorDet.add("Pepper, Claude [D-FL");
		senatorDet.add("Brown, Prentiss M. [D-MI");
		senatorDet.add("Hitchcock, Herbert E. [D-SD");
		senatorDet.add("Bridges, Styles [R-NH");
		senatorDet.add("Ellender, Allen J. [D-LA");
		senatorDet.add("Green, Theodore F. [D-RI");
		senatorDet.add("Hughes, James H. [D-DE");
		senatorDet.add("Johnson, Edwin C. [D-CO");
		senatorDet.add("Lee, Joshua B. [D-OK");
		senatorDet.add("Lodge, Henry Cabot, Jr. [R-MA");
		senatorDet.add("Lundeen, Ernest [FL-MN");
		senatorDet.add("Schwartz, Henry H. [D-WY");
		senatorDet.add("Herring, Clyde L. [D-IA");
		senatorDet.add("Smathers, William H. [D-NJ");
		senatorDet.add("Berry, George L. [D-TN");
		senatorDet.add("Graves, Dixie Bibb [D-AL");
		senatorDet.add("Miller, John E. [D-AR");
		senatorDet.add("Hill, J. Lister [D-AL");
		senatorDet.add("Milton, John [D-NJ");
		senatorDet.add("Reames, Alfred Evan [D-OR");
		senatorDet.add("Barry, Alexander G. [R-OR");
		senatorDet.add("Pyle, Gladys [R-SD");
		senatorDet.add("Storke, Thomas M. [D-CA");
		senatorDet.add("Mead, James M. [D-NY");
		senatorDet.add("Clark, D. Worth [D-ID");
		senatorDet.add("Danaher, John A. [R-CT");
		senatorDet.add("Downey, Sheridan [D-CA");
		senatorDet.add("Gurney, J. Chandler [R-SD");
		senatorDet.add("Holman, Rufus C. [R-OR");
		senatorDet.add("Lucas, Scott W. [D-IL");
		senatorDet.add("Reed, Clyde M. [R-KS");
		senatorDet.add("Taft, Robert A. [R-OH");
		senatorDet.add("Tobey, Charles W. [R-NH");
		senatorDet.add("Wiley, Alexander [R-WI");
		senatorDet.add("Stewart, A.T. [Tom) (D-TN");
		senatorDet.add("Slattery, James M. [D-IL");
		senatorDet.add("Chandler, Albert B. [D-KY");
		senatorDet.add("Gibson, Ernest W., Jr. [R-VT");
		senatorDet.add("Ball, Joseph H. [R-MN");
		senatorDet.add("Brooks, C. Wayland [R-IL");
		senatorDet.add("Bunker, Berkeley L. [D-NV");
		senatorDet.add("Wallgren, Monrad C. [D-WA");
		senatorDet.add("Brewster, Ralph O. [R-ME");
		senatorDet.add("Burton, Harold H. [R-OH");
		senatorDet.add("Butler, Hugh A. [R-NE");
		senatorDet.add("Kilgore, Harley M. [D-WV");
		senatorDet.add("Langer, William [R-ND");
		senatorDet.add("McFarland, Ernest W. [D-AZ");
		senatorDet.add("Murdock, Abe [D-UT");
		senatorDet.add("Tunnell, James M. [D-DE");
		senatorDet.add("Willis, Raymond E. [R-IN");
		senatorDet.add("Aiken, George D. [R-VT");
		senatorDet.add("Rosier, Joseph [D-WV");
		senatorDet.add("Spencer, G. Lloyd [D-AR");
		senatorDet.add("Houston, Andrew Jackson [D-TX");
		senatorDet.add("Eastland, James O. [D-MS");
		senatorDet.add("Lumpkin, Alva M. [D-SC");
		senatorDet.add("O'Daniel, W. Lee [D-TX");
		senatorDet.add("Peace, Roger C. [D-SC");
		senatorDet.add("Doxey, Wall [D-MS");
		senatorDet.add("Maybank, Burnet R. [D-SC");
		senatorDet.add("Millikin, Eugene D. [R-CO");
		senatorDet.add("Nelson, Arthur E. [R-MN");
		senatorDet.add("Shott, Hugh I. [R-WV");
		senatorDet.add("Scrugham, James G. [D-NV");
		senatorDet.add("Buck, C. Douglass [R-DE");
		senatorDet.add("Bushfield, Harlan J. [R-SD");
		senatorDet.add("Ferguson, Homer [R-MI");
		senatorDet.add("Hawkes, Albert W. [R-NJ");
		senatorDet.add("McClellan, John L. [D-AR");
		senatorDet.add("Moore, Edward H. [R-OK");
		senatorDet.add("Revercomb, Chapman [R-WV");
		senatorDet.add("Robertson, Edward V. [R-WY");
		senatorDet.add("Wherry, Kenneth S. [R-NE");
		senatorDet.add("Wilson, George A. [R-IA");
		senatorDet.add("Walsh, Arthur [D-NJ");
		senatorDet.add("Jackson, Samuel D. [D-IN");
		senatorDet.add("Weeks, Sinclair [R-MA");
		senatorDet.add("Cordon, Guy [R-OR");
		senatorDet.add("Jenner, William E. [R-IN");
		senatorDet.add("Hall, Wilton E. [D-SC");
		senatorDet.add("Smith, H. Alexander [R-NJ");
		senatorDet.add("Magnuson, Warren G. [D-WA");
		senatorDet.add("Capehart, Homer E. [R-IN");
		senatorDet.add("Fulbright, J. Willia [D-AR");
		senatorDet.add("Hickenlooper, Bourke B. [R-IA");
		senatorDet.add("Hoey, Clyde R. [D-NC");
		senatorDet.add("Johnston, Olin D. [D-SC");
		senatorDet.add("McMahon, Brien [D-CT");
		senatorDet.add("Morse, Wayne L. [R/I/D-OR");
		senatorDet.add("Moses, John [D-ND");
		senatorDet.add("Myers, Francis J. [D-PA");
		senatorDet.add("Taylor, Glen H. [D-ID");
		senatorDet.add("Saltonstall, Leverett [R-MA");
		senatorDet.add("Donnell, Forrest C. [R-MO");
		senatorDet.add("Mitchell, Hugh B. [D-WA");
		senatorDet.add("Hart, Thomas C. [R-CT");
		senatorDet.add("Young, Milton R. [R-ND");
		senatorDet.add("Carville, Edward P. [D-NV");
		senatorDet.add("Knowland, William F. [R-CA");
		senatorDet.add("Huffman, James W. [D-OH");
		senatorDet.add("Gossett, Charles [D-ID");
		senatorDet.add("Stanfill, William A. [R-KY");
		senatorDet.add("Burch, Thomas G. [D-VA");
		senatorDet.add("Swift, George R. [D-AL");
		senatorDet.add("Holland, Spessard L. [D-FL");
		senatorDet.add("Flanders, Ralph E. [R-VT");
		senatorDet.add("Cooper, John Sherman [R-KY");
		senatorDet.add("Dworshak, Henry C. [R-ID");
		senatorDet.add("Robertson, A. Willis [D-VA");
		senatorDet.add("Sparkman, John J. [D-AL");
		senatorDet.add("Taft, Kingsley A. [R-OH");
		senatorDet.add("Umstead, William B. [D-NC");
		senatorDet.add("Cain, Harry P. [R-WA");
		senatorDet.add("Baldwin, Raymond E. [R-CT");
		senatorDet.add("Bricker, John W. [R-OH");
		senatorDet.add("Ecton, Zales N. [R-MT");
		senatorDet.add("Ives, Irving M. [R-NY");
		senatorDet.add("Jenner, William E. [R-IN");
		senatorDet.add("Kem, James P. [R-MO");
		senatorDet.add("Malone, George W. [R-NV");
		senatorDet.add("Martin, Edward [R-PA");
		senatorDet.add("McCarthy, Joseph R. [R-WI");
		senatorDet.add("McGrath, J. Howard [D-RI");
		senatorDet.add("O'Conor, Herbert R. [D-MD");
		senatorDet.add("Thye, Edward J. [R-MN");
		senatorDet.add("Watkins, Arthur V. [R-UT");
		senatorDet.add("Williams, John J. [R-DE");
		senatorDet.add("Stennis, John C. [D-MS");
		senatorDet.add("Feazel, William C. [D-LA");
		senatorDet.add("Bushfield, Vera C. [R-SD");
		senatorDet.add("Broughton, J. Melville [D-NC");
		senatorDet.add("Long, Russell B. [D-LA");
		senatorDet.add("Mundt, Karl E. [R-SD");
		senatorDet.add("Anderson, Clinton P. [D-NM");
		senatorDet.add("Chapman, Virgil M. [D-KY");
		senatorDet.add("Douglas, Paul H. [D-IL");
		senatorDet.add("Frear, J. Allan, Jr. [D-DE");
		senatorDet.add("Hendrickson, Robert C. [R-NJ");
		senatorDet.add("Humphrey, Hubert H. [D-MN");
		senatorDet.add("Hunt, Lester C. [D-WY");
		senatorDet.add("Johnson, Lyndon B. [D-TX");
		senatorDet.add("Kefauver, Estes [D-TN");
		senatorDet.add("Kerr, Robert S. [D-OK");
		senatorDet.add("Miller, Bert H. [D-ID");
		senatorDet.add("Neely, Mathew M. [D-WV");
		senatorDet.add("Schoeppel, Andrew F. [R-KS");
		senatorDet.add("Smith, Margaret Chase [R-ME");
		senatorDet.add("Withers, Garrett L. [D-KY");
		senatorDet.add("Dulles, John Foster [R-NY");
		senatorDet.add("Leahy, Edward L. [D-RI");
		senatorDet.add("Lehman, Herbert H. [D-NY");
		senatorDet.add("Darby, Harry [R-KS");
		senatorDet.add("Benton, William [D-CT");
		senatorDet.add("Clements, Earle C. [D-KY");
		senatorDet.add("Smith, Willis [D-NC");
		senatorDet.add("Nixon, Richard M. [R-CA");
		senatorDet.add("Pastore, John O. [D-RI");
		senatorDet.add("Bennett, Wallace F. [R-UT");
		senatorDet.add("Butler, John M. [R-MD");
		senatorDet.add("Case, Francis [R-SD");
		senatorDet.add("Dirksen, Everett M. [R-IL");
		senatorDet.add("Hennings, Thomas C., Jr. [D-MO");
		senatorDet.add("Monroney, A.S. Mike [D-OK");
		senatorDet.add("Smathers, George A. [D-FL");
		senatorDet.add("Welker, Herman [R-ID");
		senatorDet.add("Duff, James H. [R-PA");
		senatorDet.add("Underwood, Thomas R. [D-KY");
		senatorDet.add("Moody, Blair [D-MI");
		senatorDet.add("Seaton, Fred A. [R-NE");
		senatorDet.add("Purtell, William A. [R-CT");
		senatorDet.add("Bush, Prescott [R-CT");
		senatorDet.add("Cooper, John Sherman [R-KY");
		senatorDet.add("Griswold, Dwight [R-NE");
		senatorDet.add("Potter, Charles E. [R-MI");
		senatorDet.add("Kuchel, Thomas H. [R-CA");
		senatorDet.add("Beall, J. Glenn [R-MD");
		senatorDet.add("Daniel, M. Price [D-TX");
		senatorDet.add("Goldwater, Barry [R-AZ");
		senatorDet.add("Gore, Albert [D-TN");
		senatorDet.add("Jackson, Henry M. [D-WA");
		senatorDet.add("Kennedy, John F. [D-MA");
		senatorDet.add("Mansfield, Mike [D-MT");
		senatorDet.add("Payne, Frederick G. [R-ME");
		senatorDet.add("Symington, Stuart [D-MO");
		senatorDet.add("Lennon, Alton A. [D-NC");
		senatorDet.add("Upton, Robert W. [R-NH");
		senatorDet.add("Burke, Thomas A. [D-OH");
		senatorDet.add("Bowring, Eva [R-NE");
		senatorDet.add("Ervin, Samuel J., Jr. [D-NC");
		senatorDet.add("Crippa, Edward D. [R-WY");
		senatorDet.add("Reynolds, Samuel W. [R-NE");
		senatorDet.add("Daniel, Charles E. [D-SC");
		senatorDet.add("Brown, Ernest S. [R-NV");
		senatorDet.add("Abel, Hazel H. [R-NE");
		senatorDet.add("Cotton, Norris [R-NH");
		senatorDet.add("Hruska, Roman L. [R-NE");
		senatorDet.add("O'Mahoney, Joseph C. [D-WY");
		senatorDet.add("Scott, W. Kerr [D-NC");
		senatorDet.add("Bible, Alan [D-NV");
		senatorDet.add("Bender, George H. [R-OH");
		senatorDet.add("Thurmond, Strom [I-SC");
		senatorDet.add("Curtis, Carl T. [R-NE");
		senatorDet.add("Allott, Gordon [R-CO");
		senatorDet.add("Case, Clifford P. [R-NJ");
		senatorDet.add("Martin, Thomas E. [R-IA");
		senatorDet.add("McNamara, Patrick V [D-MI");
		senatorDet.add("Neuberger, Richard L. [D-OR");
		senatorDet.add("Laird, William R., III [D-WV");
		senatorDet.add("Wofford, Thomas A. [D-SC");
		senatorDet.add("Humphreys, Robert [D-KY");
		senatorDet.add("Cooper, John Sherman [R-KY");
		senatorDet.add("Thurmond, Strom [D/R-SC");
		senatorDet.add("Carroll, John A. [D-CO");
		senatorDet.add("Clark, Joseph S. [D-PA");
		senatorDet.add("Morton, Thruston B. [R-KY");
		senatorDet.add("Talmadge, Herman E. [D-GA");
		senatorDet.add("Javits, Jacob K. [R-NY");
		senatorDet.add("Blakley, William A. [D-TX");
		senatorDet.add("Yarborough, Ralph W. [D-TX");
		senatorDet.add("Proxmire, Willia [D-WI");
		senatorDet.add("Hoblitzell, John D., Jr. [R-WV");
		senatorDet.add("Jordan, B. Everett [D-NC");
		senatorDet.add("Randolph, Jennings [D-WV");
		senatorDet.add("Young, Stephen M. [D-OH");
		senatorDet.add("Scott, Hugh D. [R-PA");
		senatorDet.add("Engle, Clair [D-CA");
		senatorDet.add("Keating, Kenneth B. [R-NY");
		senatorDet.add("McCarthy, Eugene J. [D-MN");
		senatorDet.add("Prouty, Winston L. [R-VT");
		senatorDet.add("Dodd, Thomas J. [D-CT");
		senatorDet.add("Byrd, Robert C. [D-WV");
		senatorDet.add("Byrd, Robert [D-WV");
		senatorDet.add("Williams, Harrison A., Jr. [D-NJ");
		senatorDet.add("Bartlett, Edward L. [D-AK");
		senatorDet.add("Muskie, Edmund S. [D-ME");
		senatorDet.add("Gruening, Ernest [D-AK");
		senatorDet.add("Hart, Philip A. [D-MI");
		senatorDet.add("Hartke, Vance [D-IN");
		senatorDet.add("McGee, Gale W. [D-WY");
		senatorDet.add("Cannon, Howard W. [D-NV");
		senatorDet.add("Long, Oren E. [D-HI");
		senatorDet.add("Fong, Hiram L. [R-HI");
		senatorDet.add("Brunsdale, C. Norman [R-ND");
		senatorDet.add("Lusk, Hall S. [D-OR");
		senatorDet.add("Burdick, Quentin N. [D-ND");
		senatorDet.add("Long, Edward V. [D-MO");
		senatorDet.add("Neuberger, Maurine B. [D-OR");
		senatorDet.add("Smith, Benjamin [D-MA");
		senatorDet.add("Boggs, J. Caleb [R-DE");
		senatorDet.add("Metcalf, Lee [D-MT");
		senatorDet.add("Hickey, J. J. [D-WY");
		senatorDet.add("Miller, Jack [R-IA");
		senatorDet.add("Pell, Claiborne [D-RI");
		senatorDet.add("Tower, John G. [R-TX");
		senatorDet.add("Murphy, Maurice J., Jr. [R-NH");
		senatorDet.add("Pearson, James B. [R-KS");
		senatorDet.add("Bottum, Joe H. [R-SD");
		senatorDet.add("Jordan, Leonard B. [R-ID");
		senatorDet.add("Simpson, Milward L. [R-WY");
		senatorDet.add("Kennedy, Edward M. [D-MA");
		senatorDet.add("Kennedy, Edward [D-MA");
		senatorDet.add("McIntyre, Thomas J. [D-NH");
		senatorDet.add("Mechem, Edwin L. [R-NM");
		senatorDet.add("Ribicoff, Abraham A. [D-CT");
		senatorDet.add("McGovern, George [D-SD");
		senatorDet.add("Brewster, Daniel B. [D-MD");
		senatorDet.add("Inouye, Daniel K. [D-HI");
		senatorDet.add("Inouye, Daniel [D-HI");
		senatorDet.add("Dominick, Peter H. [R-CO");
		senatorDet.add("Bayh, Birch [D-IN");
		senatorDet.add("Edmondson, J. Howard [D-OK");
		senatorDet.add("Nelson, Gaylord [D-WI");
		senatorDet.add("Walters, Herbert S. [D-TN");
		senatorDet.add("Salinger, Pierre [D-CA");
		senatorDet.add("Bass, Ross [D-TN");
		senatorDet.add("Montoya, Joseph M. [D-NM");
		senatorDet.add("Harris, Fred R. [D-OK");
		senatorDet.add("Mondale, Walter F. [D-MN");
		senatorDet.add("Murphy, George [R-CA");
		senatorDet.add("Kennedy, Robert F. [D-NY");
		senatorDet.add("Fannin, Paul J. [R-AZ");
		senatorDet.add("Tydings, Joseph D. [D-MD");
		senatorDet.add("Russell, Donald [D-SC");
		senatorDet.add("Byrd, Harry F., Jr. [I-VA");
		senatorDet.add("Griffin, Robert [R-MI");
		senatorDet.add("Hollings, Ernest F. [D-SC");
		senatorDet.add("Hollings, Ernest [D-SC");
		senatorDet.add("Spong, William B., Jr. [D-VA");
		senatorDet.add("Hansen, Clifford P. [R-WY");
		senatorDet.add("Percy, Charles H. [R-IL");
		senatorDet.add("Brooke, Edward W. [R-MA");
		senatorDet.add("Baker, Howard H., Jr. [R-TN");
		senatorDet.add("Hatfield, Mark O. [R-OR");
		senatorDet.add("Goodell, Charles E. [R-NY");
		senatorDet.add("Cook, Marlow [R-KY");
		senatorDet.add("Stevens, Ted [R-AK");
		senatorDet.add("Eagleton, Thomas F. [D-MO");
		senatorDet.add("Goldwater, Barry M. [R-AZ");
		senatorDet.add("Schweiker, Richard S. [R-PA");
		senatorDet.add("Mathias, Charles McC., Jr. [R-MD");
		senatorDet.add("Dole, Robert J. [R-KS");
		senatorDet.add("Gurney, Edward J. [R-FL");
		senatorDet.add("Hughes, Harold E. [D-IA");
		senatorDet.add("Bellmon, Henry L. [R-OK");
		senatorDet.add("Cranston, Alan [D-CA");
		senatorDet.add("Saxbe, William B. [R-OH");
		senatorDet.add("Allen, James B. [D-AL");
		senatorDet.add("Packwood, Robert W. [R-OR");
		senatorDet.add("Packwood, Bob [R-OR");
		senatorDet.add("Gravel, Mike [D-AK");
		senatorDet.add("Smith, Ralph T. [R-IL");
		senatorDet.add("Stevenson, Adlai E., III [D-IL");
		senatorDet.add("Roth, William V., Jr. [R-DE");
		senatorDet.add("Roth Jr, William [R-DE");
		senatorDet.add("Tunney, John V. [D-CA");
		senatorDet.add("Bentsen, Lloyd, M. [D-TX");
		senatorDet.add("Taft, Robert, Jr. [R-OH");
		senatorDet.add("Brock, William E., III [R-TN");
		senatorDet.add("Beall, J. Glenn, Jr. [R-MD");
		senatorDet.add("Weicker, Lowell P., Jr. [R-CT");
		senatorDet.add("Buckley, James L. [C/R-NY");
		senatorDet.add("Chiles, Lawton M., Jr. [D-FL");
		senatorDet.add("Gambrell, David H. [D-GA");
		senatorDet.add("Stafford, Robert T. [R-VT");
		senatorDet.add("Edwards, Elaine S. [D-LA");
		senatorDet.add("Nunn, Sam [D-GA");
		senatorDet.add("Johnston, J. Bennett [D-LA");
		senatorDet.add("Hathaway, William D. [D-ME");
		senatorDet.add("Scott, William L. [R-VA");
		senatorDet.add("McClure, James A. [R-ID");
		senatorDet.add("Abourezk, James [D-SD");
		senatorDet.add("Bartlett, Dewey F. [R-OK");
		senatorDet.add("Helms, Jesse [R-NC");
		senatorDet.add("Huddleston, Walter [D-KY");
		senatorDet.add("Clark, Dick [D-IA");
		senatorDet.add("Haskell, Floyd K. [D-CO");
		senatorDet.add("Domenici, Pete V. [R-NM");
		senatorDet.add("Domenici, Pete [R-NM");
		senatorDet.add("Biden, Joseph R., Jr. [D-DE");
		senatorDet.add("Biden Jr, Joseph [D-DE");
		senatorDet.add("Biden Jr., Joseph R. [D-DE");
		senatorDet.add("Metzenbaum, Howard M. [D-OH");
		senatorDet.add("Laxalt, Paul D. [R-NV");
		senatorDet.add("Garn, E. J. (Jake) [R-UT");
		senatorDet.add("Glenn, John [D-OH");
		senatorDet.add("Glenn, John H., Jr. [D-OH");
		senatorDet.add("Ford, Wendell H. [D-KY");
		senatorDet.add("Wyman, Louis C. [R-NH");
		senatorDet.add("Stone, Richard [D-FL");
		senatorDet.add("Culver, John C. [D-IA");
		senatorDet.add("Bumpers, Dale [D-AR");
		senatorDet.add("Morgan, Robert [D-NC");
		senatorDet.add("Hart, Gary [D-CO");
		senatorDet.add("Leahy, Patrick J. [D-VT");
		senatorDet.add("Leahy, Patrick [D-VT");
		senatorDet.add("Durkin, John A. [D-NH");
		senatorDet.add("Danforth, John C. [R-MO");
		senatorDet.add("Zorinsky, Edward [D-NE");
		senatorDet.add("Chafee, John H. [R-RI");
		senatorDet.add("Metzenbaum, Howard [D-OH");
		senatorDet.add("Riegle, Donald W., Jr. [D-MI");
		senatorDet.add("Anderson, Wendell R. [D-MN");
		senatorDet.add("Hayakawa, S. I. [R-CA");
		senatorDet.add("Matsunaga, Spark M. [D-HI");
		senatorDet.add("Melcher, John [D-MT");
		senatorDet.add("Heinz, John [R-PA");
		senatorDet.add("Sarbanes, Paul S. [D-MD");
		senatorDet.add("Sarbanes, Paul [D-MD");
		senatorDet.add("Moynihan, Daniel Patrick [D-NY");
		senatorDet.add("Moynihan, Daniel P. [D-NY");
		senatorDet.add("Moynihan, Daniel [D-NY");
		senatorDet.add("Lugar, Richard G. [R-IN");
		senatorDet.add("Lugar, Richard [R-IN");
		senatorDet.add("Sasser, Jim [D-TN");
		senatorDet.add("DeConcini, Dennis [D-AZ");
		senatorDet.add("Hatch, Orrin G. [R-UT");
		senatorDet.add("Hatch, Orrin [R-UT");
		senatorDet.add("Schmitt, Harrison H. [R-NM");
		senatorDet.add("Wallop, Malcolm [R-WY");
		senatorDet.add("Hodges, Kaneaster, Jr. [D-AR");
		senatorDet.add("Hatfield, Paul G. [D-MT");
		senatorDet.add("Humphrey, Muriel [D-MN");
		senatorDet.add("Allen, Maryon [D-AL");
		senatorDet.add("Stewart, Donald W. [D-AL");
		senatorDet.add("Durenberger, Dave [R-MN");
		senatorDet.add("Baucus, Max [D-MT");
		senatorDet.add("Kassebaum, Nancy Landon [R-KS");
		senatorDet.add("Cochran, Thad [R-MS");
		senatorDet.add("Boschwitz, Rudy [R-MN");
		senatorDet.add("Simpson, Alan K. [R-WY");
		senatorDet.add("Warner, John W. [R-VA");
		senatorDet.add("Warner, John [R-VA");
		senatorDet.add("Pryor, David H. [D-AR");
		senatorDet.add("Armstrong, William L. [R-CO");
		senatorDet.add("Armstrong, William J. [R-CO");
		senatorDet.add("Cohen, William S. [R-ME");
		senatorDet.add("Tsongas, Paul E. [D-MA");
		senatorDet.add("Pressler, Larry [R-SD");
		senatorDet.add("Boren, David L. [D-OK");
		senatorDet.add("Exon, J. James [D-NE");
		senatorDet.add("Levin, Carl [D-MI");
		senatorDet.add("Bradley, Bill [D-NJ");
		senatorDet.add("Heflin, Howell [D-AL");
		senatorDet.add("Jepsen, Roger W. [R-IA");
		senatorDet.add("Humphrey, Gordon J. [R-NH");
		senatorDet.add("Mitchell, George J. [D-ME");
		senatorDet.add("Rudman, Warren [R-NH");
		senatorDet.add("Hawkins, Paula [R-FL");
		senatorDet.add("Denton, Jeremiah A. [R-AL");
		senatorDet.add("Dodd, Christopher J. [D-CT");
		senatorDet.add("Dodd, Christopher [D-CT");
		senatorDet.add("Mattingly, Mack F. [R-GA");
		senatorDet.add("Symms, Steve [R-ID");
		senatorDet.add("Dixon, Alan J. [D-IL");
		senatorDet.add("Quayle, J. Danforth [R-IN");
		senatorDet.add("Grassley, Charles [R-IA");
		senatorDet.add("Grassley, Charles E. [R-IA");
		senatorDet.add("Grassley, Chuck [R-IA");
		senatorDet.add("D'Amato, Alfonse M. [R-NY");
		senatorDet.add("D'Amato, Alfonse [R-NY");
		senatorDet.add("East, John P. [R-NC");
		senatorDet.add("Andrews, Mark [R-ND");
		senatorDet.add("Nickles, Don [R-OK");
		senatorDet.add("Specter, Arlen [R/D-PA");
		senatorDet.add("Abdnor, James [R-SD");
		senatorDet.add("Gorton, Slade [R-WA");
		senatorDet.add("Kasten, Robert W., Jr. [R-WI");
		senatorDet.add("Brady, Nicholas F. [R-NJ");
		senatorDet.add("Trible, Paul S., Jr. [R-VA");
		senatorDet.add("Bingaman, Jeff [D-NM");
		senatorDet.add("Hecht, Chic [R-NV");
		senatorDet.add("Wilson, Pete [R-CA");
		senatorDet.add("Evans, Daniel J. [R-WA");
		senatorDet.add("Kerry, John F. [D-MA");
		senatorDet.add("Kerry, John [D-MA");
		senatorDet.add("Simon, Paul [D-IL");
		senatorDet.add("Harkin, Tom [D-IA");
		senatorDet.add("Gore, Albert, Jr. [D-TN");
		senatorDet.add("Gramm, Phil [R-TX");
		senatorDet.add("McConnell, Mitch [R-KY");
		senatorDet.add("Rockefeller, John D., IV [D-WV");
		senatorDet.add("Rockefeller IV, John [D-WV");
		senatorDet.add("Rockefeller IV, John D. [D-WV");
		senatorDet.add("Rockefeller, Jay [D-WV");
		senatorDet.add("Broyhill, James T. [R-NC");
		senatorDet.add("Sanford, Terry [D-NC");
		senatorDet.add("Breaux, John B. [D-LA");
		senatorDet.add("Breaux, John [D-LA");
		senatorDet.add("Adams, Brock [D-WA");
		senatorDet.add("Wirth, Timothy [D-CO");
		senatorDet.add("Mikulski, Barbara A. [D-MD");
		senatorDet.add("Mikulski, Barbara [D-MD");
		senatorDet.add("Fowler, Wyche [D-GA");
		senatorDet.add("Shelby, Richard C. [D/R-AL");
		senatorDet.add("Shelby, Richard [D/R-AL");
		senatorDet.add("Daschle, Thomas A. [D-SD");
		senatorDet.add("Daschle, Thomas [D-SD");
		senatorDet.add("McCain, John [R-AZ");
		senatorDet.add("Reid, Harry [D-NV");
		senatorDet.add("Reid, Harry M. [D-NV");
		senatorDet.add("Graham, Bob [D-FL");
		senatorDet.add("Bond, Kit [R-MO");
		senatorDet.add("Conrad, Kent [D-ND");
		senatorDet.add("Karnes, David [R-NE");
		senatorDet.add("Lott, Trent [R-MS");
		senatorDet.add("Jeffords, Jim [R/I-VT");
		senatorDet.add("Jeffords, James [R/I-VT");
		senatorDet.add("Jeffords, James M. [R/I-VT");
		senatorDet.add("Coats, Dan [R-IN");
		senatorDet.add("Mack, Connie [R-FL");
		senatorDet.add("Bryan, Richard [D-NV");
		senatorDet.add("Robb, Charles S. [D-VA");
		senatorDet.add("Kerrey, Bob [D-NE");
		senatorDet.add("Kerrey, J. Robert [D-NE");
		senatorDet.add("Kerrey, Robert [D-NE");
		senatorDet.add("Kohl, Herbert [D-WI");
		senatorDet.add("Lieberman, Joseph [D-CT");
		senatorDet.add("Burns, Conrad R. [R-MT");
		senatorDet.add("Burns, Conrad [R-MT");
		senatorDet.add("Akaka, Daniel K. [D-HI");
		senatorDet.add("Akaka, Daniel [D-HI");
		senatorDet.add("Smith, Robert C. [R-NH");
		senatorDet.add("Smith, Bob [R-NH");
		senatorDet.add("Brown, George Hanks [Hank) (R-CO");
		senatorDet.add("Craig, Larry E. [R-ID");
		senatorDet.add("Craig, Larry [R-ID");
		senatorDet.add("Wellstone, Paul [D-MN");
		senatorDet.add("Seymour, John [R-CA");
		senatorDet.add("Wofford, Harris [D-PA");
		senatorDet.add("Burdick, Jocelyn [D-ND");
		senatorDet.add("Feinstein, Dianne [D-CA");
		senatorDet.add("Feinstein Dianne [D-CA");
		senatorDet.add("Conrad, Kent [D-ND");
		senatorDet.add("Dorgan, Byron L. [D-ND");
		senatorDet.add("Dorgan, Byron [D-ND");
		senatorDet.add("Mathews, Harlan [D-TN");
		senatorDet.add("Boxer, Barbara [D-CA");
		senatorDet.add("Gregg, Judd [R-NH");
		senatorDet.add("Campbell, Ben Nighthorse [D/R-CO");
		senatorDet.add("Moseley-Braun, Carol [D-IL");
		senatorDet.add("Faircloth, Lauch [R-NC");
		senatorDet.add("Coverdell, Paul [R-GA");
		senatorDet.add("Murray, Patty [D-WA");
		senatorDet.add("Feingold, Russell [D-WI");
		senatorDet.add("Bennett, Robert F. [R-UT");
		senatorDet.add("Bennett, Robert [R-UT");
		senatorDet.add("Kempthorne, Dirk [R-ID");
		senatorDet.add("Krueger, Robert C. [D-TX");
		senatorDet.add("Hutchison, Kathryn Ann Bailey [R-TX");
		senatorDet.add("Inhofe, James M. [R-OK");
		senatorDet.add("Thompson, Fred [R-TN");
		senatorDet.add("Snowe, Olympia J. [R-ME");
		senatorDet.add("Kyl, Jon [R-AZ");
		senatorDet.add("DeWine, Mike [R-OH");
		senatorDet.add("DeWine, Michael [R-OH");
		senatorDet.add("Thomas, Craig [R-WY");
		senatorDet.add("Santorum, Rick [R-PA");
		senatorDet.add("Grams, Rod [R-MN");
		senatorDet.add("Ashcroft, John [R-MO");
		senatorDet.add("Abraham, Spencer [R-MI");
		senatorDet.add("Frist, Bill [R-TN");
		senatorDet.add("Wyden, Ron [D-OR");
		senatorDet.add("Frahm, Sheila [R-KS");
		senatorDet.add("Brownback, Samuel Dale [R-KS");
		senatorDet.add("Roberts, Pat [R-KS");
		senatorDet.add("Durbin, Richard J. [D-IL");
		senatorDet.add("Torricelli, Robert G. [D-NJ");
		senatorDet.add("Johnson, Tim [D-SD");
		senatorDet.add("Allard, Wayne [R-CO");
		senatorDet.add("Allard, A. Wayne [R-CO");
		senatorDet.add("Reed, Jack [D-RI");
		senatorDet.add("Hutchinson, Tim [R-AR");
		senatorDet.add("Cleland, Max [D-GA");
		senatorDet.add("Landrieu, Mary [D-LA");
		senatorDet.add("Landrieu, Mary L. [D-LA");
		senatorDet.add("Sessions, Jeff [R-AL");
		senatorDet.add("Smith, Gordon [R-OR");
		senatorDet.add("Hagel, Chuck [R-NE");
		senatorDet.add("Hagel, Charles [R-NE");
		senatorDet.add("Collins, Susan M. [R-ME");
		senatorDet.add("Enzi, Michael B. [R-WY");
		senatorDet.add("Enzi, Mike [R-WY");
		senatorDet.add("Schumer, Charles [D-NY");
		senatorDet.add("Schumer, Charles E. [D-NY");
		senatorDet.add("Bunning, Jim [R-KY");
		senatorDet.add("Crapo, Mike [R-ID");
		senatorDet.add("Crapo, Michael [R-ID");
		senatorDet.add("Lincoln, Blanche L. [D-AR");
		senatorDet.add("Voinovich, George [R-OH");
		senatorDet.add("Bayh, Evan [D-IN");
		senatorDet.add("Fitzgerald, Peter [R-IL");
		senatorDet.add("Chafee, Lincoln D. [R-RI");
		senatorDet.add("Miller, Zell B. [D-GA");
		senatorDet.add("Nelson, Bill [D-FL");
		senatorDet.add("Nelson, E. Benjamin [D-FL");
		senatorDet.add("Carper, Tom [D-DE");
		senatorDet.add("Carper, Thomas R. [D-DE");
		senatorDet.add("Stabenow, Debbie [D-MI");
		senatorDet.add("Ensign, John [R-NV");
		senatorDet.add("Ensign, John E. [R-NV");
		senatorDet.add("Allen, George [R-VA");
		senatorDet.add("Cantwell, Maria [D-WA");
		senatorDet.add("Nelson, Ben [D-NE");
		senatorDet.add("Clinton, Hillary Rodham [D-NY");
		senatorDet.add("Corzine, Jon [D-NJ");
		senatorDet.add("Corzine, Jon S. [D-NJ");
		senatorDet.add("Carnahan, Jean [D-MO");
		senatorDet.add("Dayton, Mark [D-MN");
		senatorDet.add("Barkley, Dean [I-MN");
		senatorDet.add("Talent, James [R-MO");
		senatorDet.add("Talent, Jim [R-MO");
		senatorDet.add("Cornyn, John [R-TX");
		senatorDet.add("Murkowski, Lisa [R-AK");
		senatorDet.add("Chambliss, Saxby [R-GA");
		senatorDet.add("Graham, Lindsey [R-SC");
		senatorDet.add("Graham, Lindsey O. [R-SC");
		senatorDet.add("Sununu, John [R-NH");
		senatorDet.add("Sununu, John E. [R-NH");
		senatorDet.add("Alexander, Lamar [R-TN");
		senatorDet.add("Dole, Elizabeth [R-NC");
		senatorDet.add("Coleman, Norm [R-MN");
		senatorDet.add("Pryor, Mark [D-AR");
		senatorDet.add("Burr, Richard [R-NC");
		senatorDet.add("DeMint, James [R-SC");
		senatorDet.add("DeMint, Jim [R-SC");
		senatorDet.add("Coburn, Tom [R-OK");
		senatorDet.add("Thune, John [R-SD");
		senatorDet.add("Isakson, Johnny [R-GA");
		senatorDet.add("Vitter, David [R-LA");
		senatorDet.add("Martinez, Mel [R-FL");
		senatorDet.add("Obama, Barack [D-IL");
		senatorDet.add("Salazar, Ken [D-CO");
		senatorDet.add("Menendez, Robert [D-NJ");
		senatorDet.add("Cardin, Ben [D-MD");
		senatorDet.add("Cardin, Benjamin L. [D-MD");
		senatorDet.add("Sanders, Bernie [I-VT");
		senatorDet.add("Brown, Sherrod [D-OH");
		senatorDet.add("Webb, Jim [D-VA");
		senatorDet.add("Casey, Robert [D-PA");
		senatorDet.add("Casey, Robert P., Jr. [D-PA");
		senatorDet.add("Corker, Robert [R-TN");
		senatorDet.add("Corker, Bob [R-TN");
		senatorDet.add("McCaskill, Claire [D-MO");
		senatorDet.add("Klobuchar, Amy [D-MN");
		senatorDet.add("Whitehouse, Sheldon [D-RI");
		senatorDet.add("Tester, Jon [D-MT");
		senatorDet.add("Barrasso, John [R-WY");
		senatorDet.add("Wicker, Roger F. [R-MS");
		senatorDet.add("Udall, Mark [D-CO");
		senatorDet.add("Udall, Tom [D-NM");
		senatorDet.add("Johanns, Mike [R-NE");
		senatorDet.add("Shaheen, Jeanne [D-NH");
		senatorDet.add("Warner, Mark [D-VA");
		senatorDet.add("Warner, Mark R. [D-VA");
		senatorDet.add("Risch, Jim [R-ID");
		senatorDet.add("Hagan, Kay [D-NC");
		senatorDet.add("Merkley, Jeff [D-OR");
		senatorDet.add("Begich, Mark [D-AK");
		senatorDet.add("Burris, Roland [D-IL");
		senatorDet.add("Kaufman, Edward [D-DE");
		senatorDet.add("Bennet, Michael [D-CO");
		senatorDet.add("Bennet, Michael F. [D-CO");
		senatorDet.add("Bennet, Michael R. [D-CO");
		senatorDet.add("Gillibrand, Kirsten 11 [D-NY) 191");
		senatorDet.add("LeMieux, George [R-FL");
		senatorDet.add("Kirk, Paul G, Jr. [D-MA");
		senatorDet.add("Brown, Scott P. [R-MA");
		senatorDet.add("Goodwin, Carte P. [D-WV");
		senatorDet.add("Manchin, Joe [D-WV");
		senatorDet.add("Coons, Christopher [D-DE");
		senatorDet.add("Coons, Christopher A. [D-DE");
		senatorDet.add("Kirk, Mark13 [R-IL) 191");
		senatorDet.add("Coats, Daniel [R-IN");
		senatorDet.add("Blunt, Roy [R-MO");
		senatorDet.add("Moran, Jerry [R-KS");
		senatorDet.add("Portman, Rob [R-OH");
		senatorDet.add("Boozman, John [R-AR");
		senatorDet.add("Toomey, Pat [R-PA");
		senatorDet.add("Hoeven, John [R-ND");
		senatorDet.add("Rubio, Marco [R-FL");
		senatorDet.add("Johnson, Ron [R-WI");
		senatorDet.add("Paul, Rand [R-KY");
		senatorDet.add("Blumenthal, Richard [D-CT");
		senatorDet.add("Lee, Mike [R-UT");
		senatorDet.add("Ayotte, Kelly [R-NH");
		senatorDet.add("Heller, Dean [R-NV");
		senatorDet.add("Schatz, Brian E. [D-HI");
		senatorDet.add("Scott, Tim14 [R-SC");
		senatorDet.add("Baldwin, Tammy [D-WI");
		senatorDet.add("Flake, Jeff [R-AZ");
		senatorDet.add("Donnelly, Joe [D-IN");
		senatorDet.add("Murphy, Chris [D-CT");
		senatorDet.add("Hirono, Mazie [D-HI");
		senatorDet.add("Heinrich, Martin [D-NM");
		senatorDet.add("King, Angus [I-ME");
		senatorDet.add("Kaine, Tim [D-VA");
		senatorDet.add("Cruz, Ted [R-TX");
		senatorDet.add("Warren, Elizabeth [D-MA");
		senatorDet.add("Fischer, Deb [R-NE");
		senatorDet.add("Heitkamp, Heidi [D-ND");
		senatorDet.add("Cowan, William M. [D-MA");
		senatorDet.add("Chiesa, Jeffrey S. [R-NJ");
		senatorDet.add("Chiesa, Jeff [R-NJ");
		senatorDet.add("Markey, Edward J. [D-MA");
		senatorDet.add("Booker, Cory [D-NJ");
		senatorDet.add("Booker, Cory A. [D-NJ");
		senatorDet.add("Walsh, John15 [D-MT");
		senatorDet.add("Capito, Shelley Moore [R-WV");
		senatorDet.add("Peters, Gary [D-MI");
		senatorDet.add("Cassidy, Bill [R-LA");
		senatorDet.add("Gardner, Cory [R-CO");
		senatorDet.add("Lankford, James [R-OK");
		senatorDet.add("Cotton, Tom [R-AR");
		senatorDet.add("Daines, Steve [R-MT");
		senatorDet.add("Rounds, Mike [R-SD");
		senatorDet.add("Perdue, David [R-GA");
		senatorDet.add("Tillis, Thom [R-NC");
		senatorDet.add("Ernst, Joni [R-IA");
		senatorDet.add("Sasse, Ben [R-NE");
		senatorDet.add("Sullivan, Dan [R-AK");
		
		senatorDet.add("Bond, Christopher S. [R-MO");
		senatorDet.add("Bond, Christopher [R-MO");
		senatorDet.add("Murkowski, Frank H. [R-AK");
		senatorDet.add("Murkowski, Frank [R-AK");
		senatorDet.add("Hutchinson, Kay Bailey [R-TX");
		senatorDet.add("Reed, John F. [D-RI");

		// > 109 has an affiliation with name
		return (ArrayList<String>) senatorDet;
		
	}
	
}
