package edu.usc.cssl.tacit.common.queryprocess;

public enum QueryOperatorType {
	STRING_EQUALS, STRING_CONTAINS, STRING_STARS_WITH, STRING_ENDS_WITH, INTEGER_GREATER_THAN, INTEGER_LESS_THAN, INTEGER_EQUALS, DOUBLE_EQUALS, DOUBLE_GREATER_THAN, DOUBLE_LESS_THAN;
}
